# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: acquis.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Window functions

ID_TEXT = 10000
ID_PANGRIDLIST = 10001
ID_BUTREFRESH = 10002

def ElencoFilesFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Elenco files da acquisire - Doppio click per avviare l'importazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.Panel( parent, ID_PANGRIDLIST, wx.DefaultPosition, [750,200], wx.SUNKEN_BORDER )
    item2.SetName( "pangridlist" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item3 = wx.Button( parent, ID_BUTREFRESH, "Aggiorna elenco", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetName( "butrefresh" )
    item0.Add( item3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_BUTRIC = 10003

def RiceviFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.GridSizer( 0, 1, 0, 0 )
    
    item1 = wx.GridSizer( 0, 2, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Documenti da scaricare:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3 = wx.StaticText( parent, ID_TEXT, "-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetForegroundColour( wx.BLUE )
    item3.SetName( "numdocs" )
    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item1, 0, 0, 5 )

    item4 = wx.Button( parent, ID_BUTRIC, "Scarica documenti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetName( "butric" )
    item0.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
