# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: azisetup.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.datectrl import DateCtrl
from awc.controls.numctrl import NumCtrl
from awc.controls.radiobox import RadioBox
from awc.controls.checkbox import CheckBox
from awc.controls.linktable import LinkTable

from awc.controls.entries import FolderEntryCtrl

from anag.basetab import WorkZoneNotebook, PhotoContainerPanel

from anag.mag import MagazzDialog

import Env
bt = Env.Azienda.BaseTab

import anag.lib as alib

class ScorpIvaRadioBox(RadioBox):
    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=' 1')

class UnoZeroCheckBox(CheckBox):
    def __init__(self, *args, **kwargs):
        CheckBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values={True: 1, False: 0})
    
    def SetValue(self, v):
        if isinstance(v, (str, unicode)):
            v = int(v)
        CheckBox.SetValue(self, v)


class SovrapposizioneRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=(0,1))

class RitAccCheckBox(UnoZeroCheckBox):

    def __init__(self, *args, **kwargs):
        UnoZeroCheckBox.__init__(self, *args, **kwargs)
        self.Bind(wx.EVT_CHECKBOX, self.OnRitAccChanged)

    def OnRitAccChanged(self, event):
        for name in 'per com'.split():
            self.GetParent().FindWindowByName('setup_con%sritacc'%name).Enable(self.IsChecked())
        event.Skip()

class ScoDocCheckBox(UnoZeroCheckBox):

    def __init__(self, *args, **kwargs):
        UnoZeroCheckBox.__init__(self, *args, **kwargs)
        self.Bind(wx.EVT_CHECKBOX, self.OnScoDocChanged)

    def OnScoDocChanged(self, event):
        for name in 'per com'.split():
            self.GetParent().FindWindowByName('setup_con%sscodoc'%name).Enable(self.IsChecked())
        event.Skip()

class MagProvMovRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=(" ", "E"))


class OrdPartiteRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=["S",  "D"])



from awc.controls.choice import ChoiceData

class RegimeFiscaleChoice(ChoiceData):
    
    def __init__(self, *args, **kwargs):
        ChoiceData.__init__(self, *args, **kwargs)
        self.SetDataLink(values=[n for n in range(1,20,1)])



class SoggettoEmittenteRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=[" ", "C", "T"])


class TipoRitenutaChoice(ChoiceData):
    
    def __init__(self, *args, **kwargs):
        ChoiceData.__init__(self, *args, **kwargs)
        self.SetDataLink(values=["1", "2"])
    
    def SetValue(self, value):
        if value:
            value = str(int(value))
            ChoiceData.SetValue(self, value)


class TipoCassaPrevidenzaChoice(ChoiceData):
    
    def __init__(self, *args, **kwargs):
        ChoiceData.__init__(self, *args, **kwargs)
        self.SetDataLink(values=[n for n in range(1,23,1)])

class FtElTipoCodiceRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=('P','F','B'))




# Window functions

ID_NOTEBOOK = 15000
ID_BTNOK = 15001

def AziendaSetup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = WorkZoneNotebook( parent, ID_NOTEBOOK, wx.DefaultPosition, wx.DefaultSize, 0 )
    item1 = item2
    
    item3 = wx.Panel( item2, -1 )
    DatiAziendaFunc(item3, False)
    item2.AddPage( item3, "Dati azienda" )

    item4 = wx.Panel( item2, -1 ); item4.SetName('contabpanel')
    ContabSetup(item4, False)
    item2.AddPage( item4, "Contabilità" )

    item5 = wx.Panel( item2, -1 ); item5.SetName('magazzpanel')
    MagazzSetup(item5, False)
    item2.AddPage( item5, "Magazzino" )

    item6 = wx.Panel( item2, -1 ); item6.SetName('opzionipanel')
    OpzioniFunc(item6, False)
    item2.AddPage( item6, "Opzioni" )

    item7 = wx.Panel( item2, -1 )
    FTEL_Setup(item7, False)
    item2.AddPage( item7, "Fattura Elettronica" )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item9 = wx.Button( parent, ID_BTNOK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetDefault()
    item9.SetName( "btnok" )
    item8.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 15002
ID_ESERCIZIOGG = 15003
ID_ESERCIZIOMM = 15004
ID_ESERCIZIOERR = 15005
ID_CODATECO = 15006
ID_CONSOVGES = 15007
ID_RADIOBOX = 15008
ID_CONTABVAL = 15009
ID_CONTABDECIMP = 15010
ID_CHECKBOX = 15011
ID_CONBILRICL = 15012
ID_CONBILRCEE = 15013
ID_CONATTRITACC = 15014
ID_CONPERRITACC = 15015
ID_CONCOMRITACC = 15016
ID_CONATTSCODOC = 15017
ID_CONPERSCODOC = 15018
ID_CONCOMSCODOC = 15019
ID_SCADORD = 15020
ID_GESSOLPAG = 15021
ID_DOCSOLPAG = 15022
ID_GGSSOLPAG = 15023
ID_EFFCONSCA = 15024

def ContabSetup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item3 = wx.StaticBox( parent, -1, "Esercizio contabile" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )
    
    item4 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item5 = wx.StaticText( parent, ID_TEXT, "Giorno e mese di inizio dell'esercizio contabile:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item6 = NumCtrl( parent, integerWidth=2, allowNegative=False); item6.SetName('setup_esercizio_startgg')
    item4.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "/", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item7, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item8 = NumCtrl( parent, integerWidth=2, allowNegative=False); item8.SetName('setup_esercizio_startmm')
    item4.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.StaticText( parent, ID_ESERCIZIOERR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetForegroundColour( wx.RED )
    item9.SetName( "esercizio_err" )
    item4.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4.AddGrowableCol( 4 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.StaticBox( parent, -1, "Spesometro" )
    item10 = wx.StaticBoxSizer( item11, wx.VERTICAL )
    
    item12 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item13 = wx.StaticText( parent, ID_TEXT, "Cod.Attività Ateco2007:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item14 = TextCtrl( parent, ID_CODATECO, "", wx.DefaultPosition, [80,-1], 0 )
    item14.SetName( "setup_azienda_codateco" )
    item12.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item16 = SovrapposizioneRadioBox( parent, ID_CONSOVGES, "Chiusure contabili", wx.DefaultPosition, wx.DefaultSize, 
        ["Senza sovrapposizione d'esercizio","Con sovrapposizione d'esercizio"] , 1, wx.RA_SPECIFY_COLS )
    item16.SetName( "setup_consovges" )
    item15.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item17 = RadioBox( parent, ID_RADIOBOX, "Tipo di gestione dell'IVA", wx.DefaultPosition, wx.DefaultSize, 
        ["Ordinaria","Semplificata"] , 1, wx.RA_SPECIFY_COLS )
    item17.SetName( "setup_tipo_contab" )
    item15.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item18 = RadioBox( parent, ID_RADIOBOX, "Periodicità di liquidazione IVA", wx.DefaultPosition, wx.DefaultSize, 
        ["Mensile","Trimestrale"] , 1, wx.RA_SPECIFY_COLS )
    item18.SetName( "setup_liqiva_periodic" )
    item15.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item15.AddGrowableCol( 0 )

    item15.AddGrowableCol( 1 )

    item0.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item20 = wx.StaticBox( parent, -1, "Impostazione valuta di conto" )
    item19 = wx.StaticBoxSizer( item20, wx.VERTICAL )
    
    item21 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item22 = wx.StaticText( parent, ID_TEXT, "Valuta di conto:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item22, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item23 = LinkTable(parent, ID_CONTABVAL ); item23.SetDataLink( bt.TABNAME_VALUTE, "setup_contab_valcon", None); item23.SetObligatory(True)
    item21.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Numero di decimali su importi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item24, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item25 = NumCtrl( parent, integerWidth=2, allowNegative=False); item25.SetName('setup_contab_decimp')
    item21.Add( item25, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item21.AddGrowableCol( 1 )

    item19.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticBox( parent, -1, "Gestione fidi clienti" )
    item26 = wx.StaticBoxSizer( item27, wx.VERTICAL )
    
    item28 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Attiva la gestione dei fidi sui clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item28.SetName( "setup_gesfidicli" )
    item26.Add( item28, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item30 = wx.StaticBox( parent, -1, "Bilanci" )
    item29 = wx.StaticBoxSizer( item30, wx.HORIZONTAL )
    
    item31 = UnoZeroCheckBox( parent, ID_CONBILRICL, "Attiva riclassificazioni di bilancio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.SetName( "setup_conbilricl" )
    item29.Add( item31, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item32 = UnoZeroCheckBox( parent, ID_CONBILRCEE, "Attiva riclassificazioni CEE", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetName( "setup_conbilrcee" )
    item29.Add( item32, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item34 = wx.StaticBox( parent, -1, "Ritenute d'Acconto" )
    item33 = wx.StaticBoxSizer( item34, wx.HORIZONTAL )
    
    item35 = RitAccCheckBox( parent, ID_CONATTRITACC, "Attiva gestione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item35.SetName( "setup_conattritacc" )
    item33.Add( item35, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item36 = wx.StaticText( parent, ID_TEXT, "Calcolo %:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item36, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item37 = NumCtrl( parent, integerWidth=2, fractionWidth=2, allowNegative=False); item37.SetName('setup_conperritacc')
    item33.Add( item37, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item38 = wx.StaticText( parent, ID_TEXT, "da applicare all'imponibile in % del:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item38, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item39 = NumCtrl( parent, integerWidth=3, fractionWidth=2, allowNegative=False); item39.SetName('setup_concomritacc')
    item33.Add( item39, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item41 = wx.StaticBox( parent, -1, "Sconto esterno" )
    item40 = wx.StaticBoxSizer( item41, wx.HORIZONTAL )
    
    item42 = ScoDocCheckBox( parent, ID_CONATTSCODOC, "Attiva gestione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.SetName( "setup_conattscodoc" )
    item40.Add( item42, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item43 = wx.StaticText( parent, ID_TEXT, "Calcolo %:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.Add( item43, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item44 = NumCtrl( parent, integerWidth=2, fractionWidth=2, allowNegative=False); item44.SetName('setup_conperscodoc')
    item40.Add( item44, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item45 = wx.StaticText( parent, ID_TEXT, "da applicare all'imponibile in % del:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.Add( item45, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item46 = NumCtrl( parent, integerWidth=3, fractionWidth=2, allowNegative=False); item46.SetName('setup_concomscodoc')
    item40.Add( item46, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item47 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item48 = OrdPartiteRadioBox( parent, ID_SCADORD, "Ordinameno scadenzari clienti/fornitori", wx.DefaultPosition, wx.DefaultSize, 
        ["Data scadenza","Data documento"] , 1, wx.RA_SPECIFY_ROWS )
    item48.SetName( "setup_scadord" )
    item47.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item50 = wx.StaticBox( parent, -1, "Solleciti pagamento" )
    item49 = wx.StaticBoxSizer( item50, wx.VERTICAL )
    
    item51 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item52 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item53 = UnoZeroCheckBox( parent, ID_GESSOLPAG, "Attiva gestione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item53.SetName( "setup_gessolpag" )
    item52.Add( item53, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item54 = UnoZeroCheckBox( parent, ID_DOCSOLPAG, "Allega documenti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item54.SetName( "setup_docsolpag" )
    item52.Add( item54, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item51.Add( item52, 0, wx.ALIGN_CENTER, 5 )

    item55 = wx.StaticText( parent, ID_TEXT, "GG scad:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item51.Add( item55, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item56 = NumCtrl( parent, integerWidth=3, fractionWidth=0, allowNegative=False); item56.SetName('setup_ggssolpag')
    item51.Add( item56, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item49.Add( item51, 0, wx.ALIGN_CENTER, 5 )

    item47.Add( item49, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item58 = wx.StaticBox( parent, -1, "Contabilizzazione effetti" )
    item57 = wx.StaticBoxSizer( item58, wx.VERTICAL )
    
    item59 = UnoZeroCheckBox( parent, ID_EFFCONSCA, "Usa la data di scadenza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item59.SetName( "setup_effconsca" )
    item57.Add( item59, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item47.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item47.AddGrowableCol( 2 )

    item0.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_MAGDEFAULT = 15025
ID_magdec_qta = 15026
ID_magdec_prez = 15027
ID_magricpre = 15028
ID_MAGPZCONF = 15029
ID_MAGPZGRIP = 15030
ID_MAGSCORPCOS = 15031
ID_MAGSCORPPRE = 15032
ID_FOREIGN = 15033
ID_MAGSCOCAT = 15034
ID_MAGGESACC = 15035
ID_MAGEANPREFIX = 15036
ID_MAGDATCHI = 15037
ID_MAGNUMLIS = 15038
ID_MAGDATLIS = 15039
ID_MAGBCOLIS = 15040
ID_MAGFORLIS = 15041
ID_MAGROWLIS = 15042
ID_MAGVLIFOR = 15043
ID_MAGVLIMAR = 15044
ID_MAGVLICAT = 15045
ID_MAGVLIGRU = 15046
ID_MAGRICLIS = 15047
ID_MAGSCOLIS = 15048
ID_MAGPPROMO = 15049
ID_MAGVRGLIS = 15050
ID_MAGVSGLIS = 15051
ID_MAGREPLIS = 15052
ID_MAGRELLIS = 15053
ID_MAGSEPLIS = 15054
ID_MAGSELLIS = 15055
ID_MAGERPLIS = 15056
ID_MAGESPLIS = 15057
ID_MAGATTGRIP = 15058
ID_MAGCDEGRIP = 15059
ID_LINE = 15060
ID_MAGATTGRIF = 15061
ID_MAGCDEGRIF = 15062
ID_MAGAGGGRIP = 15063
ID_MAGALWGRIP = 15064
ID_MAGDATGRIP = 15065
ID_MAGNOCODEVET = 15066
ID_MAGNOCDEFVET = 15067
ID_MAGEXTRAVET = 15068
ID_MAGNOCODEDES = 15069
ID_MAGNOCDEFDES = 15070
ID_MAGIMGPROD = 15071
ID_MAGDIGSEARCH = 15072
ID_MAGRETSEARCH = 15073
ID_MAGEXCSEARCH = 15074
ID_MAGVISGIA = 15075
ID_MAGVISDIS = 15076
ID_MAGVISCOS = 15077
ID_MAGVISPRE = 15078
ID_MAGVISCPF = 15079
ID_MAGVISBCD = 15080
ID_MAGPROVATT = 15081
ID_MAGPROVCLI = 15082
ID_MAGPROVPRO = 15083
ID_MAGPROVMOV = 15084
ID_MAGPROVSEQ = 15085

def MagazzSetup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Magazzino di default per operazioni di carico/scarico e immissione documenti" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Magazzino:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item5 = LinkTable(parent, ID_MAGDEFAULT ); item5.SetDataLink( bt.TABNAME_MAGAZZ, "setup_magazz_default:site %s" % Env.Azienda.config.Site_name, MagazzDialog); item5.SetObligatory(True)
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3.AddGrowableCol( 1 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item8 = wx.StaticBox( parent, -1, "Numero di decimali da gestire" )
    item7 = wx.StaticBoxSizer( item8, wx.VERTICAL )
    
    item9 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item10 = wx.StaticText( parent, ID_TEXT, "Quantità:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item11 = NumCtrl( parent, integerWidth=2, allowNegative=False); item11.SetName('setup_magdec_qta')
    item9.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Prezzi unitari:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item12, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item13 = NumCtrl( parent, integerWidth=2, allowNegative=False); item13.SetName('setup_magdec_prez')
    item9.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item15 = wx.StaticBox( parent, -1, "Prezzi" )
    item14 = wx.StaticBoxSizer( item15, wx.VERTICAL )
    
    item16 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item17 = wx.StaticText( parent, ID_TEXT, "Ricarica predefinita:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.Add( item17, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item18 = NumCtrl( parent, ID_magricpre, integerWidth=3, allowNegative=False); item18.SetName('setup_magricpre')
    item16.Add( item18, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item20 = wx.StaticBox( parent, -1, "Confezioni" )
    item19 = wx.StaticBoxSizer( item20, wx.VERTICAL )
    
    item21 = UnoZeroCheckBox( parent, ID_MAGPZCONF, "Gestisci", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetName( "setup_magpzconf" )
    item19.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item22 = UnoZeroCheckBox( parent, ID_MAGPZGRIP, "Su griglie", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "setup_magpzgrip" )
    item19.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item6.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item6.AddGrowableCol( 0 )

    item6.AddGrowableCol( 1 )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item23 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item24 = ScorpIvaRadioBox( parent, ID_MAGSCORPCOS, "I costi su scheda prodotto sono:", wx.DefaultPosition, wx.DefaultSize, 
        ["Imponibili: l'IVA sarà aggiunta","Ivati: l'IVA sarà scorporata"] , 1, wx.RA_SPECIFY_COLS )
    item24.SetName( "setup_magscorpcos" )
    item23.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item25 = ScorpIvaRadioBox( parent, ID_MAGSCORPPRE, "I prezzi su scheda prodotto sono:", wx.DefaultPosition, wx.DefaultSize, 
        ["Imponibili: l'IVA sarà aggiunta","Ivati: l'IVA sarà scorporata"] , 1, wx.RA_SPECIFY_COLS )
    item25.SetName( "setup_magscorppre" )
    item23.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item23.AddGrowableCol( 0 )

    item23.AddGrowableCol( 1 )

    item0.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item28 = wx.StaticBox( parent, -1, "Gestisci" )
    item27 = wx.StaticBoxSizer( item28, wx.VERTICAL )
    
    item29 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item30 = wx.StaticText( parent, ID_TEXT, "Ricariche:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.Add( item30, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item31 = NumCtrl(parent, ID_FOREIGN, integerWidth=1, allowNegative=False); item31.SetName('setup_magnumric'); item31.SetToolTipString("Indicare il numero delle ricariche da gestire (0-6)")
    item29.Add( item31, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item32 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.Add( item32, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item33 = NumCtrl(parent, ID_FOREIGN, integerWidth=1, allowNegative=False); item33.SetName('setup_magnumsco'); item33.SetToolTipString("Indicare il numero degli sconti da gestire (0-6)")
    item29.Add( item33, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item27.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item35 = wx.StaticBox( parent, -1, "" )
    item34 = wx.StaticBoxSizer( item35, wx.VERTICAL )
    
    item36 = UnoZeroCheckBox( parent, ID_MAGSCOCAT, "Attiva sconti per categoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.SetName( "setup_magscocat" )
    item34.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item37 = UnoZeroCheckBox( parent, ID_MAGGESACC, "Attiva gestione acconti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.SetName( "setup_maggesacc" )
    item34.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item26.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item39 = wx.StaticBox( parent, -1, "Codifica barcodes" )
    item38 = wx.StaticBoxSizer( item39, wx.HORIZONTAL )
    
    item40 = wx.StaticText( parent, ID_TEXT, "EAN13 C.C.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item40, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item41 = wx.TextCtrl( parent, ID_MAGEANPREFIX, "", wx.DefaultPosition, [30,-1], 0 )
    item41.SetName( "setup_mageanprefix" )
    item38.Add( item41, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item43 = wx.StaticBox( parent, -1, "Chiusura" )
    item42 = wx.StaticBoxSizer( item43, wx.HORIZONTAL )
    
    item44 = wx.StaticText( parent, ID_TEXT, "Data ultima chiusura magazzino:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.Add( item44, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item45 = DateCtrl( parent, ID_MAGDATCHI, "", wx.DefaultPosition, [80,-1], 0 )
    item45.SetName( "setup_magdatchi" )
    item42.Add( item45, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item26.AddGrowableCol( 0 )

    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item48 = wx.StaticBox( parent, -1, "Gestione Listini di vendita" )
    item47 = wx.StaticBoxSizer( item48, wx.VERTICAL )
    
    item49 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item50 = wx.StaticText( parent, ID_TEXT, "Num.Listini:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item49.Add( item50, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item51 = NumCtrl(parent, ID_MAGNUMLIS, integerWidth=1, allowNegative=False); item51.SetName('setup_magnumlis'); item51.SetToolTipString("Indicare il numero dei listini da gestire (0-9)")
    item49.Add( item51, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item52 = UnoZeroCheckBox( parent, ID_MAGDATLIS, "Per data", wx.DefaultPosition, wx.DefaultSize, 0 )
    item52.SetToolTip( wx.ToolTip("Attiva la gestione dei listini per data") )
    item52.SetName( "setup_magdatlis" )
    item49.Add( item52, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item47.Add( item49, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item53 = wx.BoxSizer( wx.HORIZONTAL )
    
    item54 = UnoZeroCheckBox( parent, ID_MAGBCOLIS, "Barcode", wx.DefaultPosition, wx.DefaultSize, 0 )
    item54.SetToolTip( wx.ToolTip("Attiva la gestione dei listini per data") )
    item54.SetName( "setup_magbcolis" )
    item53.Add( item54, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item55 = UnoZeroCheckBox( parent, ID_MAGFORLIS, "Cod.Forn.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.SetToolTip( wx.ToolTip("Attiva la codifica prodotto del fornitore sul listino") )
    item55.SetName( "setup_magforlis" )
    item53.Add( item55, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item56 = UnoZeroCheckBox( parent, ID_MAGROWLIS, "Su riga", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.SetToolTip( wx.ToolTip("Attiva la selezione del listino su ogni riga del documento") )
    item56.SetName( "setup_magrowlis" )
    item53.Add( item56, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item47.Add( item53, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item46.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item58 = wx.StaticBox( parent, -1, "Listini variabili per:" )
    item57 = wx.StaticBoxSizer( item58, wx.VERTICAL )
    
    item59 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item60 = UnoZeroCheckBox( parent, ID_MAGVLIFOR, "Fornit", wx.DefaultPosition, wx.DefaultSize, 0 )
    item60.SetName( "setup_magvlifor" )
    item59.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item61 = UnoZeroCheckBox( parent, ID_MAGVLIMAR, "Marca", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.SetName( "setup_magvlimar" )
    item59.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item62 = UnoZeroCheckBox( parent, ID_MAGVLICAT, "Categ.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item62.SetName( "setup_magvlicat" )
    item59.Add( item62, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item63 = UnoZeroCheckBox( parent, ID_MAGVLIGRU, "Gruppo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item63.SetName( "setup_magvligru" )
    item59.Add( item63, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item57.Add( item59, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item65 = wx.StaticBox( parent, -1, "Sui listini:" )
    item64 = wx.StaticBoxSizer( item65, wx.VERTICAL )
    
    item66 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item67 = wx.StaticText( parent, ID_TEXT, "Ricar:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item67, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item68 = NumCtrl(parent, ID_MAGRICLIS, integerWidth=1, allowNegative=False); item68.SetName('setup_magriclis'); item68.SetToolTipString("Indicare il numero delle ricariche da gestire sui listini (0-9)")
    item66.Add( item68, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item69 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item69, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item70 = NumCtrl(parent, ID_MAGSCOLIS, integerWidth=1, allowNegative=False); item70.SetName('setup_magscolis'); item70.SetToolTipString("Indicare il numero delle scontistiche da gestire sui listini (0-9)")
    item66.Add( item70, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item64.Add( item66, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item64, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item72 = wx.StaticBox( parent, -1, "Promoz." )
    item71 = wx.StaticBoxSizer( item72, wx.HORIZONTAL )
    
    item73 = UnoZeroCheckBox( parent, ID_MAGPPROMO, "Attiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item73.SetToolTip( wx.ToolTip("Attiva le condizioni promozionali sui prodotti") )
    item73.SetName( "setup_magppromo" )
    item71.Add( item73, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item46.Add( item71, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item75 = wx.StaticBox( parent, -1, "Su gruppo pr.:" )
    item74 = wx.StaticBoxSizer( item75, wx.VERTICAL )
    
    item76 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item77 = wx.StaticText( parent, ID_TEXT, "Ricar:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item76.Add( item77, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item78 = NumCtrl(parent, ID_MAGVRGLIS, integerWidth=1, allowNegative=False); item78.SetName('setup_magvrglis'); item78.SetToolTipString("Indicare il numero delle ricariche del gruppo prezzi da visualizzare (0-3)")
    item76.Add( item78, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item79 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item76.Add( item79, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item80 = NumCtrl(parent, ID_MAGVSGLIS, integerWidth=1, allowNegative=False); item80.SetName('setup_magvsglis'); item80.SetToolTipString("Indicare il numero delle scontistiche del gruppo prezzi da visualizzare (0-3)")
    item76.Add( item80, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item74.Add( item76, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item74, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item82 = wx.StaticBox( parent, -1, "Visualizza %effettiva:" )
    item81 = wx.StaticBoxSizer( item82, wx.VERTICAL )
    
    item83 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item84 = wx.StaticText( parent, ID_TEXT, "Ricarica:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item83.Add( item84, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item85 = UnoZeroCheckBox( parent, ID_MAGREPLIS, "Prezzo p.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.SetToolTip( wx.ToolTip("Attiva la visualizzazione della ricarica effettiva del prezzo al pubblico rispetto al costo ultimo") )
    item85.SetName( "setup_magreplis" )
    item83.Add( item85, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item86 = UnoZeroCheckBox( parent, ID_MAGRELLIS, "Listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item86.SetToolTip( wx.ToolTip("Attiva la visualizzazione della ricarica effettiva di ogni listino rispetto al costo ultimo") )
    item86.SetName( "setup_magrellis" )
    item83.Add( item86, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item87 = wx.StaticText( parent, ID_TEXT, "Sconto:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item83.Add( item87, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item88 = UnoZeroCheckBox( parent, ID_MAGSEPLIS, "Prezzo p.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item88.SetToolTip( wx.ToolTip("Attiva la visualizzazione dello sconto effettivo del costo ultimo rispetto al prezzo al pubblico") )
    item88.SetName( "setup_magseplis" )
    item83.Add( item88, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item89 = UnoZeroCheckBox( parent, ID_MAGSELLIS, "Listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item89.SetToolTip( wx.ToolTip("Attiva la visualizzazione dello sconto effettivo del costo ultimo rispetto ad ogni listino") )
    item89.SetName( "setup_magsellis" )
    item83.Add( item89, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item81.Add( item83, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46.Add( item81, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item91 = wx.StaticBox( parent, -1, "Su prodotto:" )
    item90 = wx.StaticBoxSizer( item91, wx.VERTICAL )
    
    item92 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item93 = wx.StaticText( parent, ID_TEXT, "Ricar:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.Add( item93, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item94 = NumCtrl(parent, ID_MAGERPLIS, integerWidth=1, allowNegative=False); item94.SetName('setup_magerplis'); item94.SetToolTipString("Indicare il numero delle ricariche del prodotto da gestire (0-3)")
    item92.Add( item94, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item95 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.Add( item95, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item96 = NumCtrl(parent, ID_MAGESPLIS, integerWidth=1, allowNegative=False); item96.SetName('setup_magesplis'); item96.SetToolTipString("Indicare il numero delle scontistiche del prodotto da gestire (0-3)")
    item92.Add( item96, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item90.Add( item92, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item90, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item46.AddGrowableCol( 1 )

    item46.AddGrowableCol( 2 )

    item46.AddGrowableCol( 3 )

    item0.Add( item46, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item97 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item99 = wx.StaticBox( parent, -1, "Griglie prezzi Clienti/Fornitori" )
    item98 = wx.StaticBoxSizer( item99, wx.HORIZONTAL )
    
    item100 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item101 = UnoZeroCheckBox( parent, ID_MAGATTGRIP, "Attiva clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item101.SetToolTip( wx.ToolTip("Attiva la gestione delle griglie prezzi di vendita sui clienti") )
    item101.SetName( "setup_magattgrip" )
    item100.Add( item101, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item102 = UnoZeroCheckBox( parent, ID_MAGCDEGRIP, "Cod.esterna prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item102.SetToolTip( wx.ToolTip("Attiva la codifica del prodotto sulla griglia da parte del cliente") )
    item102.SetName( "setup_magcdegrip" )
    item100.Add( item102, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item98.Add( item100, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item103 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item98.Add( item103, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item104 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item105 = UnoZeroCheckBox( parent, ID_MAGATTGRIF, "Attiva fornitori", wx.DefaultPosition, wx.DefaultSize, 0 )
    item105.SetToolTip( wx.ToolTip("Attiva la gestione delle griglie prezzi di acquisto sui fornitori") )
    item105.SetName( "setup_magattgrif" )
    item104.Add( item105, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item106 = UnoZeroCheckBox( parent, ID_MAGCDEGRIF, "Cod.esterna prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item106.SetToolTip( wx.ToolTip("Attiva la codifica del prodotto sulla griglia da parte del fornitore") )
    item106.SetName( "setup_magcdegrif" )
    item104.Add( item106, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item98.Add( item104, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item107 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item98.Add( item107, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item108 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item109 = UnoZeroCheckBox( parent, ID_MAGAGGGRIP, "Aggiorna da doc.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item109.SetToolTip( wx.ToolTip("Attiva la facoltÃ  di creare/aggiornare la griglia dal dataentry di magazzino") )
    item109.SetName( "setup_magagggrip" )
    item108.Add( item109, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item110 = UnoZeroCheckBox( parent, ID_MAGALWGRIP, "Default sempre", wx.DefaultPosition, wx.DefaultSize, 0 )
    item110.SetToolTip( wx.ToolTip("Attiva di default l'aggiornamento della griglia dal dataentry di magazzino") )
    item110.SetName( "setup_magalwgrip" )
    item108.Add( item110, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item111 = UnoZeroCheckBox( parent, ID_MAGDATGRIP, "Griglie per data", wx.DefaultPosition, wx.DefaultSize, 0 )
    item111.SetToolTip( wx.ToolTip("Attiva la gestione delle griglie per data") )
    item111.SetName( "setup_magdatgrip" )
    item108.Add( item111, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item98.Add( item108, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item112 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item98.Add( item112, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item97.Add( item98, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item113 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item115 = wx.StaticBox( parent, -1, "Vettori" )
    item114 = wx.StaticBoxSizer( item115, wx.HORIZONTAL )
    
    item116 = UnoZeroCheckBox( parent, ID_MAGNOCODEVET, "Variaz.manuale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item116.SetToolTip( wx.ToolTip("Attiva la possibilitÃ  di variazione manuale del vettore sul singolo documento, senza doverlo codificare") )
    item116.SetName( "setup_magnocodevet" )
    item114.Add( item116, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item117 = UnoZeroCheckBox( parent, ID_MAGNOCDEFVET, "Default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item117.SetToolTip( wx.ToolTip("Imposta di default il nuovo documento con giÃ  spuntata la casella di variazione manuale del vettore") )
    item117.SetName( "setup_magnocdefvet" )
    item114.Add( item117, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item118 = UnoZeroCheckBox( parent, ID_MAGEXTRAVET, "Extra-dati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item118.SetToolTip( wx.ToolTip("Attiva extra-dati sui vettori") )
    item118.SetName( "setup_magextravet" )
    item114.Add( item118, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item113.Add( item114, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item120 = wx.StaticBox( parent, -1, "Destinazioni merce" )
    item119 = wx.StaticBoxSizer( item120, wx.HORIZONTAL )
    
    item121 = UnoZeroCheckBox( parent, ID_MAGNOCODEDES, "Variaz.manuale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item121.SetToolTip( wx.ToolTip("Attiva la possibilitÃ  di variazione manuale della destinazione merce sul singolo documento, senza doverla codificare") )
    item121.SetName( "setup_magnocodedes" )
    item119.Add( item121, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item122 = UnoZeroCheckBox( parent, ID_MAGNOCDEFDES, "Default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item122.SetToolTip( wx.ToolTip("Imposta di default il nuovo documento con giÃ  spuntata la casella di variazione manuale della destinazione") )
    item122.SetName( "setup_magnocdefdes" )
    item119.Add( item122, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item113.Add( item119, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.RIGHT, 5 )

    item113.AddGrowableCol( 0 )

    item113.AddGrowableRow( 1 )

    item97.Add( item113, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item97.AddGrowableCol( 1 )

    item0.Add( item97, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item123 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item125 = wx.StaticBox( parent, -1, "Immagine del prodotto" )
    item124 = wx.StaticBoxSizer( item125, wx.VERTICAL )
    
    item126 = UnoZeroCheckBox( parent, ID_MAGIMGPROD, "Attiva se presente", wx.DefaultPosition, wx.DefaultSize, 0 )
    item126.SetName( "setup_magimgprod" )
    item124.Add( item126, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item123.Add( item124, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item128 = wx.StaticBox( parent, -1, "Ricerca prodotti" )
    item127 = wx.StaticBoxSizer( item128, wx.HORIZONTAL )
    
    item129 = CheckBox( parent, ID_MAGDIGSEARCH, "Cerca in digitaz. codice", wx.DefaultPosition, wx.DefaultSize, 0 )
    item129.SetName( "setup_magdigsearch" )
    item127.Add( item129, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item130 = UnoZeroCheckBox( parent, ID_MAGRETSEARCH, "Cerca con Invio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item130.SetName( "setup_magretsearch" )
    item127.Add( item130, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item131 = UnoZeroCheckBox( parent, ID_MAGEXCSEARCH, "Ricerca esclusiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item131.SetName( "setup_magexcsearch" )
    item127.Add( item131, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item132 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item127.Add( item132, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.RIGHT, 5 )

    item133 = wx.StaticText( parent, ID_TEXT, "Visualizza:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item127.Add( item133, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item134 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item135 = UnoZeroCheckBox( parent, ID_MAGVISGIA, "Giacenza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item135.SetName( "setup_magvisgia" )
    item134.Add( item135, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item136 = UnoZeroCheckBox( parent, ID_MAGVISDIS, "Disponib.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item136.SetName( "setup_magvisdis" )
    item134.Add( item136, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item127.Add( item134, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item137 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item138 = UnoZeroCheckBox( parent, ID_MAGVISCOS, "Costo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item138.SetName( "setup_magviscos" )
    item137.Add( item138, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item139 = UnoZeroCheckBox( parent, ID_MAGVISPRE, "Prezzo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item139.SetName( "setup_magvispre" )
    item137.Add( item139, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item127.Add( item137, 0, wx.ALIGN_CENTER, 5 )

    item140 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item141 = UnoZeroCheckBox( parent, ID_MAGVISCPF, "Cod.Forn.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item141.SetName( "setup_magviscpf" )
    item140.Add( item141, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item142 = UnoZeroCheckBox( parent, ID_MAGVISBCD, "Barcode", wx.DefaultPosition, wx.DefaultSize, 0 )
    item142.SetName( "setup_magvisbcd" )
    item140.Add( item142, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item127.Add( item140, 0, wx.ALIGN_CENTER, 5 )

    item123.Add( item127, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item123.AddGrowableCol( 1 )

    item0.Add( item123, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item143 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item145 = wx.StaticBox( parent, -1, "Provvigioni" )
    item144 = wx.StaticBoxSizer( item145, wx.HORIZONTAL )
    
    item146 = UnoZeroCheckBox( parent, ID_MAGPROVATT, "Attiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item146.SetName( "setup_magprovatt" )
    item144.Add( item146, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item147 = UnoZeroCheckBox( parent, ID_MAGPROVCLI, "Su clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item147.SetName( "setup_magprovcli" )
    item144.Add( item147, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item148 = UnoZeroCheckBox( parent, ID_MAGPROVPRO, "Su prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item148.SetName( "setup_magprovpro" )
    item144.Add( item148, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item143.Add( item144, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item149 = MagProvMovRadioBox( parent, ID_MAGPROVMOV, "Provvig. sui movimenti", wx.DefaultPosition, wx.DefaultSize, 
        ["Default","Eredita"] , 1, wx.RA_SPECIFY_ROWS )
    item149.SetName( "setup_magprovmov" )
    item143.Add( item149, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item151 = wx.StaticBox( parent, -1, "Gerarchia ereditarietà" )
    item150 = wx.StaticBoxSizer( item151, wx.HORIZONTAL )
    
    item152 = wx.StaticText( parent, ID_TEXT, "Sequenza priorità provvig.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item150.Add( item152, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item153 = wx.TextCtrl( parent, ID_MAGPROVSEQ, "", wx.DefaultPosition, [80,-1], 0 )
    item153.SetName( "setup_magprovseq" )
    item150.Add( item153, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item143.Add( item150, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item143.AddGrowableCol( 2 )

    item0.Add( item143, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_OPTNOTIFICHE = 15086
ID_OPTTABSEARCH = 15087
ID_OPTDIGSEARCH = 15088
ID_OPTSPASEARCH = 15089
ID_OPTLNKCRDPDC = 15090
ID_OPTLNKGRDPDC = 15091
ID_OPTLNKCRDCLI = 15092
ID_OPTLNKGRDCLI = 15093
ID_OPTLNKCRDFOR = 15094
ID_OPTLNKGRDFOR = 15095
ID_BACKUPDIR = 15096
ID_GCP_USER = 15097
ID_GCP_PSWD = 15098
ID_GC_PRINT = 15099

def OpzioniFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Notifiche" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = UnoZeroCheckBox( parent, ID_OPTNOTIFICHE, "Attiva notifiche (Email, XMPP)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetName( "setup_optnotifiche" )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.StaticBox( parent, -1, "Ricerche" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )
    
    item6 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item7 = UnoZeroCheckBox( parent, ID_OPTTABSEARCH, "Attiva la ricerca con il tasto Tab", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetName( "setup_opttabsearch" )
    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item8 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Attiva la ricerca con il tasto Invio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "setup_optretsearch" )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = UnoZeroCheckBox( parent, ID_OPTDIGSEARCH, "Cerca durante la digitazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetName( "setup_optdigsearch" )
    item6.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item10 = UnoZeroCheckBox( parent, ID_OPTSPASEARCH, "Cerca per contenuto con \" \" (spazio)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "setup_optspasearch" )
    item6.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item4.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Alla ricezione del focus di tastiera, sui seguenti elementi di ricerca anagrafica imposta la priorità  sulla descrizione:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item13 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item14 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item15 = wx.StaticText( parent, ID_TEXT, "In Scheda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "In griglia", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item16, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Piano dei Conti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item17, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item18 = UnoZeroCheckBox( parent, ID_OPTLNKCRDPDC, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetName( "setup_optlnkcrdpdc" )
    item13.Add( item18, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item19 = UnoZeroCheckBox( parent, ID_OPTLNKGRDPDC, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetName( "setup_optlnkgrdpdc" )
    item13.Add( item19, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Clienti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21 = UnoZeroCheckBox( parent, ID_OPTLNKCRDCLI, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetName( "setup_optlnkcrdcli" )
    item13.Add( item21, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item22 = UnoZeroCheckBox( parent, ID_OPTLNKGRDCLI, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "setup_optlnkgrdcli" )
    item13.Add( item22, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item23 = wx.StaticText( parent, ID_TEXT, "Fornitori:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item23, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item24 = UnoZeroCheckBox( parent, ID_OPTLNKCRDFOR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.SetName( "setup_optlnkcrdfor" )
    item13.Add( item24, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item25 = UnoZeroCheckBox( parent, ID_OPTLNKGRDFOR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.SetName( "setup_optlnkgrdfor" )
    item13.Add( item25, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item13.AddGrowableCol( 1 )

    item13.AddGrowableCol( 2 )

    item4.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticBox( parent, -1, "Percorso backup azienda" )
    item26 = wx.StaticBoxSizer( item27, wx.VERTICAL )
    
    item28 = FolderEntryCtrl( parent, ID_BACKUPDIR, "", wx.DefaultPosition, [280,-1], 0 )
    item28.SetName( "setup_optbackupdir" )
    item26.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item30 = wx.StaticBox( parent, -1, "Google Account" )
    item29 = wx.StaticBoxSizer( item30, wx.VERTICAL )
    
    item31 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item32 = wx.StaticText( parent, ID_TEXT, "Username:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item32, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item33 = TextCtrl_LC( parent, ID_GCP_USER, "", wx.DefaultPosition, [80,-1], 0 )
    item33.SetName( "setup_opt_gcp_user" )
    item31.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item34 = wx.StaticText( parent, ID_TEXT, "Password:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item34, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item35 = TextCtrl_LC( parent, ID_GCP_PSWD, "", wx.DefaultPosition, [80,-1], wx.TE_PASSWORD )
    item35.SetName( "setup_opt_gcp_pswd" )
    item31.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item31.AddGrowableCol( 1 )

    item31.AddGrowableCol( 3 )

    item29.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item36 = UnoZeroCheckBox( parent, ID_GC_PRINT, "Abilita stampe su Google Cloud Print", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.SetName( "setup_opt_gc_print" )
    item29.Add( item36, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXTCTRL = 15100
ID_AZIENDA_LOGO = 15101

def DatiAziendaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Intestazione azienda" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Codice:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item3.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [100,-1], 0 )
    item5.SetName( "setup_azienda_codice" )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item1.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item7 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item8 = wx.StaticText( parent, ID_TEXT, "Ragione Sociale:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item7.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item9 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [360,-1], 0 )
    item9.SetName( "setup_azienda_ragsoc" )
    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "Indirizzo:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item11 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "setup_azienda_indirizzo" )
    item7.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "CAP, Città, Prov.:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item12, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item13 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item14 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item14.SetName( "setup_azienda_cap" )
    item13.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item15 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetName( "setup_azienda_citta" )
    item13.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item16 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item16.SetName( "setup_azienda_prov" )
    item13.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item13.AddGrowableCol( 1 )

    item7.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Cod.Fiscale:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item17, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item18 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item19 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item19.SetName( "setup_azienda_codfisc" )
    item18.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item18.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item21.SetName( "setup_azienda_stato" )
    item18.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item22 = wx.StaticText( parent, ID_TEXT, "P.IVA:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item18.Add( item22, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item23 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [90,-1], 0 )
    item23.SetName( "setup_azienda_piva" )
    item18.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item18.AddGrowableCol( 0 )

    item18.AddGrowableCol( 4 )

    item7.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Telefono:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item24, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item25 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item26 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.SetName( "setup_azienda_numtel" )
    item25.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticText( parent, ID_TEXT, "FAX:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item25.Add( item27, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item28 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item28.SetName( "setup_azienda_numfax" )
    item25.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item25.AddGrowableCol( 0 )

    item25.AddGrowableCol( 2 )

    item7.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item29 = wx.StaticText( parent, ID_TEXT, "email:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item29, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item30 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.SetName( "setup_azienda_email" )
    item7.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item31 = wx.StaticText( parent, ID_TEXT, "Titolare privacy:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item31, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item32 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetName( "setup_azienda_titprivacy" )
    item7.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item7.AddGrowableCol( 1 )

    item1.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item33 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item34 = wx.StaticText( parent, ID_TEXT, "Logo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item35 = wx.StaticText( parent, ID_TEXT, "Descrizione attività:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item36 = PhotoContainerPanel( parent, ID_AZIENDA_LOGO, wx.DefaultPosition, [128,128], wx.SUNKEN_BORDER )
    item36.SetName( "azienda_logo" )
    item33.Add( item36, 0, wx.LEFT|wx.BOTTOM, 5 )

    item37 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,40], wx.TE_MULTILINE )
    item37.SetName( "setup_azienda_infatti" )
    item33.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item33.AddGrowableCol( 1 )

    item33.AddGrowableRow( 1 )

    item0.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_FTEL_ACQPDC = 15102
ID_FTEL_VENPDF = 15103
ID_FTEL_SOLITA = 15104
ID_FTEL_DACOCO = 15105
ID_FTEL_INFDEST = 15106
ID_FTEL_EEB_URL = 15107
ID_FTEL_EEB_USER = 15108
ID_FTEL_EEB_PSWD = 15109
ID_FTEL_VENART = 15110
ID_FTEL_TIPCOD = 15111
ID_FTEL_TIPDAT = 15112
ID_FTEL_ROWCAU = 15113
ID_REGFISC = 15114
ID_TIPORIT = 15115
ID_PAGRITACC = 15116
ID_CASSAPREV = 15117

def FTEL_Setup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item4 = wx.StaticBox( parent, -1, "Acquisti" )
    item3 = wx.StaticBoxSizer( item4, wx.VERTICAL )
    
    item5 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item6 = wx.StaticText( parent, ID_TEXT, "Costo generico per acquisizione fatture fornitori", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item7 = alib.LinkTablePdc(parent, ID_FTEL_ACQPDC, 'setup_ftel_acqpdc')
    item5.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item5.AddGrowableCol( 0 )

    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item9 = wx.StaticBox( parent, -1, "Vendite" )
    item8 = wx.StaticBoxSizer( item9, wx.VERTICAL )
    
    item10 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item11 = UnoZeroCheckBox( parent, ID_FTEL_VENPDF, "Allega copia PDF", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "setup_ftel_venpdf" )
    item10.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item12 = UnoZeroCheckBox( parent, ID_FTEL_SOLITA, "Escludi clienti esteri", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.SetName( "setup_ftel_solita" )
    item10.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item13 = UnoZeroCheckBox( parent, ID_FTEL_DACOCO, "Gestione dati contratto/conv.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.SetName( "setup_ftel_dacoco" )
    item10.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item14 = UnoZeroCheckBox( parent, ID_FTEL_INFDEST, "Dati extra su destinazioni", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.SetName( "setup_ftel_infdest" )
    item10.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item8.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item2.AddGrowableCol( 0 )

    item2.AddGrowableRow( 1 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item17 = wx.StaticBox( parent, -1, "ebill.evolvia.srl" )
    item16 = wx.StaticBoxSizer( item17, wx.VERTICAL )
    
    item18 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item19 = wx.StaticText( parent, ID_TEXT, "Webservice URL:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Username:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item21 = wx.StaticText( parent, ID_TEXT, "Password:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item22 = TextCtrl_LC( parent, ID_FTEL_EEB_URL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "setup_ftel_eeb_url" )
    item18.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item23 = TextCtrl_LC( parent, ID_FTEL_EEB_USER, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item23.SetName( "setup_ftel_eeb_user" )
    item18.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item24 = TextCtrl_LC( parent, ID_FTEL_EEB_PSWD, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.SetName( "setup_ftel_eeb_pswd" )
    item18.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item18.AddGrowableCol( 0 )

    item18.AddGrowableCol( 1 )

    item18.AddGrowableCol( 2 )

    item16.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item25 = UnoZeroCheckBox( parent, ID_FTEL_VENART, "Includi codici prodotto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.SetName( "setup_ftel_vencod" )
    item15.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item26 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item27 = FtElTipoCodiceRadioBox( parent, ID_FTEL_TIPCOD, "Identifica i prodotti usando il codice:", wx.DefaultPosition, wx.DefaultSize, 
        ["Cod. prod.","Cod. fornit.","Barcode"] , 1, wx.RA_SPECIFY_ROWS )
    item27.SetName( "setup_ftel_tipcod" )
    item26.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item29 = wx.StaticBox( parent, -1, "Tipo dato" )
    item28 = wx.StaticBoxSizer( item29, wx.VERTICAL )
    
    item30 = TextCtrl_LC( parent, ID_FTEL_TIPDAT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.SetName( "setup_ftel_tipdat" )
    item28.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item26.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item26.AddGrowableCol( 1 )

    item26.AddGrowableRow( 0 )

    item15.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15.AddGrowableCol( 0 )

    item15.AddGrowableRow( 2 )

    item1.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item32 = wx.StaticBox( parent, -1, "Righe causale" )
    item31 = wx.StaticBoxSizer( item32, wx.VERTICAL )
    
    item33 = wx.TextCtrl( parent, ID_FTEL_ROWCAU, "", wx.DefaultPosition, [200,110], wx.TE_MULTILINE )
    item33.SetName( "setup_ftel_rowcau" )
    item31.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item1.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableCol( 2 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item34 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item35 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item37 = wx.StaticBox( parent, -1, "Dati per la Fattura Elettronica" )
    item36 = wx.StaticBoxSizer( item37, wx.VERTICAL )
    
    item38 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item39 = wx.StaticText( parent, ID_TEXT, "Nome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item39, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item40 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item41 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.SetName( "setup_azienda_ftel_nome" )
    item40.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item42 = wx.StaticText( parent, ID_TEXT, "Cognome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.Add( item42, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item43 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item43.SetName( "setup_azienda_ftel_cognome" )
    item40.Add( item43, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item40.AddGrowableCol( 0 )

    item40.AddGrowableCol( 2 )

    item38.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item44 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item44, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item45 = wx.StaticText( parent, ID_TEXT, "Stabile organizzazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item45, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item46 = wx.StaticText( parent, ID_TEXT, "Indirizzo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item46, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item47 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [200,-1], 0 )
    item47.SetName( "setup_azienda_ftel_soind" )
    item38.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item48 = wx.StaticText( parent, ID_TEXT, "CAP, Città, Prov.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item48, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item49 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item50 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item50.SetName( "setup_azienda_ftel_socap" )
    item49.Add( item50, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item51 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item51.SetName( "setup_azienda_ftel_socit" )
    item49.Add( item51, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item52 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item52.SetName( "setup_azienda_ftel_sopro" )
    item49.Add( item52, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item49.AddGrowableCol( 1 )

    item38.Add( item49, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item53 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item53, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item54 = wx.StaticText( parent, ID_TEXT, "Dati azienda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item54, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item55 = wx.StaticText( parent, ID_TEXT, "Regime fiscale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item55, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item56 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item57 = RegimeFiscaleChoice( parent, ID_REGFISC, wx.DefaultPosition, [100,-1], 
        ["RF01 - Ordinario","RF02 - Contribuenti minimi (art. 1, c.96-117, L. 244/2007)","RF03 - Nuove iniziative produttive (art.13, L. 388/2000)","RF04 - Agricoltura e attività connesse e pesca (artt. 34 e 34-bis, D.P.R. 633/1972)","RF05 - Vendita sali e tabacchi (art. 74, c.1, D.P.R. 633/1972)","RF06 - Commercio dei fiammiferi (art. 74, c.1, D.P.R.633/1972)","RF07 - Editoria (art. 74, c.1, D.P.R. 633/1972)","RF08 - Gestione di servizi di telefonia pubblica (art. 74, c.1,D.P.R. 633/1972)","RF09 - Rivendita di documenti di trasporto pubblico e di sosta (art. 74, c.1, D.P.R. 633/1972)","RF10 - Intrattenimenti, giochi e altre attività di cui alla tariffa allegata al D.P.R. n. 640/72 (art. 74, c.6, D.P.R.633/1972)","RF11 - Agenzie di viaggi e turismo (art. 74-ter, D.P.R. ","RF12 - Agriturismo (art. 5, c.2, L. 413/1991)","RF13 - Vendite a domicilio (art. 25-bis, c.6, D.P.R. 600/1973)","RF14 - Rivendita di beni usati, di oggetti d’arte, d’antiquariato o ","RF15 - Agenzie di vendite all’asta di oggetti d’arte, antiquariato ","RF16 - IVA per cassa P.A. (art. 6, c.5, D.P.R. 633/1972)","RF17 - IVA per cassa soggetti con volume d’affari inferiore a Eur 200.000 (art. 7, D.L. 185/2008)","RF19 - Regime forfettario (art.1, c.54-89, L. 190/2014)","RF18 - Altro","RF19 - Regime forfettario"] , 0 )
    item57.SetName( "setup_azienda_ftel_regfisc" )
    item56.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item56.AddGrowableCol( 0 )

    item38.Add( item56, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item58 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item58, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item59 = wx.StaticText( parent, ID_TEXT, "Dati REA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item59, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item60 = wx.StaticText( parent, ID_TEXT, "Num.Iscriz:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item60, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item61 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item62 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item62.SetName( "setup_azienda_ftel_reanum" )
    item61.Add( item62, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item63 = wx.StaticText( parent, ID_TEXT, "Ufficio:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.Add( item63, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item64 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item64.SetName( "setup_azienda_ftel_reauff" )
    item61.Add( item64, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item38.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item65 = wx.StaticText( parent, ID_TEXT, "Capitale sociale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item65, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item66 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item67 = NumCtrl(parent, integerWidth=6, fractionWidth=2, allowNegative=False); item67.SetName('setup_azienda_ftel_capsoc')
    item66.Add( item67, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item68 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Socio unico", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.SetName( "setup_azienda_ftel_socuni" )
    item66.Add( item68, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item69 = UnoZeroCheckBox( parent, ID_CHECKBOX, "In liquidazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item69.SetName( "setup_azienda_ftel_socliq" )
    item66.Add( item69, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item38.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item38.AddGrowableCol( 1 )

    item36.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item35.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item71 = wx.StaticBox( parent, -1, "Soggetto trasmittente se diverso da cedente/prestatore" )
    item70 = wx.StaticBoxSizer( item71, wx.VERTICAL )
    
    item72 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item73 = wx.StaticText( parent, ID_TEXT, "C.F./P.I.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item72.Add( item73, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item74 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item74.SetName( "setup_azienda_ftel_trcodfis" )
    item72.Add( item74, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item75 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item72.Add( item75, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item76 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item76.SetName( "setup_azienda_ftel_trstato" )
    item72.Add( item76, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item70.Add( item72, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item35.Add( item70, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item78 = wx.StaticBox( parent, -1, "Ritenuta d'acconto" )
    item77 = wx.StaticBoxSizer( item78, wx.VERTICAL )
    
    item79 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item80 = wx.StaticText( parent, ID_TEXT, "Tipo di ritenuta:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item79.Add( item80, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item81 = TipoRitenutaChoice( parent, ID_TIPORIT, wx.DefaultPosition, [100,-1], 
        ["RT01 - Ritenuta persone fisiche","RT02 - Ritenuta persone giuridiche","RT03 - Contributo INPS","RT04 - Contributo ENASARCO","RT05 - Contributo UNPAM","RT06 - Altro contributo previdenziale"] , 0 )
    item81.SetName( "setup_azienda_ftel_ritacctipo" )
    item79.Add( item81, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item82 = wx.StaticText( parent, ID_TEXT, "Codice Tipo pagamento ritenuta (A):", wx.DefaultPosition, wx.DefaultSize, 0 )
    item79.Add( item82, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item83 = TextCtrl( parent, ID_PAGRITACC, "", wx.DefaultPosition, [80,-1], 0 )
    item83.SetName( "setup_azienda_ftel_ritaccpag" )
    item79.Add( item83, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item79.AddGrowableCol( 1 )

    item77.Add( item79, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item35.Add( item77, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item85 = wx.StaticBox( parent, -1, "Cassa previdenziale" )
    item84 = wx.StaticBoxSizer( item85, wx.VERTICAL )
    
    item86 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item87 = wx.StaticText( parent, ID_TEXT, "Tipo cassa:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item86.Add( item87, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item88 = TipoCassaPrevidenzaChoice( parent, ID_CASSAPREV, wx.DefaultPosition, [100,-1], 
        ["TC01 - Cassa nazionale previdenza avvocati e procuratori legali","TC02 - Cassa previdenza dottori commercialisti","TC03 - Cassa previdenza e assistenza geometri","TC04 - Cassa nazionale ingegneri e architetti liberi professionisti","TC05 - Cassa nazionale del notariato","TC06 - Cassa nazionale ragionieri e periti commerciali","TC07 - ENASARCO","TC08 - ENPACL","TC09 - ENPAM","TC10 - ENPAF","TC11 - ENPAV","TC12 - ENPAIA","TC13 - Fondo prev. impiegati imprese spediz. e ag. marittime","TC14 - INPGI","TC15 - ONAOSI","TC16 - CASAGIT","TC17 - EPPI","TC18 - EPAP","TC19 - ENPAB","TC20 - ENPAPI","TC21 - ENPAP","TC22 - INPS"] , 0 )
    item88.SetName( "setup_azienda_ftel_cassaprev" )
    item86.Add( item88, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item86.AddGrowableCol( 1 )

    item84.Add( item86, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item35.Add( item84, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item35.AddGrowableCol( 0 )

    item35.AddGrowableRow( 2 )

    item34.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item89 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item91 = wx.StaticBox( parent, -1, "Rappresentante fiscale" )
    item90 = wx.StaticBoxSizer( item91, wx.VERTICAL )
    
    item92 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item93 = wx.StaticText( parent, ID_TEXT, "Nome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.Add( item93, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item94 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item95 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item95.SetName( "setup_azienda_ftel_rfnome" )
    item94.Add( item95, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item96 = wx.StaticText( parent, ID_TEXT, "Cognome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item94.Add( item96, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item97 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item97.SetName( "setup_azienda_ftel_rfcognome" )
    item94.Add( item97, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item94.AddGrowableCol( 0 )

    item94.AddGrowableCol( 2 )

    item92.Add( item94, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item98 = wx.StaticText( parent, ID_TEXT, "Ragione sociale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.Add( item98, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item99 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [200,-1], 0 )
    item99.SetName( "setup_azienda_ftel_rfdes" )
    item92.Add( item99, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item100 = wx.StaticText( parent, ID_TEXT, "Indirizzo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.Add( item100, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item101 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item101.SetName( "setup_azienda_ftel_rfind" )
    item92.Add( item101, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item102 = wx.StaticText( parent, ID_TEXT, "CAP, Città, Prov.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.Add( item102, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item103 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item104 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item104.SetName( "setup_azienda_ftel_rfcap" )
    item103.Add( item104, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item105 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item105.SetName( "setup_azienda_ftel_rfcit" )
    item103.Add( item105, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item106 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item106.SetName( "setup_azienda_ftel_rfpro" )
    item103.Add( item106, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item103.AddGrowableCol( 1 )

    item92.Add( item103, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item107 = wx.StaticText( parent, ID_TEXT, "Cod.Fiscale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.Add( item107, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item108 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item109 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item109.SetName( "setup_azienda_ftel_rfcodfis" )
    item108.Add( item109, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item110 = wx.StaticText( parent, ID_TEXT, "P.IVA:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item108.Add( item110, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item111 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [90,-1], 0 )
    item111.SetName( "setup_azienda_ftel_rfpiva" )
    item108.Add( item111, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item112 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item108.Add( item112, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item113 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item113.SetName( "setup_azienda_ftel_rfstato" )
    item108.Add( item113, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item108.AddGrowableCol( 1 )

    item92.Add( item108, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item92.AddGrowableCol( 1 )

    item90.Add( item92, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item89.Add( item90, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item115 = wx.StaticBox( parent, -1, "Terzo intermediario o soggetto emittente" )
    item114 = wx.StaticBoxSizer( item115, wx.VERTICAL )
    
    item116 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item117 = wx.StaticText( parent, ID_TEXT, "Cod.Fiscale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item116.Add( item117, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item118 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item119 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item119.SetName( "setup_azienda_ftel_secodfis" )
    item118.Add( item119, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item120 = wx.StaticText( parent, ID_TEXT, "P.IVA:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item118.Add( item120, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item121 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [90,-1], 0 )
    item121.SetName( "setup_azienda_ftel_sepiva" )
    item118.Add( item121, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item122 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item118.Add( item122, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item123 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item123.SetName( "setup_azienda_ftel_sestato" )
    item118.Add( item123, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item118.AddGrowableCol( 1 )

    item116.Add( item118, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item124 = wx.StaticText( parent, ID_TEXT, "Ragione sociale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item116.Add( item124, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item125 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item125.SetName( "setup_azienda_ftel_sedes" )
    item116.Add( item125, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item126 = wx.StaticText( parent, ID_TEXT, "Nome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item116.Add( item126, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item127 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item128 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item128.SetName( "setup_azienda_ftel_senome" )
    item127.Add( item128, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item129 = wx.StaticText( parent, ID_TEXT, "Cognome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item127.Add( item129, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item130 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item130.SetName( "setup_azienda_ftel_secognome" )
    item127.Add( item130, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item127.AddGrowableCol( 0 )

    item127.AddGrowableCol( 2 )

    item116.Add( item127, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item131 = wx.StaticText( parent, ID_TEXT, "Titolo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item116.Add( item131, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item132 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item133 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item133.SetName( "setup_azienda_ftel_setit" )
    item132.Add( item133, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item134 = wx.StaticText( parent, ID_TEXT, "Cod. EORI:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item132.Add( item134, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item135 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [100,-1], 0 )
    item135.SetName( "setup_azienda_ftel_seeori" )
    item132.Add( item135, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item132.AddGrowableCol( 0 )

    item116.Add( item132, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item116.AddGrowableCol( 1 )

    item114.Add( item116, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item89.Add( item114, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item136 = SoggettoEmittenteRadioBox( parent, ID_RADIOBOX, "Soggetto emittente", wx.DefaultPosition, wx.DefaultSize, 
        ["XX - Non specificato","CC - Cessionario/Committ.","TZ - SoggettoTerzo"] , 1, wx.RA_SPECIFY_ROWS )
    item136.SetName( "setup_azienda_ftel_sesogemi" )
    item89.Add( item136, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item89.AddGrowableCol( 0 )

    item89.AddGrowableRow( 1 )

    item34.Add( item89, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item34.AddGrowableCol( 0 )

    item34.AddGrowableCol( 1 )

    item0.Add( item34, 0, wx.GROW, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableCol( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
