# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: azisetup.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.datectrl import DateCtrl
from awc.controls.numctrl import NumCtrl
from awc.controls.radiobox import RadioBox
from awc.controls.checkbox import CheckBox
from awc.controls.linktable import LinkTable

from awc.controls.entries import FolderEntryCtrl

from anag.basetab import WorkZoneNotebook, PhotoContainerPanel

from anag.mag import MagazzDialog

import Env
bt = Env.Azienda.BaseTab

import anag.lib as alib

class ScorpIvaRadioBox(RadioBox):
    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=' 1')

class UnoZeroCheckBox(CheckBox):
    def __init__(self, *args, **kwargs):
        CheckBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values={True: 1, False: 0})
    
    def SetValue(self, v):
        if isinstance(v, (str, unicode)):
            v = int(v)
        CheckBox.SetValue(self, v)


class SovrapposizioneRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=(0,1))

class RitAccCheckBox(UnoZeroCheckBox):

    def __init__(self, *args, **kwargs):
        UnoZeroCheckBox.__init__(self, *args, **kwargs)
        self.Bind(wx.EVT_CHECKBOX, self.OnRitAccChanged)

    def OnRitAccChanged(self, event):
        for name in 'per com'.split():
            self.GetParent().FindWindowByName('setup_con%sritacc'%name).Enable(self.IsChecked())
        event.Skip()

class MagProvMovRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=(" ", "E"))


class OrdPartiteRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=["S",  "D"])



from awc.controls.choice import ChoiceData

class RegimeFiscaleChoice(ChoiceData):
    
    def __init__(self, *args, **kwargs):
        ChoiceData.__init__(self, *args, **kwargs)
        self.SetDataLink(values=[n for n in range(1,19,1)])



class SoggettoEmittenteRadioBox(RadioBox):

    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=[" ", "C", "T"])


class TipoRitenutaChoice(ChoiceData):
    
    def __init__(self, *args, **kwargs):
        ChoiceData.__init__(self, *args, **kwargs)
        self.SetDataLink(values=["1", "2"])
    
    def SetValue(self, value):
        if value:
            value = str(int(value))
            ChoiceData.SetValue(self, value)


class TipoCassaPrevidenzaChoice(ChoiceData):
    
    def __init__(self, *args, **kwargs):
        ChoiceData.__init__(self, *args, **kwargs)
        self.SetDataLink(values=[n for n in range(1,23,1)])




# Window functions

ID_NOTEBOOK = 15000
ID_BTNOK = 15001

def AziendaSetup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = WorkZoneNotebook( parent, ID_NOTEBOOK, wx.DefaultPosition, wx.DefaultSize, 0 )
    item1 = item2
    
    item3 = wx.Panel( item2, -1 )
    DatiAziendaFunc(item3, False)
    item2.AddPage( item3, "Dati azienda" )

    item4 = wx.Panel( item2, -1 ); item4.SetName('contabpanel')
    ContabSetup(item4, False)
    item2.AddPage( item4, "Contabilità" )

    item5 = wx.Panel( item2, -1 ); item5.SetName('magazzpanel')
    MagazzSetup(item5, False)
    item2.AddPage( item5, "Magazzino" )

    item6 = wx.Panel( item2, -1 ); item6.SetName('opzionipanel')
    OpzioniFunc(item6, False)
    item2.AddPage( item6, "Opzioni" )

    item7 = wx.Panel( item2, -1 )
    FTEL_Setup(item7, False)
    item2.AddPage( item7, "Fattura Elettronica" )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item8 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item9 = wx.Button( parent, ID_BTNOK, "OK", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetDefault()
    item9.SetName( "btnok" )
    item8.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 15002
ID_ESERCIZIOGG = 15003
ID_ESERCIZIOMM = 15004
ID_ESERCIZIOERR = 15005
ID_CODATECO = 15006
ID_CONSOVGES = 15007
ID_RADIOBOX = 15008
ID_CONTABVAL = 15009
ID_CONTABDECIMP = 15010
ID_CHECKBOX = 15011
ID_CONBILRICL = 15012
ID_CONBILRCEE = 15013
ID_CONATTRITACC = 15014
ID_CONPERRITACC = 15015
ID_CONCOMRITACC = 15016
ID_SCADORD = 15017
ID_GESSOLPAG = 15018
ID_DOCSOLPAG = 15019
ID_GGSSOLPAG = 15020
ID_EFFCONSCA = 15021

def ContabSetup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item3 = wx.StaticBox( parent, -1, "Esercizio contabile" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )
    
    item4 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item5 = wx.StaticText( parent, ID_TEXT, "Giorno e mese di inizio dell'esercizio contabile:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item6 = NumCtrl( parent, integerWidth=2, allowNegative=False); item6.SetName('setup_esercizio_startgg')
    item4.Add( item6, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "/", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item7, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item8 = NumCtrl( parent, integerWidth=2, allowNegative=False); item8.SetName('setup_esercizio_startmm')
    item4.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item9 = wx.StaticText( parent, ID_ESERCIZIOERR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetForegroundColour( wx.RED )
    item9.SetName( "esercizio_err" )
    item4.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item4.AddGrowableCol( 4 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.StaticBox( parent, -1, "Spesometro" )
    item10 = wx.StaticBoxSizer( item11, wx.VERTICAL )
    
    item12 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item13 = wx.StaticText( parent, ID_TEXT, "Cod.Attività Ateco2007:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item12.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item14 = TextCtrl( parent, ID_CODATECO, "", wx.DefaultPosition, [80,-1], 0 )
    item14.SetName( "setup_azienda_codateco" )
    item12.Add( item14, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item10.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item16 = SovrapposizioneRadioBox( parent, ID_CONSOVGES, "Chiusure contabili", wx.DefaultPosition, wx.DefaultSize, 
        ["Senza sovrapposizione d'esercizio","Con sovrapposizione d'esercizio"] , 1, wx.RA_SPECIFY_COLS )
    item16.SetName( "setup_consovges" )
    item15.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item17 = RadioBox( parent, ID_RADIOBOX, "Tipo di gestione dell'IVA", wx.DefaultPosition, wx.DefaultSize, 
        ["Ordinaria","Semplificata"] , 1, wx.RA_SPECIFY_COLS )
    item17.SetName( "setup_tipo_contab" )
    item15.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item18 = RadioBox( parent, ID_RADIOBOX, "Periodicità di liquidazione IVA", wx.DefaultPosition, wx.DefaultSize, 
        ["Mensile","Trimestrale"] , 1, wx.RA_SPECIFY_COLS )
    item18.SetName( "setup_liqiva_periodic" )
    item15.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item15.AddGrowableCol( 0 )

    item15.AddGrowableCol( 1 )

    item0.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item20 = wx.StaticBox( parent, -1, "Impostazione valuta di conto" )
    item19 = wx.StaticBoxSizer( item20, wx.VERTICAL )
    
    item21 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item22 = wx.StaticText( parent, ID_TEXT, "Valuta di conto:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item22, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item23 = LinkTable(parent, ID_CONTABVAL ); item23.SetDataLink( bt.TABNAME_VALUTE, "setup_contab_valcon", None); item23.SetObligatory(True)
    item21.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Numero di decimali su importi:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item24, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item25 = NumCtrl( parent, integerWidth=2, allowNegative=False); item25.SetName('setup_contab_decimp')
    item21.Add( item25, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item21.AddGrowableCol( 1 )

    item19.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticBox( parent, -1, "Gestione fidi clienti" )
    item26 = wx.StaticBoxSizer( item27, wx.VERTICAL )
    
    item28 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Attiva la gestione dei fidi sui clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item28.SetName( "setup_gesfidicli" )
    item26.Add( item28, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item30 = wx.StaticBox( parent, -1, "Bilanci" )
    item29 = wx.StaticBoxSizer( item30, wx.HORIZONTAL )
    
    item31 = UnoZeroCheckBox( parent, ID_CONBILRICL, "Attiva riclassificazioni di bilancio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.SetName( "setup_conbilricl" )
    item29.Add( item31, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item32 = UnoZeroCheckBox( parent, ID_CONBILRCEE, "Attiva riclassificazioni CEE", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetName( "setup_conbilrcee" )
    item29.Add( item32, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item34 = wx.StaticBox( parent, -1, "Ritenute d'Acconto" )
    item33 = wx.StaticBoxSizer( item34, wx.HORIZONTAL )
    
    item35 = RitAccCheckBox( parent, ID_CONATTRITACC, "Attiva gestione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item35.SetName( "setup_conattritacc" )
    item33.Add( item35, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item36 = wx.StaticText( parent, ID_TEXT, "Calcolo %:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item36, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item37 = NumCtrl( parent, integerWidth=2, fractionWidth=2, allowNegative=False); item37.SetName('setup_conperritacc')
    item33.Add( item37, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item38 = wx.StaticText( parent, ID_TEXT, "da applicare all'imponibile in % del:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item38, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item39 = NumCtrl( parent, integerWidth=3, fractionWidth=2, allowNegative=False); item39.SetName('setup_concomritacc')
    item33.Add( item39, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item40 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item41 = OrdPartiteRadioBox( parent, ID_SCADORD, "Ordinameno scadenzari clienti/fornitori", wx.DefaultPosition, wx.DefaultSize, 
        ["Data scadenza","Data documento"] , 1, wx.RA_SPECIFY_ROWS )
    item41.SetName( "setup_scadord" )
    item40.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item43 = wx.StaticBox( parent, -1, "Solleciti pagamento" )
    item42 = wx.StaticBoxSizer( item43, wx.VERTICAL )
    
    item44 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item45 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item46 = UnoZeroCheckBox( parent, ID_GESSOLPAG, "Attiva gestione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item46.SetName( "setup_gessolpag" )
    item45.Add( item46, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item47 = UnoZeroCheckBox( parent, ID_DOCSOLPAG, "Allega documenti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item47.SetName( "setup_docsolpag" )
    item45.Add( item47, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item44.Add( item45, 0, wx.ALIGN_CENTER, 5 )

    item48 = wx.StaticText( parent, ID_TEXT, "GG scad:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item44.Add( item48, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item49 = NumCtrl( parent, integerWidth=3, fractionWidth=0, allowNegative=False); item49.SetName('setup_ggssolpag')
    item44.Add( item49, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item42.Add( item44, 0, wx.ALIGN_CENTER, 5 )

    item40.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item51 = wx.StaticBox( parent, -1, "Contabilizzazione effetti" )
    item50 = wx.StaticBoxSizer( item51, wx.VERTICAL )
    
    item52 = UnoZeroCheckBox( parent, ID_EFFCONSCA, "Usa la data di scadenza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item52.SetName( "setup_effconsca" )
    item50.Add( item52, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item40.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item40.AddGrowableCol( 2 )

    item0.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_MAGDEFAULT = 15022
ID_magdec_qta = 15023
ID_magdec_prez = 15024
ID_magricpre = 15025
ID_MAGPZCONF = 15026
ID_MAGPZGRIP = 15027
ID_MAGSCORPCOS = 15028
ID_MAGSCORPPRE = 15029
ID_FOREIGN = 15030
ID_MAGSCOCAT = 15031
ID_MAGGESACC = 15032
ID_MAGEANPREFIX = 15033
ID_MAGDATCHI = 15034
ID_MAGNUMLIS = 15035
ID_MAGDATLIS = 15036
ID_MAGBCOLIS = 15037
ID_MAGFORLIS = 15038
ID_MAGROWLIS = 15039
ID_MAGVLIFOR = 15040
ID_MAGVLIMAR = 15041
ID_MAGVLICAT = 15042
ID_MAGVLIGRU = 15043
ID_MAGRICLIS = 15044
ID_MAGSCOLIS = 15045
ID_MAGPPROMO = 15046
ID_MAGVRGLIS = 15047
ID_MAGVSGLIS = 15048
ID_MAGREPLIS = 15049
ID_MAGRELLIS = 15050
ID_MAGSEPLIS = 15051
ID_MAGSELLIS = 15052
ID_MAGERPLIS = 15053
ID_MAGESPLIS = 15054
ID_MAGATTGRIP = 15055
ID_MAGCDEGRIP = 15056
ID_LINE = 15057
ID_MAGATTGRIF = 15058
ID_MAGCDEGRIF = 15059
ID_MAGAGGGRIP = 15060
ID_MAGALWGRIP = 15061
ID_MAGDATGRIP = 15062
ID_MAGNOCODEVET = 15063
ID_MAGNOCDEFVET = 15064
ID_MAGEXTRAVET = 15065
ID_MAGNOCODEDES = 15066
ID_MAGNOCDEFDES = 15067
ID_MAGIMGPROD = 15068
ID_MAGDIGSEARCH = 15069
ID_MAGRETSEARCH = 15070
ID_MAGEXCSEARCH = 15071
ID_MAGVISGIA = 15072
ID_MAGVISDIS = 15073
ID_MAGVISCOS = 15074
ID_MAGVISPRE = 15075
ID_MAGVISCPF = 15076
ID_MAGVISBCD = 15077
ID_MAGPROVATT = 15078
ID_MAGPROVCLI = 15079
ID_MAGPROVPRO = 15080
ID_MAGPROVMOV = 15081
ID_MAGPROVSEQ = 15082

def MagazzSetup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Magazzino di default per operazioni di carico/scarico e immissione documenti" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Magazzino:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item5 = LinkTable(parent, ID_MAGDEFAULT ); item5.SetDataLink( bt.TABNAME_MAGAZZ, "setup_magazz_default:site %s" % Env.Azienda.config.Site_name, MagazzDialog); item5.SetObligatory(True)
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3.AddGrowableCol( 1 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item8 = wx.StaticBox( parent, -1, "Numero di decimali da gestire" )
    item7 = wx.StaticBoxSizer( item8, wx.VERTICAL )
    
    item9 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item10 = wx.StaticText( parent, ID_TEXT, "Quantità:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item11 = NumCtrl( parent, integerWidth=2, allowNegative=False); item11.SetName('setup_magdec_qta')
    item9.Add( item11, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Prezzi unitari:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item12, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item13 = NumCtrl( parent, integerWidth=2, allowNegative=False); item13.SetName('setup_magdec_prez')
    item9.Add( item13, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item15 = wx.StaticBox( parent, -1, "Prezzi" )
    item14 = wx.StaticBoxSizer( item15, wx.VERTICAL )
    
    item16 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item17 = wx.StaticText( parent, ID_TEXT, "Ricarica predefinita:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.Add( item17, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item18 = NumCtrl( parent, ID_magricpre, integerWidth=3, allowNegative=False); item18.SetName('setup_magricpre')
    item16.Add( item18, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item20 = wx.StaticBox( parent, -1, "Confezioni" )
    item19 = wx.StaticBoxSizer( item20, wx.VERTICAL )
    
    item21 = UnoZeroCheckBox( parent, ID_MAGPZCONF, "Gestisci", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetName( "setup_magpzconf" )
    item19.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item22 = UnoZeroCheckBox( parent, ID_MAGPZGRIP, "Su griglie", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "setup_magpzgrip" )
    item19.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item6.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item6.AddGrowableCol( 0 )

    item6.AddGrowableCol( 1 )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item23 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item24 = ScorpIvaRadioBox( parent, ID_MAGSCORPCOS, "I costi su scheda prodotto sono:", wx.DefaultPosition, wx.DefaultSize, 
        ["Imponibili: l'IVA sarà aggiunta","Ivati: l'IVA sarà scorporata"] , 1, wx.RA_SPECIFY_COLS )
    item24.SetName( "setup_magscorpcos" )
    item23.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item25 = ScorpIvaRadioBox( parent, ID_MAGSCORPPRE, "I prezzi su scheda prodotto sono:", wx.DefaultPosition, wx.DefaultSize, 
        ["Imponibili: l'IVA sarà aggiunta","Ivati: l'IVA sarà scorporata"] , 1, wx.RA_SPECIFY_COLS )
    item25.SetName( "setup_magscorppre" )
    item23.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item23.AddGrowableCol( 0 )

    item23.AddGrowableCol( 1 )

    item0.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item28 = wx.StaticBox( parent, -1, "Gestisci" )
    item27 = wx.StaticBoxSizer( item28, wx.VERTICAL )
    
    item29 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item30 = wx.StaticText( parent, ID_TEXT, "Ricariche:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.Add( item30, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item31 = NumCtrl(parent, ID_FOREIGN, integerWidth=1, allowNegative=False); item31.SetName('setup_magnumric'); item31.SetToolTipString("Indicare il numero delle ricariche da gestire (0-6)")
    item29.Add( item31, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item32 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.Add( item32, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item33 = NumCtrl(parent, ID_FOREIGN, integerWidth=1, allowNegative=False); item33.SetName('setup_magnumsco'); item33.SetToolTipString("Indicare il numero degli sconti da gestire (0-6)")
    item29.Add( item33, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item27.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item35 = wx.StaticBox( parent, -1, "" )
    item34 = wx.StaticBoxSizer( item35, wx.VERTICAL )
    
    item36 = UnoZeroCheckBox( parent, ID_MAGSCOCAT, "Attiva sconti per categoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.SetName( "setup_magscocat" )
    item34.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item37 = UnoZeroCheckBox( parent, ID_MAGGESACC, "Attiva gestione acconti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.SetName( "setup_maggesacc" )
    item34.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item26.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item39 = wx.StaticBox( parent, -1, "Codifica barcodes" )
    item38 = wx.StaticBoxSizer( item39, wx.HORIZONTAL )
    
    item40 = wx.StaticText( parent, ID_TEXT, "EAN13 C.C.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.Add( item40, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item41 = wx.TextCtrl( parent, ID_MAGEANPREFIX, "", wx.DefaultPosition, [30,-1], 0 )
    item41.SetName( "setup_mageanprefix" )
    item38.Add( item41, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item43 = wx.StaticBox( parent, -1, "Chiusura" )
    item42 = wx.StaticBoxSizer( item43, wx.HORIZONTAL )
    
    item44 = wx.StaticText( parent, ID_TEXT, "Data ultima chiusura magazzino:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.Add( item44, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item45 = DateCtrl( parent, ID_MAGDATCHI, "", wx.DefaultPosition, [80,-1], 0 )
    item45.SetName( "setup_magdatchi" )
    item42.Add( item45, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item26.AddGrowableCol( 0 )

    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item48 = wx.StaticBox( parent, -1, "Gestione Listini di vendita" )
    item47 = wx.StaticBoxSizer( item48, wx.VERTICAL )
    
    item49 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item50 = wx.StaticText( parent, ID_TEXT, "Num.Listini:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item49.Add( item50, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item51 = NumCtrl(parent, ID_MAGNUMLIS, integerWidth=1, allowNegative=False); item51.SetName('setup_magnumlis'); item51.SetToolTipString("Indicare il numero dei listini da gestire (0-9)")
    item49.Add( item51, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item52 = UnoZeroCheckBox( parent, ID_MAGDATLIS, "Per data", wx.DefaultPosition, wx.DefaultSize, 0 )
    item52.SetToolTip( wx.ToolTip("Attiva la gestione dei listini per data") )
    item52.SetName( "setup_magdatlis" )
    item49.Add( item52, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item47.Add( item49, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item53 = wx.BoxSizer( wx.HORIZONTAL )
    
    item54 = UnoZeroCheckBox( parent, ID_MAGBCOLIS, "Barcode", wx.DefaultPosition, wx.DefaultSize, 0 )
    item54.SetToolTip( wx.ToolTip("Attiva la gestione dei listini per data") )
    item54.SetName( "setup_magbcolis" )
    item53.Add( item54, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item55 = UnoZeroCheckBox( parent, ID_MAGFORLIS, "Cod.Forn.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.SetToolTip( wx.ToolTip("Attiva la codifica prodotto del fornitore sul listino") )
    item55.SetName( "setup_magforlis" )
    item53.Add( item55, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item56 = UnoZeroCheckBox( parent, ID_MAGROWLIS, "Su riga", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.SetToolTip( wx.ToolTip("Attiva la selezione del listino su ogni riga del documento") )
    item56.SetName( "setup_magrowlis" )
    item53.Add( item56, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item47.Add( item53, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item46.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item58 = wx.StaticBox( parent, -1, "Listini variabili per:" )
    item57 = wx.StaticBoxSizer( item58, wx.VERTICAL )
    
    item59 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item60 = UnoZeroCheckBox( parent, ID_MAGVLIFOR, "Fornit", wx.DefaultPosition, wx.DefaultSize, 0 )
    item60.SetName( "setup_magvlifor" )
    item59.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item61 = UnoZeroCheckBox( parent, ID_MAGVLIMAR, "Marca", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.SetName( "setup_magvlimar" )
    item59.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item62 = UnoZeroCheckBox( parent, ID_MAGVLICAT, "Categ.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item62.SetName( "setup_magvlicat" )
    item59.Add( item62, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item63 = UnoZeroCheckBox( parent, ID_MAGVLIGRU, "Gruppo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item63.SetName( "setup_magvligru" )
    item59.Add( item63, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item57.Add( item59, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item65 = wx.StaticBox( parent, -1, "Sui listini:" )
    item64 = wx.StaticBoxSizer( item65, wx.VERTICAL )
    
    item66 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item67 = wx.StaticText( parent, ID_TEXT, "Ricar:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item67, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item68 = NumCtrl(parent, ID_MAGRICLIS, integerWidth=1, allowNegative=False); item68.SetName('setup_magriclis'); item68.SetToolTipString("Indicare il numero delle ricariche da gestire sui listini (0-9)")
    item66.Add( item68, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item69 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.Add( item69, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item70 = NumCtrl(parent, ID_MAGSCOLIS, integerWidth=1, allowNegative=False); item70.SetName('setup_magscolis'); item70.SetToolTipString("Indicare il numero delle scontistiche da gestire sui listini (0-9)")
    item66.Add( item70, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item64.Add( item66, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item64, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item72 = wx.StaticBox( parent, -1, "Promoz." )
    item71 = wx.StaticBoxSizer( item72, wx.HORIZONTAL )
    
    item73 = UnoZeroCheckBox( parent, ID_MAGPPROMO, "Attiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item73.SetToolTip( wx.ToolTip("Attiva le condizioni promozionali sui prodotti") )
    item73.SetName( "setup_magppromo" )
    item71.Add( item73, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item46.Add( item71, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item75 = wx.StaticBox( parent, -1, "Su gruppo pr.:" )
    item74 = wx.StaticBoxSizer( item75, wx.VERTICAL )
    
    item76 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item77 = wx.StaticText( parent, ID_TEXT, "Ricar:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item76.Add( item77, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item78 = NumCtrl(parent, ID_MAGVRGLIS, integerWidth=1, allowNegative=False); item78.SetName('setup_magvrglis'); item78.SetToolTipString("Indicare il numero delle ricariche del gruppo prezzi da visualizzare (0-3)")
    item76.Add( item78, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item79 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item76.Add( item79, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item80 = NumCtrl(parent, ID_MAGVSGLIS, integerWidth=1, allowNegative=False); item80.SetName('setup_magvsglis'); item80.SetToolTipString("Indicare il numero delle scontistiche del gruppo prezzi da visualizzare (0-3)")
    item76.Add( item80, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item74.Add( item76, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item74, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item82 = wx.StaticBox( parent, -1, "Visualizza %effettiva:" )
    item81 = wx.StaticBoxSizer( item82, wx.VERTICAL )
    
    item83 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item84 = wx.StaticText( parent, ID_TEXT, "Ricarica:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item83.Add( item84, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item85 = UnoZeroCheckBox( parent, ID_MAGREPLIS, "Prezzo p.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.SetToolTip( wx.ToolTip("Attiva la visualizzazione della ricarica effettiva del prezzo al pubblico rispetto al costo ultimo") )
    item85.SetName( "setup_magreplis" )
    item83.Add( item85, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item86 = UnoZeroCheckBox( parent, ID_MAGRELLIS, "Listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item86.SetToolTip( wx.ToolTip("Attiva la visualizzazione della ricarica effettiva di ogni listino rispetto al costo ultimo") )
    item86.SetName( "setup_magrellis" )
    item83.Add( item86, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item87 = wx.StaticText( parent, ID_TEXT, "Sconto:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item83.Add( item87, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item88 = UnoZeroCheckBox( parent, ID_MAGSEPLIS, "Prezzo p.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item88.SetToolTip( wx.ToolTip("Attiva la visualizzazione dello sconto effettivo del costo ultimo rispetto al prezzo al pubblico") )
    item88.SetName( "setup_magseplis" )
    item83.Add( item88, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item89 = UnoZeroCheckBox( parent, ID_MAGSELLIS, "Listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item89.SetToolTip( wx.ToolTip("Attiva la visualizzazione dello sconto effettivo del costo ultimo rispetto ad ogni listino") )
    item89.SetName( "setup_magsellis" )
    item83.Add( item89, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item81.Add( item83, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item46.Add( item81, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item91 = wx.StaticBox( parent, -1, "Su prodotto:" )
    item90 = wx.StaticBoxSizer( item91, wx.VERTICAL )
    
    item92 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item93 = wx.StaticText( parent, ID_TEXT, "Ricar:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.Add( item93, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item94 = NumCtrl(parent, ID_MAGERPLIS, integerWidth=1, allowNegative=False); item94.SetName('setup_magerplis'); item94.SetToolTipString("Indicare il numero delle ricariche del prodotto da gestire (0-3)")
    item92.Add( item94, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item95 = wx.StaticText( parent, ID_TEXT, "Sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.Add( item95, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item96 = NumCtrl(parent, ID_MAGESPLIS, integerWidth=1, allowNegative=False); item96.SetName('setup_magesplis'); item96.SetToolTipString("Indicare il numero delle scontistiche del prodotto da gestire (0-3)")
    item92.Add( item96, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item90.Add( item92, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item90, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item46.AddGrowableCol( 1 )

    item46.AddGrowableCol( 2 )

    item46.AddGrowableCol( 3 )

    item0.Add( item46, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item97 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item99 = wx.StaticBox( parent, -1, "Griglie prezzi Clienti/Fornitori" )
    item98 = wx.StaticBoxSizer( item99, wx.HORIZONTAL )
    
    item100 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item101 = UnoZeroCheckBox( parent, ID_MAGATTGRIP, "Attiva clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item101.SetToolTip( wx.ToolTip("Attiva la gestione delle griglie prezzi di vendita sui clienti") )
    item101.SetName( "setup_magattgrip" )
    item100.Add( item101, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item102 = UnoZeroCheckBox( parent, ID_MAGCDEGRIP, "Cod.esterna prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item102.SetToolTip( wx.ToolTip("Attiva la codifica del prodotto sulla griglia da parte del cliente") )
    item102.SetName( "setup_magcdegrip" )
    item100.Add( item102, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item98.Add( item100, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item103 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item98.Add( item103, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item104 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item105 = UnoZeroCheckBox( parent, ID_MAGATTGRIF, "Attiva fornitori", wx.DefaultPosition, wx.DefaultSize, 0 )
    item105.SetToolTip( wx.ToolTip("Attiva la gestione delle griglie prezzi di acquisto sui fornitori") )
    item105.SetName( "setup_magattgrif" )
    item104.Add( item105, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item106 = UnoZeroCheckBox( parent, ID_MAGCDEGRIF, "Cod.esterna prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item106.SetToolTip( wx.ToolTip("Attiva la codifica del prodotto sulla griglia da parte del fornitore") )
    item106.SetName( "setup_magcdegrif" )
    item104.Add( item106, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item98.Add( item104, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item107 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item98.Add( item107, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item108 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item109 = UnoZeroCheckBox( parent, ID_MAGAGGGRIP, "Aggiorna da doc.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item109.SetToolTip( wx.ToolTip("Attiva la facoltÃ  di creare/aggiornare la griglia dal dataentry di magazzino") )
    item109.SetName( "setup_magagggrip" )
    item108.Add( item109, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item110 = UnoZeroCheckBox( parent, ID_MAGALWGRIP, "Default sempre", wx.DefaultPosition, wx.DefaultSize, 0 )
    item110.SetToolTip( wx.ToolTip("Attiva di default l'aggiornamento della griglia dal dataentry di magazzino") )
    item110.SetName( "setup_magalwgrip" )
    item108.Add( item110, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item111 = UnoZeroCheckBox( parent, ID_MAGDATGRIP, "Griglie per data", wx.DefaultPosition, wx.DefaultSize, 0 )
    item111.SetToolTip( wx.ToolTip("Attiva la gestione delle griglie per data") )
    item111.SetName( "setup_magdatgrip" )
    item108.Add( item111, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item98.Add( item108, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item112 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item98.Add( item112, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT, 5 )

    item97.Add( item98, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item113 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item115 = wx.StaticBox( parent, -1, "Vettori" )
    item114 = wx.StaticBoxSizer( item115, wx.HORIZONTAL )
    
    item116 = UnoZeroCheckBox( parent, ID_MAGNOCODEVET, "Variaz.manuale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item116.SetToolTip( wx.ToolTip("Attiva la possibilitÃ  di variazione manuale del vettore sul singolo documento, senza doverlo codificare") )
    item116.SetName( "setup_magnocodevet" )
    item114.Add( item116, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item117 = UnoZeroCheckBox( parent, ID_MAGNOCDEFVET, "Default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item117.SetToolTip( wx.ToolTip("Imposta di default il nuovo documento con giÃ  spuntata la casella di variazione manuale del vettore") )
    item117.SetName( "setup_magnocdefvet" )
    item114.Add( item117, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item118 = UnoZeroCheckBox( parent, ID_MAGEXTRAVET, "Extra-dati", wx.DefaultPosition, wx.DefaultSize, 0 )
    item118.SetToolTip( wx.ToolTip("Attiva extra-dati sui vettori") )
    item118.SetName( "setup_magextravet" )
    item114.Add( item118, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item113.Add( item114, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item120 = wx.StaticBox( parent, -1, "Destinazioni merce" )
    item119 = wx.StaticBoxSizer( item120, wx.HORIZONTAL )
    
    item121 = UnoZeroCheckBox( parent, ID_MAGNOCODEDES, "Variaz.manuale", wx.DefaultPosition, wx.DefaultSize, 0 )
    item121.SetToolTip( wx.ToolTip("Attiva la possibilitÃ  di variazione manuale della destinazione merce sul singolo documento, senza doverla codificare") )
    item121.SetName( "setup_magnocodedes" )
    item119.Add( item121, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item122 = UnoZeroCheckBox( parent, ID_MAGNOCDEFDES, "Default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item122.SetToolTip( wx.ToolTip("Imposta di default il nuovo documento con giÃ  spuntata la casella di variazione manuale della destinazione") )
    item122.SetName( "setup_magnocdefdes" )
    item119.Add( item122, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item113.Add( item119, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.RIGHT, 5 )

    item113.AddGrowableCol( 0 )

    item113.AddGrowableRow( 1 )

    item97.Add( item113, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item97.AddGrowableCol( 1 )

    item0.Add( item97, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item123 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item125 = wx.StaticBox( parent, -1, "Immagine del prodotto" )
    item124 = wx.StaticBoxSizer( item125, wx.VERTICAL )
    
    item126 = UnoZeroCheckBox( parent, ID_MAGIMGPROD, "Attiva se presente", wx.DefaultPosition, wx.DefaultSize, 0 )
    item126.SetName( "setup_magimgprod" )
    item124.Add( item126, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item123.Add( item124, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item128 = wx.StaticBox( parent, -1, "Ricerca prodotti" )
    item127 = wx.StaticBoxSizer( item128, wx.HORIZONTAL )
    
    item129 = CheckBox( parent, ID_MAGDIGSEARCH, "Cerca in digitaz. codice", wx.DefaultPosition, wx.DefaultSize, 0 )
    item129.SetName( "setup_magdigsearch" )
    item127.Add( item129, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item130 = UnoZeroCheckBox( parent, ID_MAGRETSEARCH, "Cerca con Invio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item130.SetName( "setup_magretsearch" )
    item127.Add( item130, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item131 = UnoZeroCheckBox( parent, ID_MAGEXCSEARCH, "Ricerca esclusiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item131.SetName( "setup_magexcsearch" )
    item127.Add( item131, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item132 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [-1,20], wx.LI_VERTICAL )
    item127.Add( item132, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.RIGHT, 5 )

    item133 = wx.StaticText( parent, ID_TEXT, "Visualizza:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item127.Add( item133, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item134 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item135 = UnoZeroCheckBox( parent, ID_MAGVISGIA, "Giacenza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item135.SetName( "setup_magvisgia" )
    item134.Add( item135, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item136 = UnoZeroCheckBox( parent, ID_MAGVISDIS, "Disponib.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item136.SetName( "setup_magvisdis" )
    item134.Add( item136, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item127.Add( item134, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item137 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item138 = UnoZeroCheckBox( parent, ID_MAGVISCOS, "Costo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item138.SetName( "setup_magviscos" )
    item137.Add( item138, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item139 = UnoZeroCheckBox( parent, ID_MAGVISPRE, "Prezzo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item139.SetName( "setup_magvispre" )
    item137.Add( item139, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item127.Add( item137, 0, wx.ALIGN_CENTER, 5 )

    item140 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item141 = UnoZeroCheckBox( parent, ID_MAGVISCPF, "Cod.Forn.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item141.SetName( "setup_magviscpf" )
    item140.Add( item141, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item142 = UnoZeroCheckBox( parent, ID_MAGVISBCD, "Barcode", wx.DefaultPosition, wx.DefaultSize, 0 )
    item142.SetName( "setup_magvisbcd" )
    item140.Add( item142, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item127.Add( item140, 0, wx.ALIGN_CENTER, 5 )

    item123.Add( item127, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item123.AddGrowableCol( 1 )

    item0.Add( item123, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item143 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item145 = wx.StaticBox( parent, -1, "Provvigioni" )
    item144 = wx.StaticBoxSizer( item145, wx.HORIZONTAL )
    
    item146 = UnoZeroCheckBox( parent, ID_MAGPROVATT, "Attiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item146.SetName( "setup_magprovatt" )
    item144.Add( item146, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item147 = UnoZeroCheckBox( parent, ID_MAGPROVCLI, "Su clienti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item147.SetName( "setup_magprovcli" )
    item144.Add( item147, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item148 = UnoZeroCheckBox( parent, ID_MAGPROVPRO, "Su prodotti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item148.SetName( "setup_magprovpro" )
    item144.Add( item148, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item143.Add( item144, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item149 = MagProvMovRadioBox( parent, ID_MAGPROVMOV, "Provvig. sui movimenti", wx.DefaultPosition, wx.DefaultSize, 
        ["Default","Eredita"] , 1, wx.RA_SPECIFY_ROWS )
    item149.SetName( "setup_magprovmov" )
    item143.Add( item149, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item151 = wx.StaticBox( parent, -1, "Gerarchia ereditarietà" )
    item150 = wx.StaticBoxSizer( item151, wx.HORIZONTAL )
    
    item152 = wx.StaticText( parent, ID_TEXT, "Sequenza priorità provvig.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item150.Add( item152, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item153 = wx.TextCtrl( parent, ID_MAGPROVSEQ, "", wx.DefaultPosition, [80,-1], 0 )
    item153.SetName( "setup_magprovseq" )
    item150.Add( item153, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item143.Add( item150, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item143.AddGrowableCol( 2 )

    item0.Add( item143, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_OPTNOTIFICHE = 15083
ID_OPTTABSEARCH = 15084
ID_OPTDIGSEARCH = 15085
ID_OPTSPASEARCH = 15086
ID_OPTLNKCRDPDC = 15087
ID_OPTLNKGRDPDC = 15088
ID_OPTLNKCRDCLI = 15089
ID_OPTLNKGRDCLI = 15090
ID_OPTLNKCRDFOR = 15091
ID_OPTLNKGRDFOR = 15092
ID_BACKUPDIR = 15093
ID_GCP_USER = 15094
ID_GCP_PSWD = 15095
ID_GC_PRINT = 15096

def OpzioniFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Notifiche" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = UnoZeroCheckBox( parent, ID_OPTNOTIFICHE, "Attiva notifiche (Email, XMPP)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetName( "setup_optnotifiche" )
    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.StaticBox( parent, -1, "Ricerche" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )
    
    item6 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item7 = UnoZeroCheckBox( parent, ID_OPTTABSEARCH, "Attiva la ricerca con il tasto Tab", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetName( "setup_opttabsearch" )
    item6.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item8 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Attiva la ricerca con il tasto Invio", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "setup_optretsearch" )
    item6.Add( item8, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.BOTTOM, 5 )

    item9 = UnoZeroCheckBox( parent, ID_OPTDIGSEARCH, "Cerca durante la digitazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetName( "setup_optdigsearch" )
    item6.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item10 = UnoZeroCheckBox( parent, ID_OPTSPASEARCH, "Cerca per contenuto con \" \" (spazio)", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "setup_optspasearch" )
    item6.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item4.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "Alla ricezione del focus di tastiera, sui seguenti elementi di ricerca anagrafica imposta la priorità  sulla descrizione:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item13 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item14 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item14, 0, wx.ALIGN_CENTER|wx.RIGHT|wx.TOP, 5 )

    item15 = wx.StaticText( parent, ID_TEXT, "In Scheda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "In griglia", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item16, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Piano dei Conti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item17, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item18 = UnoZeroCheckBox( parent, ID_OPTLNKCRDPDC, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetName( "setup_optlnkcrdpdc" )
    item13.Add( item18, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item19 = UnoZeroCheckBox( parent, ID_OPTLNKGRDPDC, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetName( "setup_optlnkgrdpdc" )
    item13.Add( item19, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Clienti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21 = UnoZeroCheckBox( parent, ID_OPTLNKCRDCLI, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetName( "setup_optlnkcrdcli" )
    item13.Add( item21, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item22 = UnoZeroCheckBox( parent, ID_OPTLNKGRDCLI, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "setup_optlnkgrdcli" )
    item13.Add( item22, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item23 = wx.StaticText( parent, ID_TEXT, "Fornitori:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item23, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item24 = UnoZeroCheckBox( parent, ID_OPTLNKCRDFOR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.SetName( "setup_optlnkcrdfor" )
    item13.Add( item24, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item25 = UnoZeroCheckBox( parent, ID_OPTLNKGRDFOR, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.SetName( "setup_optlnkgrdfor" )
    item13.Add( item25, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item13.AddGrowableCol( 1 )

    item13.AddGrowableCol( 2 )

    item4.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticBox( parent, -1, "Percorso backup azienda" )
    item26 = wx.StaticBoxSizer( item27, wx.VERTICAL )
    
    item28 = FolderEntryCtrl( parent, ID_BACKUPDIR, "", wx.DefaultPosition, [280,-1], 0 )
    item28.SetName( "setup_optbackupdir" )
    item26.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item30 = wx.StaticBox( parent, -1, "Google Account" )
    item29 = wx.StaticBoxSizer( item30, wx.VERTICAL )
    
    item31 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item32 = wx.StaticText( parent, ID_TEXT, "Username:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item32, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item33 = TextCtrl_LC( parent, ID_GCP_USER, "", wx.DefaultPosition, [80,-1], 0 )
    item33.SetName( "setup_opt_gcp_user" )
    item31.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item34 = wx.StaticText( parent, ID_TEXT, "Password:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.Add( item34, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item35 = TextCtrl_LC( parent, ID_GCP_PSWD, "", wx.DefaultPosition, [80,-1], wx.TE_PASSWORD )
    item35.SetName( "setup_opt_gcp_pswd" )
    item31.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item31.AddGrowableCol( 1 )

    item31.AddGrowableCol( 3 )

    item29.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item36 = UnoZeroCheckBox( parent, ID_GC_PRINT, "Abilita stampe su Google Cloud Print", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.SetName( "setup_opt_gc_print" )
    item29.Add( item36, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXTCTRL = 15097
ID_AZIENDA_LOGO = 15098

def DatiAziendaFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.StaticBox( parent, -1, "Intestazione azienda" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item4 = wx.StaticText( parent, ID_TEXT, "Codice:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item3.Add( item4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [100,-1], 0 )
    item5.SetName( "setup_azienda_codice" )
    item3.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item1.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item7 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item8 = wx.StaticText( parent, ID_TEXT, "Ragione Sociale:", wx.DefaultPosition, [100,-1], wx.ALIGN_RIGHT )
    item7.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item9 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [360,-1], 0 )
    item9.SetName( "setup_azienda_ragsoc" )
    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "Indirizzo:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item11 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "setup_azienda_indirizzo" )
    item7.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "CAP, Città, Prov.:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item12, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item13 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item14 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item14.SetName( "setup_azienda_cap" )
    item13.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item15 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetName( "setup_azienda_citta" )
    item13.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item16 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item16.SetName( "setup_azienda_prov" )
    item13.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item13.AddGrowableCol( 1 )

    item7.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Cod.Fiscale:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item17, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item18 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item19 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item19.SetName( "setup_azienda_codfisc" )
    item18.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item18.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item21 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item21.SetName( "setup_azienda_stato" )
    item18.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item22 = wx.StaticText( parent, ID_TEXT, "P.IVA:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item18.Add( item22, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item23 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [90,-1], 0 )
    item23.SetName( "setup_azienda_piva" )
    item18.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item18.AddGrowableCol( 0 )

    item18.AddGrowableCol( 4 )

    item7.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Telefono:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item24, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item25 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item26 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.SetName( "setup_azienda_numtel" )
    item25.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27 = wx.StaticText( parent, ID_TEXT, "FAX:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item25.Add( item27, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item28 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item28.SetName( "setup_azienda_numfax" )
    item25.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item25.AddGrowableCol( 0 )

    item25.AddGrowableCol( 2 )

    item7.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item29 = wx.StaticText( parent, ID_TEXT, "email:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item29, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item30 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.SetName( "setup_azienda_email" )
    item7.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item31 = wx.StaticText( parent, ID_TEXT, "Titolare privacy:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item7.Add( item31, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item32 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetName( "setup_azienda_titprivacy" )
    item7.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item7.AddGrowableCol( 1 )

    item1.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item33 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item34 = wx.StaticText( parent, ID_TEXT, "Logo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item35 = wx.StaticText( parent, ID_TEXT, "Descrizione attività:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item36 = PhotoContainerPanel( parent, ID_AZIENDA_LOGO, wx.DefaultPosition, [128,128], wx.SUNKEN_BORDER )
    item36.SetName( "azienda_logo" )
    item33.Add( item36, 0, wx.LEFT|wx.BOTTOM, 5 )

    item37 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,40], wx.TE_MULTILINE )
    item37.SetName( "setup_azienda_infatti" )
    item33.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item33.AddGrowableCol( 1 )

    item33.AddGrowableRow( 1 )

    item0.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_FTEL_ACQPDC = 15099
ID_FTEL_EEB_URL = 15100
ID_FTEL_EEB_USER = 15101
ID_FTEL_EEB_PSWD = 15102
ID_REGFISC = 15103
ID_TIPORIT = 15104
ID_PAGRITACC = 15105
ID_CASSAPREV = 15106

def FTEL_Setup( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.StaticBox( parent, -1, "Acquisti" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )
    
    item4 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item5 = wx.StaticText( parent, ID_TEXT, "Costo generico per acquisizione fatture fornitori", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item6 = alib.LinkTablePdc(parent, ID_FTEL_ACQPDC, 'setup_ftel_acqpdc')
    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item4.AddGrowableCol( 0 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item8 = wx.StaticBox( parent, -1, "Vendite" )
    item7 = wx.StaticBoxSizer( item8, wx.VERTICAL )
    
    item9 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Escludi clienti esteri", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.SetName( "setup_ftel_solita" )
    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item10 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Includi codici prod.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "setup_ftel_vencod" )
    item7.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item11 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Allega copia PDF", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.SetName( "setup_ftel_venpdf" )
    item7.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item1.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item13 = wx.StaticBox( parent, -1, "ebill.evolsia.srl" )
    item12 = wx.StaticBoxSizer( item13, wx.VERTICAL )
    
    item14 = wx.FlexGridSizer( 0, 3, 0, 0 )
    
    item15 = wx.StaticText( parent, ID_TEXT, "Webservice URL:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "Username:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Password:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item18 = TextCtrl_LC( parent, ID_FTEL_EEB_URL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetName( "setup_ftel_eeb_url" )
    item14.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item19 = TextCtrl_LC( parent, ID_FTEL_EEB_USER, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetName( "setup_ftel_eeb_user" )
    item14.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item20 = TextCtrl_LC( parent, ID_FTEL_EEB_PSWD, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.SetName( "setup_ftel_eeb_pswd" )
    item14.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item14.AddGrowableCol( 0 )

    item14.AddGrowableCol( 1 )

    item14.AddGrowableCol( 2 )

    item12.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item21 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item22 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item22.AddGrowableCol( 0 )

    item21.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item21.AddGrowableCol( 0 )

    item21.AddGrowableCol( 1 )

    item12.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableCol( 2 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item23 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item24 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item26 = wx.StaticBox( parent, -1, "Dati per la Fattura Elettronica" )
    item25 = wx.StaticBoxSizer( item26, wx.VERTICAL )
    
    item27 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item28 = wx.StaticText( parent, ID_TEXT, "Nome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item28, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item29 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item30 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.SetName( "setup_azienda_ftel_nome" )
    item29.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item31 = wx.StaticText( parent, ID_TEXT, "Cognome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.Add( item31, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item32 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetName( "setup_azienda_ftel_cognome" )
    item29.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item29.AddGrowableCol( 0 )

    item29.AddGrowableCol( 2 )

    item27.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item33 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item33, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item34 = wx.StaticText( parent, ID_TEXT, "Stabile organizzazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item34, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item35 = wx.StaticText( parent, ID_TEXT, "Indirizzo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item35, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item36 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [200,-1], 0 )
    item36.SetName( "setup_azienda_ftel_soind" )
    item27.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item37 = wx.StaticText( parent, ID_TEXT, "CAP, Città, Prov.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item37, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item38 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item39 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item39.SetName( "setup_azienda_ftel_socap" )
    item38.Add( item39, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item40 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item40.SetName( "setup_azienda_ftel_socit" )
    item38.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item41 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item41.SetName( "setup_azienda_ftel_sopro" )
    item38.Add( item41, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item38.AddGrowableCol( 1 )

    item27.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item42 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item42, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item43 = wx.StaticText( parent, ID_TEXT, "Dati azienda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item43, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item44 = wx.StaticText( parent, ID_TEXT, "Regime fiscale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item44, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item45 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item46 = RegimeFiscaleChoice( parent, ID_REGFISC, wx.DefaultPosition, [100,-1], 
        ["RF01 - Ordinario","RF02 - Contribuenti minimi (art. 1, c.96-117, L. 244/2007)","RF03 - Nuove iniziative produttive (art.13, L. 388/2000)","RF04 - Agricoltura e attività connesse e pesca (artt. 34 e 34-bis, D.P.R. 633/1972)","RF05 - Vendita sali e tabacchi (art. 74, c.1, D.P.R. 633/1972)","RF06 - Commercio dei fiammiferi (art. 74, c.1, D.P.R.633/1972)","RF07 - Editoria (art. 74, c.1, D.P.R. 633/1972)","RF08 - Gestione di servizi di telefonia pubblica (art. 74, c.1,D.P.R. 633/1972)","RF09 - Rivendita di documenti di trasporto pubblico e di sosta (art. 74, c.1, D.P.R. 633/1972)","RF10 - Intrattenimenti, giochi e altre attività di cui alla tariffa allegata al D.P.R. n. 640/72 (art. 74, c.6, D.P.R.633/1972)","RF11 - Agenzie di viaggi e turismo (art. 74-ter, D.P.R. ","RF12 - Agriturismo (art. 5, c.2, L. 413/1991)","RF13 - Vendite a domicilio (art. 25-bis, c.6, D.P.R. 600/1973)","RF14 - Rivendita di beni usati, di oggetti d’arte, d’antiquariato o ","RF15 - Agenzie di vendite all’asta di oggetti d’arte, antiquariato ","RF16 - IVA per cassa P.A. (art. 6, c.5, D.P.R. 633/1972)","RF17 - IVA per cassa soggetti con volume d’affari inferiore a Eur 200.000 (art. 7, D.L. 185/2008)","RF19 - Regime forfettario (art.1, c.54-89, L. 190/2014)","RF18 - Altro"] , 0 )
    item46.SetName( "setup_azienda_ftel_regfisc" )
    item45.Add( item46, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item45.AddGrowableCol( 0 )

    item27.Add( item45, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item47, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item48 = wx.StaticText( parent, ID_TEXT, "Dati REA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item48, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item49 = wx.StaticText( parent, ID_TEXT, "Num.Iscriz:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item49, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item50 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item51 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item51.SetName( "setup_azienda_ftel_reanum" )
    item50.Add( item51, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item52 = wx.StaticText( parent, ID_TEXT, "Ufficio:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item50.Add( item52, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item53 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item53.SetName( "setup_azienda_ftel_reauff" )
    item50.Add( item53, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item54 = wx.StaticText( parent, ID_TEXT, "Capitale sociale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item54, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item55 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item56 = NumCtrl(parent, integerWidth=6, fractionWidth=2, allowNegative=False); item56.SetName('setup_azienda_ftel_capsoc')
    item55.Add( item56, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item57 = UnoZeroCheckBox( parent, ID_CHECKBOX, "Socio unico", wx.DefaultPosition, wx.DefaultSize, 0 )
    item57.SetName( "setup_azienda_ftel_socuni" )
    item55.Add( item57, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item58 = UnoZeroCheckBox( parent, ID_CHECKBOX, "In liquidazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item58.SetName( "setup_azienda_ftel_socliq" )
    item55.Add( item58, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item27.Add( item55, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item27.AddGrowableCol( 1 )

    item25.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item60 = wx.StaticBox( parent, -1, "Soggetto trasmittente se diverso da cedente/prestatore" )
    item59 = wx.StaticBoxSizer( item60, wx.VERTICAL )
    
    item61 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item62 = wx.StaticText( parent, ID_TEXT, "C.F./P.I.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.Add( item62, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item63 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item63.SetName( "setup_azienda_ftel_trcodfis" )
    item61.Add( item63, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item64 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.Add( item64, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item65 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item65.SetName( "setup_azienda_ftel_trstato" )
    item61.Add( item65, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item59.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24.Add( item59, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item67 = wx.StaticBox( parent, -1, "Ritenuta d'acconto" )
    item66 = wx.StaticBoxSizer( item67, wx.VERTICAL )
    
    item68 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item69 = wx.StaticText( parent, ID_TEXT, "Tipo di ritenuta:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item69, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item70 = TipoRitenutaChoice( parent, ID_TIPORIT, wx.DefaultPosition, [100,-1], 
        ["RT01 - Ritenuta persone fisiche","RT02 - Ritenuta persone giuridiche"] , 0 )
    item70.SetName( "setup_azienda_ftel_ritacctipo" )
    item68.Add( item70, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item71 = wx.StaticText( parent, ID_TEXT, "Codice Tipo pagamento ritenuta (A):", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.Add( item71, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item72 = TextCtrl( parent, ID_PAGRITACC, "", wx.DefaultPosition, [80,-1], 0 )
    item72.SetName( "setup_azienda_ftel_ritaccpag" )
    item68.Add( item72, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item68.AddGrowableCol( 1 )

    item66.Add( item68, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item74 = wx.StaticBox( parent, -1, "Cassa previdenziale" )
    item73 = wx.StaticBoxSizer( item74, wx.VERTICAL )
    
    item75 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item76 = wx.StaticText( parent, ID_TEXT, "Tipo cassa:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item75.Add( item76, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item77 = TipoCassaPrevidenzaChoice( parent, ID_CASSAPREV, wx.DefaultPosition, [100,-1], 
        ["TC01 - Cassa nazionale previdenza avvocati e procuratori legali","TC02 - Cassa previdenza dottori commercialisti","TC03 - Cassa previdenza e assistenza geometri","TC04 - Cassa nazionale ingegneri e architetti liberi professionisti","TC05 - Cassa nazionale del notariato","TC06 - Cassa nazionale ragionieri e periti commerciali","TC07 - ENASARCO","TC08 - ENPACL","TC09 - ENPAM","TC10 - ENPAF","TC11 - ENPAV","TC12 - ENPAIA","TC13 - Fondo prev. impiegati imprese spediz. e ag. marittime","TC14 - INPGI","TC15 - ONAOSI","TC16 - CASAGIT","TC17 - EPPI","TC18 - EPAP","TC19 - ENPAB","TC20 - ENPAPI","TC21 - ENPAP","TC22 - INPS"] , 0 )
    item77.SetName( "setup_azienda_ftel_cassaprev" )
    item75.Add( item77, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item75.AddGrowableCol( 1 )

    item73.Add( item75, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24.Add( item73, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item24.AddGrowableCol( 0 )

    item24.AddGrowableRow( 2 )

    item23.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item78 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item80 = wx.StaticBox( parent, -1, "Rappresentante fiscale" )
    item79 = wx.StaticBoxSizer( item80, wx.VERTICAL )
    
    item81 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item82 = wx.StaticText( parent, ID_TEXT, "Nome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item81.Add( item82, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item83 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item84 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item84.SetName( "setup_azienda_ftel_rfnome" )
    item83.Add( item84, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item85 = wx.StaticText( parent, ID_TEXT, "Cognome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item83.Add( item85, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item86 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item86.SetName( "setup_azienda_ftel_rfcognome" )
    item83.Add( item86, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item83.AddGrowableCol( 0 )

    item83.AddGrowableCol( 2 )

    item81.Add( item83, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item87 = wx.StaticText( parent, ID_TEXT, "Ragione sociale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item81.Add( item87, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item88 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [200,-1], 0 )
    item88.SetName( "setup_azienda_ftel_rfdes" )
    item81.Add( item88, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item89 = wx.StaticText( parent, ID_TEXT, "Indirizzo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item81.Add( item89, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item90 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item90.SetName( "setup_azienda_ftel_rfind" )
    item81.Add( item90, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item91 = wx.StaticText( parent, ID_TEXT, "CAP, Città, Prov.:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item81.Add( item91, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item92 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item93 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [60,-1], 0 )
    item93.SetName( "setup_azienda_ftel_rfcap" )
    item92.Add( item93, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item94 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item94.SetName( "setup_azienda_ftel_rfcit" )
    item92.Add( item94, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item95 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item95.SetName( "setup_azienda_ftel_rfpro" )
    item92.Add( item95, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item92.AddGrowableCol( 1 )

    item81.Add( item92, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item96 = wx.StaticText( parent, ID_TEXT, "Cod.Fiscale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item81.Add( item96, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item97 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item98 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item98.SetName( "setup_azienda_ftel_rfcodfis" )
    item97.Add( item98, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item99 = wx.StaticText( parent, ID_TEXT, "P.IVA:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item97.Add( item99, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item100 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [90,-1], 0 )
    item100.SetName( "setup_azienda_ftel_rfpiva" )
    item97.Add( item100, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item101 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item97.Add( item101, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item102 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item102.SetName( "setup_azienda_ftel_rfstato" )
    item97.Add( item102, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item97.AddGrowableCol( 1 )

    item81.Add( item97, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item81.AddGrowableCol( 1 )

    item79.Add( item81, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item78.Add( item79, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item104 = wx.StaticBox( parent, -1, "Terzo intermediario o soggetto emittente" )
    item103 = wx.StaticBoxSizer( item104, wx.VERTICAL )
    
    item105 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item106 = wx.StaticText( parent, ID_TEXT, "Cod.Fiscale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item105.Add( item106, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item107 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item108 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [120,-1], 0 )
    item108.SetName( "setup_azienda_ftel_secodfis" )
    item107.Add( item108, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item109 = wx.StaticText( parent, ID_TEXT, "P.IVA:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item107.Add( item109, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item110 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [90,-1], 0 )
    item110.SetName( "setup_azienda_ftel_sepiva" )
    item107.Add( item110, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item111 = wx.StaticText( parent, ID_TEXT, "Stato:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item107.Add( item111, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item112 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [35,-1], 0 )
    item112.SetName( "setup_azienda_ftel_sestato" )
    item107.Add( item112, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item107.AddGrowableCol( 1 )

    item105.Add( item107, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item113 = wx.StaticText( parent, ID_TEXT, "Ragione sociale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item105.Add( item113, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item114 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item114.SetName( "setup_azienda_ftel_sedes" )
    item105.Add( item114, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item115 = wx.StaticText( parent, ID_TEXT, "Nome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item105.Add( item115, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item116 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item117 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item117.SetName( "setup_azienda_ftel_senome" )
    item116.Add( item117, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item118 = wx.StaticText( parent, ID_TEXT, "Cognome:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item116.Add( item118, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item119 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item119.SetName( "setup_azienda_ftel_secognome" )
    item116.Add( item119, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item116.AddGrowableCol( 0 )

    item116.AddGrowableCol( 2 )

    item105.Add( item116, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item120 = wx.StaticText( parent, ID_TEXT, "Titolo:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item105.Add( item120, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item121 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item122 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item122.SetName( "setup_azienda_ftel_setit" )
    item121.Add( item122, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item123 = wx.StaticText( parent, ID_TEXT, "Cod. EORI:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item121.Add( item123, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item124 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [100,-1], 0 )
    item124.SetName( "setup_azienda_ftel_seeori" )
    item121.Add( item124, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item121.AddGrowableCol( 0 )

    item105.Add( item121, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item105.AddGrowableCol( 1 )

    item103.Add( item105, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item78.Add( item103, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item125 = SoggettoEmittenteRadioBox( parent, ID_RADIOBOX, "Soggetto emittente", wx.DefaultPosition, wx.DefaultSize, 
        ["XX - Non specificato","CC - Cessionario/Committ.","TZ - SoggettoTerzo"] , 1, wx.RA_SPECIFY_ROWS )
    item125.SetName( "setup_azienda_ftel_sesogemi" )
    item78.Add( item125, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item78.AddGrowableCol( 0 )

    item78.AddGrowableRow( 1 )

    item23.Add( item78, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item23.AddGrowableCol( 0 )

    item23.AddGrowableCol( 1 )

    item0.Add( item23, 0, wx.GROW, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableCol( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
