# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: caumagazz.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from anag.basetab import AnagCardPanel

from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.numctrl import NumCtrl
from awc.controls.radiobox import RadioBox
from awc.controls.checkbox import CheckBox
from awc.controls.linktable import LinkTable
from awc.controls.dbgrid import DbGrid
from awc.controls.entries import PrintersComboBox
from awc.controls.notebook import Notebook

from anag.pdctip import PdcTipDialog
from anag.pdc import PdcDialog
from cfg.caucontab import CauContabDialog
from anag.trasp import TraCauDialog, TraCurDialog, TraVetDialog, TraAspDialog, TraPorDialog, TraConDialog
from anag.mag import MagazzDialog

from anag.lib import LinkTableCauContab, LinkTablePdc
import anag.lib as alib

from Env import Azienda
bt = Azienda.BaseTab

class RCheckBox(CheckBox):
    def __init__(self, parent, id, label, pos, size, style):
        style = wx.ALIGN_RIGHT
        CheckBox.__init__(self, parent, id, label, pos, size, style)

class DocNotebook(Notebook):
    def __init__(self, *args, **kwargs):
        Notebook.__init__(self, *args, **kwargs)
        self.SetName('docbook')

class MovNotebook(Notebook):
    def __init__(self, *args, **kwargs):
        Notebook.__init__(self, *args, **kwargs)
        self.SetName('movbook')

class LinkedCheckBox(CheckBox):
    
    values = None
    linkname = None
    
    def __init__(self, *args, **kwargs):
        CheckBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=self.values)
        self.Bind(wx.EVT_CHECKBOX, self.OnChanged)
    
    def OnChanged(self, event):
        self.CheckChecked()
        event.Skip()
    
    def SetValue(self, *args, **kwargs):
        CheckBox.SetValue(self, *args, **kwargs)
        self.CheckChecked()
    
    def CheckChecked(self):
        self.GetParent().FindWindowByName(self.linkname).Enable(self.IsChecked())
    
class ColCgCheckBox(LinkedCheckBox):
    
    values = values={True: "X", False: " "}
    linkname = 'id_caucg'
    
class RitAccCheckBox(LinkedCheckBox):
    
    values = values={True: 1, False: 0}
    linkname = 'id_pdc_ra'


class ScoDocCheckBox(LinkedCheckBox):
    
    values = values={True: 1, False: 0}
    linkname = 'id_pdc_sd'


class AccorpaIvaCheckBox(RCheckBox):
    
    def __init__(self, *args, **kwargs):
        RCheckBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values={True:1, False: 0})


from cfg.caucontab_wdr import TipoDocumentoRadioBox as FTEL_TipoDocumentoRadioBox

# Window functions

ID_ANAGMAIN = 16000
ID_DOCBOOK = 16001

def CauMagazzCardFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = AnagCardPanel(parent, -1)
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = DocNotebook( parent, ID_DOCBOOK, wx.DefaultPosition, [200,160], 0 )
    item2 = item3
    
    item4 = wx.Panel( item3, -1 )
    Doc1Func(item4, False)
    item3.AddPage( item4, "Setup documento #1" )

    item5 = wx.Panel( item3, -1 )
    Doc2Func(item5, False)
    item3.AddPage( item5, "Setup documento #2" )

    item6 = wx.Panel( item3, -1 )
    MovFunc(item6, False)
    item3.AddPage( item6, "Setup movimenti" )

    item7 = wx.Panel( item3, -1 )
    Doc3Func(item7, False)
    item3.AddPage( item7, "Testo email" )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 16002
ID_DESCANAG = 16003
ID_CTRPDCTIP = 16004
ID_NUMDOC = 16005
ID_DATDOC = 16006
ID_RADIOBOX = 16007
ID_FTEL_NODDT = 16008
ID_FTEL_AUTACQ = 16009
ID_FTEL_AACQTD = 16010
ID_TEXTCTRL = 16011
ID_CTRNUM = 16012
ID_AGGNUM = 16013
ID_PIENUM = 16014
ID_NONUMXMAG = 16015
ID_ASKMAGAZZ = 16016
ID_PDCDAMAG = 16017
ID_ASKMODPAG = 16018
ID_ASKBANCA = 16019
ID_ASKMPNOEFF = 16020
ID_ASKDESTIN = 16021
ID_ASKAGENTE = 16022
ID_ASKZONA = 16023
ID_ASKLISTINO = 16024
ID_ROWLISTINO = 16025
ID_TOTALI = 16026
ID_TOTZERO = 16027
ID_TOTNEG = 16028
ID_CLASDOC = 16029
ID_ASKRIFDESC = 16030
ID_ASKRIFNUM = 16031
ID_ASKRIFDATA = 16032
ID_NUMSCONTI = 16033
ID_PANGRIDPERM = 16034
ID_MAGAZZ = 16035
ID_MODPAG = 16036
ID_TDOCTRA = 16037
ID_PROVVIG = 16038
ID_STETIC = 16039
ID_TOOLPRINT = 16040
ID_FTEL_LAYOUT = 16041
ID_TOOLBARRA = 16042
ID_COMBO = 16043
ID_COPIES = 16044
ID_STAINTEST = 16045
ID_ASKSTAINT = 16046
ID_STAOBB = 16047
ID_STALOGO = 16048
ID_ASKSTAPRE = 16049
ID_STANOC = 16050
ID_DOCEMAIL = 16051
ID_AANOTEDOC = 16052

def Doc1Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item4 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item6 = wx.StaticBox( parent, -1, "" )
    item5 = wx.StaticBoxSizer( item6, wx.VERTICAL )
    
    item7 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item8 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item9 = wx.StaticText( parent, ID_TEXT, "Descrizione dell'anagrafica:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item10 = TextCtrl_LC( parent, ID_DESCANAG, "", wx.DefaultPosition, [140,-1], 0 )
    item10.SetName( "descanag" )
    item8.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item8.AddGrowableCol( 0 )

    item7.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item12 = wx.StaticText( parent, ID_TEXT, "Tipologia:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item13 = LinkTable(parent, ID_CTRPDCTIP ); item13.SetDataLink( bt.TABNAME_PDCTIP, "id_pdctip", PdcTipDialog )
    item11.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item11.AddGrowableCol( 0 )

    item7.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7.AddGrowableCol( 1 )

    item5.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item15 = RadioBox( parent, ID_NUMDOC, "Proposizione Numero documento", wx.DefaultPosition, wx.DefaultSize, 
        ["Zero","Da setup documento/famiglia","Da protocollo IVA","Da documenti/famiglia a piede"] , 1, wx.RA_SPECIFY_COLS )
    item15.SetName( "numdoc" )
    item14.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item16 = RadioBox( parent, ID_DATDOC, "Gestione Data documento", wx.DefaultPosition, wx.DefaultSize, 
        ["Nessuna gestione (data vuota)","Proposta data nulla","Proposta data registrazione","Proposta ultima data documento/famiglia","Non richiesta (=data registrazione)"] , 1, wx.RA_SPECIFY_COLS )
    item16.SetName( "datdoc" )
    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item14.AddGrowableCol( 0 )

    item14.AddGrowableCol( 1 )

    item4.Add( item14, 0, wx.GROW, 5 )

    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item18 = FTEL_TipoDocumentoRadioBox( parent, ID_RADIOBOX, "Tipo documento attura elettronica, da causale contabile", wx.DefaultPosition, wx.DefaultSize, 
        ["Non gestito","TD01 - Fattura","TD02 - Acconto ft.","TD03 - Acconto parcella","TD04 - Nota credito","TD05 - Nota debito","TD06 - Parcella","TD07 - Fattura semplif.","TD08 - Nota cr. semplif.","TD09 - Non utilizzato","TD10 - Ft. Intra beni","TD11 - Ft. Intra servizi"] , 2, wx.RA_SPECIFY_COLS )
    item18.SetName( "ftel_tipdoc" )
    item17.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item19 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item21 = wx.StaticBox( parent, -1, "Riferimento ai DDT" )
    item20 = wx.StaticBoxSizer( item21, wx.HORIZONTAL )
    
    item22 = CheckBox( parent, ID_FTEL_NODDT, "Escludi se doc.differito", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "ftel_noddt" )
    item20.Add( item22, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item19.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item24 = wx.StaticBox( parent, -1, "Emissione doc. x conto di:" )
    item23 = wx.StaticBoxSizer( item24, wx.HORIZONTAL )
    
    item25 = CheckBox( parent, ID_FTEL_AUTACQ, "Sogg.Emitt.CC", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.SetName( "ftel_autacq" )
    item23.Add( item25, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item26 = wx.StaticText( parent, ID_TEXT, "T.D.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item23.Add( item26, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item27 = TextCtrl( parent, ID_FTEL_AACQTD, "", wx.DefaultPosition, [40,-1], 0 )
    item27.SetName( "ftel_aacqtd" )
    item23.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item19.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item17.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17.AddGrowableRow( 1 )

    item3.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item28 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item29 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item31 = wx.StaticBox( parent, -1, "Gestione Numero documento" )
    item30 = wx.StaticBoxSizer( item31, wx.VERTICAL )
    
    item32 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item33 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item34 = wx.StaticText( parent, ID_TEXT, "Famiglia:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item34, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item35 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [50,-1], 0 )
    item35.SetName( "docfam" )
    item33.Add( item35, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item36 = wx.StaticText( parent, ID_TEXT, "Numeraz.esterna:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item36, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item37 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [50,-1], 0 )
    item37.SetName( "numest" )
    item33.Add( item37, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item38 = wx.StaticText( parent, ID_TEXT, "Personalizzazione:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item38, 0, wx.ALIGN_CENTER, 5 )

    item39 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item39.SetName( "custde" )
    item33.Add( item39, 0, wx.GROW|wx.LEFT|wx.RIGHT, 5 )

    item32.Add( item33, 0, wx.ALIGN_CENTER, 5 )

    item40 = wx.BoxSizer( wx.VERTICAL )
    
    item41 = CheckBox( parent, ID_CTRNUM, "Controlla", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.SetName( "ctrnum" )
    item40.Add( item41, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item42 = CheckBox( parent, ID_AGGNUM, "Aggiorna", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.SetName( "aggnum" )
    item40.Add( item42, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item43 = CheckBox( parent, ID_PIENUM, "Richiesta a piede", wx.DefaultPosition, wx.DefaultSize, 0 )
    item43.SetName( "pienum" )
    item40.Add( item43, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item44 = CheckBox( parent, ID_NONUMXMAG, "Non numerare x mag.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item44.SetName( "nonumxmag" )
    item40.Add( item44, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item32.Add( item40, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item30.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item29.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item46 = wx.StaticBox( parent, -1, "Dati da richiedere in testata" )
    item45 = wx.StaticBoxSizer( item46, wx.VERTICAL )
    
    item47 = wx.BoxSizer( wx.HORIZONTAL )
    
    item48 = CheckBox( parent, ID_ASKMAGAZZ, "Magazzino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item48.SetName( "askmagazz" )
    item47.Add( item48, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item49 = CheckBox( parent, ID_PDCDAMAG, "Usa sua anagrafica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item49.SetName( "pdcdamag" )
    item47.Add( item49, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item45.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item50 = wx.BoxSizer( wx.HORIZONTAL )
    
    item51 = CheckBox( parent, ID_ASKMODPAG, "Mod.pag.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item51.SetName( "askmodpag" )
    item50.Add( item51, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item52 = CheckBox( parent, ID_ASKBANCA, "Banca", wx.DefaultPosition, wx.DefaultSize, 0 )
    item52.SetName( "askbanca" )
    item50.Add( item52, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item53 = CheckBox( parent, ID_ASKMPNOEFF, "No effetti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item53.SetName( "askmpnoeff" )
    item50.Add( item53, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item45.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item54 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item55 = CheckBox( parent, ID_ASKDESTIN, "Destinaz.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.SetName( "askdestin" )
    item54.Add( item55, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item56 = CheckBox( parent, ID_ASKAGENTE, "Agente", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.SetName( "askagente" )
    item54.Add( item56, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item57 = CheckBox( parent, ID_ASKZONA, "Zona", wx.DefaultPosition, wx.DefaultSize, 0 )
    item57.SetName( "askzona" )
    item54.Add( item57, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item45.Add( item54, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item58 = wx.BoxSizer( wx.HORIZONTAL )
    
    item59 = CheckBox( parent, ID_ASKLISTINO, "Listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item59.SetName( "asklist" )
    item58.Add( item59, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item60 = CheckBox( parent, ID_ROWLISTINO, "Listino su ogni riga", wx.DefaultPosition, wx.DefaultSize, 0 )
    item60.SetName( "rowlist" )
    item58.Add( item60, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item45.Add( item58, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item29.Add( item45, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item62 = wx.StaticBox( parent, -1, "Totali" )
    item61 = wx.StaticBoxSizer( item62, wx.VERTICAL )
    
    item63 = CheckBox( parent, ID_TOTALI, "Mostra totali", wx.DefaultPosition, wx.DefaultSize, 0 )
    item63.SetName( "totali" )
    item61.Add( item63, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item64 = CheckBox( parent, ID_TOTZERO, "Accetta zero", wx.DefaultPosition, wx.DefaultSize, 0 )
    item64.SetName( "totzero" )
    item61.Add( item64, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item65 = CheckBox( parent, ID_TOTNEG, "Accetta negativo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item65.SetName( "totneg" )
    item61.Add( item65, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item29.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item28.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item28.AddGrowableCol( 0 )

    item28.AddGrowableRow( 1 )

    item2.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.AddGrowableRow( 1 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item66 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item67 = RadioBox( parent, ID_CLASDOC, "Classif. documento", wx.DefaultPosition, wx.DefaultSize, 
        ["Generico","Ordine a Fornitore","Carico da Fornitore","Reso a Fornitore","Ordine da Cliente","Vendita a Cliente","Reso da Cliente"] , 1, wx.RA_SPECIFY_COLS )
    item67.SetName( "clasdoc" )
    item66.Add( item67, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item69 = wx.StaticBox( parent, -1, "Dati di riferimento" )
    item68 = wx.StaticBoxSizer( item69, wx.VERTICAL )
    
    item70 = CheckBox( parent, ID_ASKRIFDESC, "Descrizione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item70.SetName( "askrifdesc" )
    item68.Add( item70, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item71 = CheckBox( parent, ID_ASKRIFNUM, "Numero", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.SetName( "askrifnum" )
    item68.Add( item71, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item72 = CheckBox( parent, ID_ASKRIFDATA, "Data", wx.DefaultPosition, wx.DefaultSize, 0 )
    item72.SetName( "askrifdata" )
    item68.Add( item72, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item66.Add( item68, 0, wx.GROW|wx.BOTTOM, 5 )

    item74 = wx.StaticBox( parent, -1, "Scontistiche" )
    item73 = wx.StaticBoxSizer( item74, wx.HORIZONTAL )
    
    item75 = wx.StaticText( parent, ID_TEXT, "Num.sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item73.Add( item75, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item76 = NumCtrl(parent, ID_NUMSCONTI, integerWidth=1, allowNegative=False, groupDigits=False); item76.SetName("numsconti")
    item73.Add( item76, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item66.Add( item73, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item66.AddGrowableRow( 2 )

    item1.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item77 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item78 = wx.StaticText( parent, ID_TEXT, "Utenti che possono accedere:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item78.SetForegroundColour( wx.BLUE )
    item77.Add( item78, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item79 = wx.Panel( parent, ID_PANGRIDPERM, wx.DefaultPosition, [200,160], wx.SUNKEN_BORDER )
    item79.SetName( "pangridperm" )
    item77.Add( item79, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item77.AddGrowableCol( 0 )

    item77.AddGrowableRow( 1 )

    item1.Add( item77, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 2 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item80 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item81 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item83 = wx.StaticBox( parent, -1, "Dati da proporre in testata" )
    item82 = wx.StaticBoxSizer( item83, wx.VERTICAL )
    
    item84 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item85 = wx.StaticText( parent, ID_TEXT, "Magazzino:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item84.Add( item85, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item86 = wx.StaticText( parent, ID_TEXT, "Mod.Pagamento:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item84.Add( item86, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item87 = LinkTable(parent, ID_MAGAZZ ); item87.SetDataLink( bt.TABNAME_MAGAZZ, "id_magazz", MagazzDialog )
    item84.Add( item87, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item88 = alib.LinkTableModPag(parent, ID_MODPAG, 'id_modpag')
    item84.Add( item88, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item84.AddGrowableCol( 0 )

    item84.AddGrowableCol( 1 )

    item82.Add( item84, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item81.Add( item82, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item90 = wx.StaticBox( parent, -1, "Generazione documento di trasferimento" )
    item89 = wx.StaticBoxSizer( item90, wx.VERTICAL )
    
    item91 = LinkTable(parent, ID_TDOCTRA ); item91.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_tdoctra", None )
    item89.Add( item91, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item81.Add( item89, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item81.AddGrowableCol( 0 )

    item80.Add( item81, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item92 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item93 = RadioBox( parent, ID_PROVVIG, "Provvigioni", wx.DefaultPosition, wx.DefaultSize, 
        ["No","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item93.SetName( "provvig" )
    item92.Add( item93, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item95 = wx.StaticBox( parent, -1, "Etichette" )
    item94 = wx.StaticBoxSizer( item95, wx.VERTICAL )
    
    item96 = CheckBox( parent, ID_STETIC, "Stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item96.SetName( "printetic" )
    item94.Add( item96, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item92.Add( item94, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item92.AddGrowableRow( 1 )

    item80.Add( item92, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item98 = wx.StaticBox( parent, -1, "Stampa" )
    item97 = wx.StaticBoxSizer( item98, wx.VERTICAL )
    
    item99 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item100 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item101 = wx.StaticText( parent, ID_TEXT, "Report:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item100.Add( item101, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item102 = TextCtrl_LC( parent, ID_TOOLPRINT, "", wx.DefaultPosition, [80,-1], 0 )
    item102.SetName( "toolprint" )
    item100.Add( item102, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item103 = wx.StaticText( parent, ID_TEXT, "Ft.PA:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item100.Add( item103, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item104 = TextCtrl_LC( parent, ID_FTEL_LAYOUT, "", wx.DefaultPosition, [80,-1], 0 )
    item104.SetName( "ftel_layout" )
    item100.Add( item104, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item99.Add( item100, 0, wx.ALIGN_CENTER, 5 )

    item105 = wx.StaticText( parent, ID_TEXT, "Num./", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item99.Add( item105, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item106 = TextCtrl( parent, ID_TOOLBARRA, "", wx.DefaultPosition, [20,-1], 0 )
    item106.SetName( "toolbarra" )
    item99.Add( item106, 0, wx.LEFT|wx.BOTTOM, 5 )

    item107 = wx.StaticText( parent, ID_TEXT, "Stampante:", wx.DefaultPosition, [70,20], wx.ALIGN_RIGHT )
    item99.Add( item107, 0, wx.ALIGN_RIGHT|wx.TOP, 5 )

    item108 = PrintersComboBox( parent, ID_COMBO, "", wx.DefaultPosition, wx.DefaultSize, [], wx.CB_DROPDOWN|wx.CB_READONLY )
    item108.SetName( "printer" )
    item99.Add( item108, 0, wx.LEFT|wx.RIGHT, 5 )

    item109 = wx.StaticText( parent, ID_TEXT, "Copie:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item99.Add( item109, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item110 = NumCtrl(parent, ID_COPIES, integerWidth=3, allowNegative=False, groupDigits=False); item110.SetName("copies")
    item99.Add( item110, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.BOTTOM, 5 )

    item99.AddGrowableCol( 5 )

    item97.Add( item99, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item111 = wx.FlexGridSizer( 0, 4, 0, 0 )
    
    item112 = CheckBox( parent, ID_STAINTEST, "Stampa dati azienda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item112.SetName( "staintest" )
    item111.Add( item112, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item113 = CheckBox( parent, ID_ASKSTAINT, "Chiedi stampa intestazioni", wx.DefaultPosition, wx.DefaultSize, 0 )
    item113.SetName( "askstaint" )
    item111.Add( item113, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item114 = CheckBox( parent, ID_STAOBB, "Obbligatoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item114.SetName( "staobb" )
    item111.Add( item114, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item111.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER, 5 )

    item115 = CheckBox( parent, ID_STALOGO, "Stampa logo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item115.SetName( "stalogo" )
    item111.Add( item115, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item116 = CheckBox( parent, ID_ASKSTAPRE, "Chiedi stampa prezzi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item116.SetName( "askstapre" )
    item111.Add( item116, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item117 = CheckBox( parent, ID_STANOC, "Non contabile", wx.DefaultPosition, wx.DefaultSize, 0 )
    item117.SetName( "stanoc" )
    item111.Add( item117, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item118 = CheckBox( parent, ID_DOCEMAIL, "Invia email", wx.DefaultPosition, wx.DefaultSize, 0 )
    item118.SetName( "docemail" )
    item111.Add( item118, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item119 = CheckBox( parent, ID_AANOTEDOC, "Non copiare note anag.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item119.SetName( "aanotedoc" )
    item111.Add( item119, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item97.Add( item111, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item80.Add( item97, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item80.AddGrowableCol( 0 )

    item0.Add( item80, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_COLCG = 16053
ID_NOIVAPROF = 16054
ID_CTRCAUCON = 16055
ID_SCORPIVA = 16056
ID_SOGRITACC = 16057
ID_CTRPDCRITACC = 16058
ID_SOGSCODOC = 16059
ID_CTRPDCSCODOC = 16060
ID_ASKPROTIVA = 16061
ID_AUTOQTAONBC = 16062
ID_RPTCOLLI = 16063
ID_DESEVARIF = 16064
ID_CTRACQDOC1 = 16065
ID_TIPACQ1 = 16066
ID_COPYDOC1 = 16067
ID_EVADOC1 = 16068
ID_ACQDOC1 = 16069
ID_ANNACQ1 = 16070
ID_CHECKACQ1 = 16071
ID_CTRACQDOC2 = 16072
ID_TIPACQ2 = 16073
ID_COPYDOC2 = 16074
ID_EVADOC2 = 16075
ID_ACQDOC2 = 16076
ID_ANNACQ2 = 16077
ID_CHECKACQ2 = 16078
ID_CTRACQDOC3 = 16079
ID_TIPACQ3 = 16080
ID_COPYDOC3 = 16081
ID_EVADOC3 = 16082
ID_ACQDOC3 = 16083
ID_ANNACQ3 = 16084
ID_CHECKACQ3 = 16085
ID_CTRACQDOC4 = 16086
ID_TIPACQ4 = 16087
ID_COPYDOC4 = 16088
ID_EVADOC4 = 16089
ID_ACQDOC4 = 16090
ID_ANNACQ4 = 16091
ID_CHECKACQ4 = 16092
ID_CHECKFIDO = 16093
ID_VISLISTINI = 16094
ID_VISCOSTO = 16095
ID_VISGIAC = 16096
ID_VISULTMOV = 16097
ID_ULTMOVBEF = 16098
ID_VISMARGINE = 16099
ID_ASKDATIACC = 16100
ID_TRAKGC = 16101
ID_TRACAU = 16102
ID_TRAASP = 16103
ID_TRACUR = 16104
ID_TRAPOR = 16105
ID_TRAVET = 16106
ID_TRACON = 16107

def Doc2Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item5 = wx.StaticBox( parent, -1, "Collegamento contabile" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )
    
    item6 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item7 = ColCgCheckBox( parent, ID_COLCG, "Contabilizza su:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetName( "colcg" )
    item6.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item8 = AccorpaIvaCheckBox( parent, ID_NOIVAPROF, "Accorpa IVA se causale composta", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "noivaprof" )
    item6.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.AddGrowableCol( 1 )

    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = LinkTableCauContab(parent, ID_CTRCAUCON, "id_caucg")
    item4.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item3.Add( item4, 0, wx.GROW|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item10 = RadioBox( parent, ID_SCORPIVA, "Gli importi sono:", wx.DefaultPosition, wx.DefaultSize, 
        ["Imponibili: l'IVA sarà aggiunta","Ivati: l'IVA sarà scorporata"] , 1, wx.RA_SPECIFY_COLS )
    item10.SetName( "scorpiva" )
    item3.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item3.AddGrowableCol( 0 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item13 = wx.StaticBox( parent, -1, "Gestione Ritenuta d'Acconto" )
    item12 = wx.StaticBoxSizer( item13, wx.VERTICAL )
    
    item14 = RitAccCheckBox( parent, ID_SOGRITACC, "Attiva e contabilizza su:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.SetName( "sogritacc" )
    item12.Add( item14, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = LinkTablePdc(parent, ID_CTRPDCRITACC, "id_pdc_ra")
    item12.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11.Add( item12, 0, wx.GROW|wx.LEFT, 5 )

    item17 = wx.StaticBox( parent, -1, "Gestione Sconto Esterno" )
    item16 = wx.StaticBoxSizer( item17, wx.VERTICAL )
    
    item18 = ScoDocCheckBox( parent, ID_SOGSCODOC, "Attiva e contabilizza su:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetName( "sogscodoc" )
    item16.Add( item18, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item19 = LinkTablePdc(parent, ID_CTRPDCSCODOC, "id_pdc_sd")
    item16.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11.Add( item16, 0, wx.GROW|wx.LEFT|wx.RIGHT, 5 )

    item11.AddGrowableCol( 0 )

    item11.AddGrowableCol( 1 )

    item2.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.AddGrowableCol( 0 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item20 = RadioBox( parent, ID_ASKPROTIVA, "Protocollo IVA", wx.DefaultPosition, wx.DefaultSize, 
        ["Non richiesto","Proposto zero","Proposto numero documento","Proposto da registro IVA"] , 1, wx.RA_SPECIFY_COLS )
    item20.SetName( "askprotiva" )
    item1.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item21 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item23 = wx.StaticBox( parent, -1, "Barcode" )
    item22 = wx.StaticBoxSizer( item23, wx.VERTICAL )
    
    item24 = CheckBox( parent, ID_AUTOQTAONBC, "Auto qta = 1", wx.DefaultPosition, wx.DefaultSize, 0 )
    item24.SetName( "autoqtaonbc" )
    item22.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item21.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item26 = wx.StaticBox( parent, -1, "Segnacolli" )
    item25 = wx.StaticBoxSizer( item26, wx.VERTICAL )
    
    item27 = CheckBox( parent, ID_RPTCOLLI, "Attiva stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.SetName( "rptcolli" )
    item25.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item21.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item29 = wx.StaticBox( parent, -1, "Evasione doc." )
    item28 = wx.StaticBoxSizer( item29, wx.VERTICAL )
    
    item30 = CheckBox( parent, ID_DESEVARIF, "Usa dati rif.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.SetName( "desevarif" )
    item28.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item21.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item21.AddGrowableRow( 2 )

    item1.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item31 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item33 = wx.StaticBox( parent, -1, "Acquisizione ed evazione altri documenti" )
    item32 = wx.StaticBoxSizer( item33, wx.VERTICAL )
    
    item34 = wx.FlexGridSizer( 0, 6, 0, 0 )
    
    item35 = wx.StaticText( parent, ID_TEXT, "Documento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item34.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item36 = wx.StaticText( parent, ID_TEXT, "Copia", wx.DefaultPosition, [30,-1], 0 )
    item34.Add( item36, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item37 = wx.StaticText( parent, ID_TEXT, "Evadi", wx.DefaultPosition, [30,-1], 0 )
    item34.Add( item37, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item38 = wx.StaticText( parent, ID_TEXT, "Acquis", wx.DefaultPosition, [30,-1], 0 )
    item34.Add( item38, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item39 = wx.StaticText( parent, ID_TEXT, "Annul", wx.DefaultPosition, [30,-1], 0 )
    item34.Add( item39, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item40 = wx.StaticText( parent, ID_TEXT, "Check", wx.DefaultPosition, [30,-1], 0 )
    item34.Add( item40, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item41 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item42 = LinkTable(parent, ID_CTRACQDOC1 ); item42.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_acqdoc1", None )
    item41.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item43 = TextCtrl(parent, ID_TIPACQ1); item43.SetName('tipacq1'); item43.Show(False)
    item41.Add( item43, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item41.AddGrowableCol( 0 )

    item34.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item44 = CheckBox( parent, ID_COPYDOC1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item44.SetName( "_copydoc1" )
    item34.Add( item44, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item45 = CheckBox( parent, ID_EVADOC1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.SetName( "_evadoc1" )
    item34.Add( item45, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item46 = CheckBox( parent, ID_ACQDOC1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item46.SetName( "_acqdoc1" )
    item34.Add( item46, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item47 = CheckBox( parent, ID_ANNACQ1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item47.SetName( "annacq1" )
    item34.Add( item47, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item48 = CheckBox( parent, ID_CHECKACQ1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item48.SetName( "checkacq1" )
    item34.Add( item48, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item49 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item50 = LinkTable(parent, ID_CTRACQDOC2 ); item50.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_acqdoc2", None )
    item49.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item51 = TextCtrl(parent, ID_TIPACQ2); item51.SetName('tipacq2'); item51.Show(False)
    item49.Add( item51, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item49.AddGrowableCol( 0 )

    item34.Add( item49, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52 = CheckBox( parent, ID_COPYDOC2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item52.SetName( "_copydoc2" )
    item34.Add( item52, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item53 = CheckBox( parent, ID_EVADOC2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item53.SetName( "_evadoc2" )
    item34.Add( item53, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item54 = CheckBox( parent, ID_ACQDOC2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item54.SetName( "_acqdoc2" )
    item34.Add( item54, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item55 = CheckBox( parent, ID_ANNACQ2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.SetName( "annacq2" )
    item34.Add( item55, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item56 = CheckBox( parent, ID_CHECKACQ2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.SetName( "checkacq2" )
    item34.Add( item56, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item57 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item58 = LinkTable(parent, ID_CTRACQDOC3 ); item58.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_acqdoc3", None )
    item57.Add( item58, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item59 = TextCtrl(parent, ID_TIPACQ3); item59.SetName('tipacq3'); item59.Show(False)
    item57.Add( item59, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item57.AddGrowableCol( 0 )

    item34.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item60 = CheckBox( parent, ID_COPYDOC3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item60.SetName( "_copydoc3" )
    item34.Add( item60, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item61 = CheckBox( parent, ID_EVADOC3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.SetName( "_evadoc3" )
    item34.Add( item61, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item62 = CheckBox( parent, ID_ACQDOC3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item62.SetName( "_acqdoc3" )
    item34.Add( item62, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item63 = CheckBox( parent, ID_ANNACQ3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item63.SetName( "annacq3" )
    item34.Add( item63, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item64 = CheckBox( parent, ID_CHECKACQ3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item64.SetName( "checkacq3" )
    item34.Add( item64, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item65 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item66 = LinkTable(parent, ID_CTRACQDOC4 ); item66.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_acqdoc4", None )
    item65.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item67 = TextCtrl(parent, ID_TIPACQ4); item67.SetName('tipacq4'); item67.Show(False)
    item65.Add( item67, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item65.AddGrowableCol( 0 )

    item34.Add( item65, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item68 = CheckBox( parent, ID_COPYDOC4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item68.SetName( "_copydoc4" )
    item34.Add( item68, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item69 = CheckBox( parent, ID_EVADOC4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item69.SetName( "_evadoc4" )
    item34.Add( item69, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item70 = CheckBox( parent, ID_ACQDOC4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item70.SetName( "_acqdoc4" )
    item34.Add( item70, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item71 = CheckBox( parent, ID_ANNACQ4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.SetName( "annacq4" )
    item34.Add( item71, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item72 = CheckBox( parent, ID_CHECKACQ4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item72.SetName( "checkacq4" )
    item34.Add( item72, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item34.AddGrowableCol( 0 )

    item32.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item31.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item73 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item75 = wx.StaticBox( parent, -1, "Fido cliente" )
    item74 = wx.StaticBoxSizer( item75, wx.VERTICAL )
    
    item76 = CheckBox( parent, ID_CHECKFIDO, "Doc. sottoposto a controllo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item76.SetName( "checkfido" )
    item74.Add( item76, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item73.Add( item74, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item78 = wx.StaticBox( parent, -1, "Del prodotto, visualizza:" )
    item77 = wx.StaticBoxSizer( item78, wx.VERTICAL )
    
    item79 = CheckBox( parent, ID_VISLISTINI, "Dati e listini in vigore", wx.DefaultPosition, wx.DefaultSize, 0 )
    item79.SetName( "vislistini" )
    item77.Add( item79, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item80 = wx.BoxSizer( wx.HORIZONTAL )
    
    item81 = CheckBox( parent, ID_VISCOSTO, "Costo U.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item81.SetName( "viscosto" )
    item80.Add( item81, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item82 = CheckBox( parent, ID_VISGIAC, "Giacenza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item82.SetName( "visgiac" )
    item80.Add( item82, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item77.Add( item80, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item83 = wx.BoxSizer( wx.HORIZONTAL )
    
    item84 = CheckBox( parent, ID_VISULTMOV, "Movim. anag.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item84.SetName( "visultmov" )
    item83.Add( item84, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item85 = CheckBox( parent, ID_ULTMOVBEF, "Dai priorità", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.SetToolTip( wx.ToolTip("Se attivato, rende prioritaria la visualizzazione dei movimenti rispetto ai dati del prodotto") )
    item85.SetName( "ultmovbef" )
    item83.Add( item85, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item77.Add( item83, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item73.Add( item77, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item87 = wx.StaticBox( parent, -1, "Margine vendita" )
    item86 = wx.StaticBoxSizer( item87, wx.VERTICAL )
    
    item88 = CheckBox( parent, ID_VISMARGINE, "Visualizza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item88.SetName( "vismargine" )
    item86.Add( item88, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item73.Add( item86, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item73.AddGrowableRow( 2 )

    item31.Add( item73, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item31.AddGrowableCol( 0 )

    item0.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item90 = wx.StaticBox( parent, -1, "Dati accompagnatori richiesti" )
    item89 = wx.StaticBoxSizer( item90, wx.VERTICAL )
    
    item91 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item92 = CheckBox( parent, ID_ASKDATIACC, "Attiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item92.SetName( "askdatiacc" )
    item91.Add( item92, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item93 = RCheckBox( parent, ID_TRAKGC, "Peso e colli", wx.DefaultPosition, wx.DefaultSize, 0 )
    item93.SetName( "asktrakgc" )
    item91.Add( item93, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item89.Add( item91, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item94 = wx.FlexGridSizer( 0, 4, 0, 0 )
    
    item95 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item94.Add( item95, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item96 = wx.StaticText( parent, ID_TEXT, "Valore di default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item94.Add( item96, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item97 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item94.Add( item97, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item98 = wx.StaticText( parent, ID_TEXT, "Valore di default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item94.Add( item98, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item99 = RCheckBox( parent, ID_TRACAU, "Causale trasporto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item99.SetName( "asktracau" )
    item94.Add( item99, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item100 = LinkTable(parent, ID_TRACAU ); item100.SetDataLink( bt.TABNAME_TRACAU, "id_tracau", TraCauDialog )
    item94.Add( item100, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item101 = RCheckBox( parent, ID_TRAASP, "Aspetto esteriore beni", wx.DefaultPosition, wx.DefaultSize, 0 )
    item101.SetName( "asktraasp" )
    item94.Add( item101, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item102 = LinkTable(parent, ID_TRAASP ); item102.SetDataLink( bt.TABNAME_TRAASP, "id_traasp", TraAspDialog )
    item94.Add( item102, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item103 = RCheckBox( parent, ID_TRACUR, "Trasporto a cura", wx.DefaultPosition, wx.DefaultSize, 0 )
    item103.SetName( "asktracur" )
    item94.Add( item103, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item104 = LinkTable(parent, ID_TRACUR ); item104.SetDataLink( bt.TABNAME_TRACUR, "id_tracur", TraCurDialog )
    item94.Add( item104, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item105 = RCheckBox( parent, ID_TRAPOR, "Porto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item105.SetName( "asktrapor" )
    item94.Add( item105, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item106 = LinkTable(parent, ID_TRAPOR ); item106.SetDataLink( bt.TABNAME_TRAPOR, "id_trapor", TraPorDialog )
    item94.Add( item106, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item107 = RCheckBox( parent, ID_TRAVET, "Vettore", wx.DefaultPosition, wx.DefaultSize, 0 )
    item107.SetName( "asktravet" )
    item94.Add( item107, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item108 = LinkTable(parent, ID_TRAVET ); item108.SetDataLink( bt.TABNAME_TRAVET, "id_travet", TraVetDialog )
    item94.Add( item108, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item109 = RCheckBox( parent, ID_TRACON, "Contrassegno", wx.DefaultPosition, wx.DefaultSize, 0 )
    item109.SetName( "asktracon" )
    item94.Add( item109, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item110 = LinkTable(parent, ID_TRACON ); item110.SetDataLink( bt.TABNAME_TRACON, "id_tracon", TraConDialog )
    item94.Add( item110, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item94.AddGrowableCol( 1 )

    item94.AddGrowableCol( 3 )

    item89.Add( item94, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item89, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANGRIDMOV = 16108
ID_BUTNEWMOV = 16109
ID_BUTDELMOV = 16110
ID_MOVBOOK = 16111

def MovFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.Panel( parent, ID_PANGRIDMOV, wx.DefaultPosition, wx.DefaultSize, wx.SUNKEN_BORDER )
    item1.Add( item2, 0, wx.GROW|wx.ALL, 5 )

    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = wx.Button( parent, ID_BUTNEWMOV, "Nuovo movimento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item5 = wx.Button( parent, ID_BUTDELMOV, "Elimina movimento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableRow( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7 = MovNotebook( parent, ID_MOVBOOK, wx.DefaultPosition, [200,160], 0 )
    item6 = item7
    
    item8 = wx.Panel( item7, -1 )
    Mov1Func(item8, False)
    item7.AddPage( item8, "Definizione movimento" )

    item9 = wx.Panel( item7, -1 )
    Mov2Func(item9, False)
    item7.AddPage( item9, "Progressivi" )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TIPOLOGIA = 16112
ID_LENDESCRIZ = 16113
ID_ASKVALORI = 16114
ID_CANPREZZO0 = 16115
ID_TIPVALUNI = 16116
ID_TIPSCONTI = 16117
ID_AGGCOSTO = 16118
ID_AGGPREZZO = 16119
ID_MODIMPRICALC = 16120
ID_AGGGRP = 16121
ID_RICCOSTO = 16122
ID_CHECKBOX = 16123
ID_AGGFORNIT = 16124
ID_ACQPDT = 16125
ID_NOMASTROPROD = 16126
ID_PROOBB = 16127
ID_NOPROVVIG = 16128
ID_LABELPDC = 16129
ID_CTRPDC = 16130
ID_PDCRESET = 16131
ID_ISACCONTO = 16132
ID_ISACCSTOR = 16133
ID_ACC_SEPIVA = 16134
ID_PRTDESTOT = 16135

def Mov1Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = RadioBox( parent, ID_TIPOLOGIA, "Tipologia", wx.DefaultPosition, wx.DefaultSize, 
        ["Descrizione","Merce","Servizi","Spese","Trasporto","Sc. ripart.","Sc. merce","Omaggio","Aum.Prezzi"] , 1, wx.RA_SPECIFY_COLS )
    item3.SetName( "tipologia" )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item5 = wx.StaticBox( parent, -1, "Descrizione" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )
    
    item6 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "#Caratteri", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item8 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item9 = wx.StaticText( parent, ID_TEXT, "max:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item10 = NumCtrl(parent, ID_LENDESCRIZ, integerWidth=4, allowNegative=False, groupDigits=False); item10.SetName("lendescriz")
    item8.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.AddGrowableCol( 0 )

    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item2.AddGrowableRow( 1 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item12 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item13 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item14 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item15 = RadioBox( parent, ID_ASKVALORI, "Valori richiesti", wx.DefaultPosition, wx.DefaultSize, 
        ["Solo qtà","Qtà, prezzo","Solo importo","Nulla"] , 1, wx.RA_SPECIFY_COLS )
    item15.SetName( "askvalori" )
    item14.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.StaticBox( parent, -1, "Richiesta prezzo" )
    item16 = wx.StaticBoxSizer( item17, wx.VERTICAL )
    
    item18 = CheckBox( parent, ID_CANPREZZO0, "Permetti 0", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetName( "canprezzo0" )
    item16.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item13.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item19 = RadioBox( parent, ID_TIPVALUNI, "Prop.Prezzo", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Costo","Prezzo","Listino"] , 1, wx.RA_SPECIFY_COLS )
    item19.SetName( "tipvaluni" )
    item13.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item20 = RadioBox( parent, ID_TIPSCONTI, "Prop.Sconti", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Da prodotto","Da cliente","Da griglia","Da gruppo prezzi"] , 1, wx.RA_SPECIFY_COLS )
    item20.SetName( "tipsconti" )
    item13.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item21 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item22 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item23 = RadioBox( parent, ID_AGGCOSTO, "Aggiorna costo", wx.DefaultPosition, wx.DefaultSize, 
        ["No","Da val. unitario","Da tot. riga"] , 1, wx.RA_SPECIFY_COLS )
    item23.SetName( "aggcosto" )
    item22.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item24 = RadioBox( parent, ID_AGGPREZZO, "Aggiorna prezzo", wx.DefaultPosition, wx.DefaultSize, 
        ["No","Da val. unitario","Da tot. riga"] , 1, wx.RA_SPECIFY_COLS )
    item24.SetName( "aggprezzo" )
    item22.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item21.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item25 = RadioBox( parent, ID_MODIMPRICALC, "La modifica dell'importo ricalcola:", wx.DefaultPosition, wx.DefaultSize, 
        ["Gli sconti (standard)","La quantità","Il prezzo"] , 1, wx.RA_SPECIFY_COLS )
    item25.SetName( "modimpricalc" )
    item21.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item13.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = RadioBox( parent, ID_AGGGRP, "Aggiorna griglie", wx.DefaultPosition, wx.DefaultSize, 
        ["No","Aggiorna più recente","Crea nuova griglia"] , 1, wx.RA_SPECIFY_COLS )
    item26.SetName( "agggrip" )
    item13.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item13.AddGrowableCol( 0 )

    item13.AddGrowableCol( 1 )

    item13.AddGrowableCol( 2 )

    item12.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item27 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item29 = wx.StaticBox( parent, -1, "Ricalcoli" )
    item28 = wx.StaticBoxSizer( item29, wx.VERTICAL )
    
    item30 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item31 = CheckBox( parent, ID_RICCOSTO, "Ricalcola il costo di acquisto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.SetName( "riccosto" )
    item30.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item32 = RCheckBox( parent, ID_CHECKBOX, "Usa sconti riga", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetName( "riccostosr" )
    item30.Add( item32, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item30.AddGrowableCol( 1 )

    item28.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item33 = CheckBox( parent, ID_RICCOSTO, "Ricalcola il prezzo al pubblico", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.SetName( "ricprezzo" )
    item28.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item34 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item35 = CheckBox( parent, ID_RICCOSTO, "Ricalcola i listini di vendita", wx.DefaultPosition, wx.DefaultSize, 0 )
    item35.SetName( "riclist" )
    item34.Add( item35, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item36 = wx.StaticText( parent, ID_TEXT, "-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item34.Add( item36, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item37 = RCheckBox( parent, ID_CHECKBOX, "Sempre nuovi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.SetName( "newlist" )
    item34.Add( item37, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item34.AddGrowableCol( 0 )

    item34.AddGrowableCol( 2 )

    item28.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item27.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item39 = wx.StaticBox( parent, -1, "Varie" )
    item38 = wx.StaticBoxSizer( item39, wx.VERTICAL )
    
    item40 = CheckBox( parent, ID_AGGFORNIT, "Aggiorna fornitore prodotto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.SetName( "aggfornit" )
    item38.Add( item40, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item41 = CheckBox( parent, ID_ACQPDT, "Attiva collegamento a PDT", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.SetName( "f_acqpdt" )
    item38.Add( item41, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item42 = CheckBox( parent, ID_NOMASTROPROD, "Escludi in mastro prodotto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.SetName( "nomastroprod" )
    item38.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item27.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item44 = wx.StaticBox( parent, -1, "Provvigioni agenti" )
    item43 = wx.StaticBoxSizer( item44, wx.VERTICAL )
    
    item45 = CheckBox( parent, ID_PROOBB, "Provvigione obbligatoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.SetName( "proobb" )
    item43.Add( item45, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item46 = CheckBox( parent, ID_NOPROVVIG, "Escludi dal calcolo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item46.SetName( "noprovvig" )
    item43.Add( item46, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item27.Add( item43, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item27.AddGrowableCol( 1 )

    item27.AddGrowableCol( 2 )

    item12.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item49 = wx.StaticBox( parent, -1, "Collegamento contabile" )
    item48 = wx.StaticBoxSizer( item49, wx.VERTICAL )
    
    item50 = wx.StaticText( parent, ID_LABELPDC, "Sottoconto su cui contabilizzare le righe:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item48.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item51 = LinkTable(parent, ID_CTRPDC ); item51.SetDataLink( bt.TABNAME_PDC, "id_pdc", PdcDialog )
    item48.Add( item51, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52 = CheckBox( parent, ID_PDCRESET, "Resetta in inserimento righe evase da altro documento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item52.SetName( "pdcreset" )
    item48.Add( item52, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item47.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item54 = wx.StaticBox( parent, -1, "Acconti" )
    item53 = wx.StaticBoxSizer( item54, wx.VERTICAL )
    
    item55 = CheckBox( parent, ID_ISACCONTO, "E' un acconto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.SetName( "is_acconto" )
    item53.Add( item55, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item56 = CheckBox( parent, ID_ISACCSTOR, "E' uno storno", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.SetName( "is_accstor" )
    item53.Add( item56, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item57 = CheckBox( parent, ID_ACC_SEPIVA, "Separa Tot.IVA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item57.SetName( "acc_sepiva" )
    item53.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47.Add( item53, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item59 = wx.StaticBox( parent, -1, "Tot.IVA (semplif.)" )
    item58 = wx.StaticBoxSizer( item59, wx.VERTICAL )
    
    item60 = wx.StaticText( parent, ID_LABELPDC, "Descrizione del totale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item58.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item61 = TextCtrl( parent, ID_PRTDESTOT, "", wx.DefaultPosition, [80,-1], 0 )
    item61.SetName( "prtdestot" )
    item58.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47.Add( item58, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item63 = wx.StaticBox( parent, -1, "Totalizza Qta per:" )
    item62 = wx.StaticBoxSizer( item63, wx.VERTICAL )
    
    item64 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item65 = CheckBox( parent, ID_CHECKBOX, "Tot. Peso KG", wx.DefaultPosition, wx.DefaultSize, 0 )
    item65.SetName( "tqtaxpeso" )
    item64.Add( item65, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item66 = CheckBox( parent, ID_CHECKBOX, "Tot. Colli", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.SetName( "tqtaxcolli" )
    item64.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item64.AddGrowableCol( 0 )

    item62.Add( item64, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47.Add( item62, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item47.AddGrowableCol( 0 )

    item12.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item12.AddGrowableCol( 0 )

    item12.AddGrowableRow( 1 )

    item11.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11.AddGrowableCol( 0 )

    item11.AddGrowableCol( 1 )

    item1.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TXTEMAIL = 16136

def Doc3Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Testo da includere nella email, quando spedita, come corpo del messaggio.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.TextCtrl( parent, ID_TXTEMAIL, "", wx.DefaultPosition, wx.DefaultSize, wx.TE_MULTILINE )
    item2.SetName( "txtemail" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_AGGINI = 16137
ID_AGGINIV = 16138
ID_AGGCAR = 16139
ID_AGGCARV = 16140
ID_AGGSCA = 16141
ID_AGGSCAV = 16142
ID_AGGORDFOR = 16143
ID_AGGORDCLI = 16144
ID_AGGCVCCAR = 16145
ID_AGGCVCSCA = 16146
ID_AGGCVFCAR = 16147
ID_AGGCVFSCA = 16148
ID_STATFTCLI = 16149
ID_STATCSCLI = 16150
ID_MANCOSTO = 16151
ID_STATFTFOR = 16152

def Mov2Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Inventario", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetBackgroundColour( wx.LIGHT_GREY )
    item3.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item5 = RadioBox( parent, ID_AGGINI, "Giacenza iniziale", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item5.SetName( "aggini" )
    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item6 = RadioBox( parent, ID_AGGINIV, "Valore giac.iniziale", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item6.SetName( "agginiv" )
    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item4.AddGrowableCol( 1 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item7 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item8 = RadioBox( parent, ID_AGGCAR, "Carichi", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item8.SetName( "aggcar" )
    item7.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = RadioBox( parent, ID_AGGCARV, "Valore carichi", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item9.SetName( "aggcarv" )
    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item7.AddGrowableCol( 1 )

    item2.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item10 = CheckBox( parent, ID_CHECKBOX, "Aggiorna data/num. ultimo carico", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "aggultcar" )
    item2.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item12 = RadioBox( parent, ID_AGGSCA, "Scarichi", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item12.SetName( "aggsca" )
    item11.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item13 = RadioBox( parent, ID_AGGSCAV, "Valore scarichi", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item13.SetName( "aggscav" )
    item11.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item11.AddGrowableCol( 1 )

    item2.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item2.AddGrowableCol( 0 )

    item2.AddGrowableRow( 1 )

    item2.AddGrowableRow( 2 )

    item2.AddGrowableRow( 3 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item14 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item15 = wx.StaticText( parent, ID_TEXT, "Ordini", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetBackgroundColour( wx.LIGHT_GREY )
    item15.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item14.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item16 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item17 = RadioBox( parent, ID_AGGORDFOR, "Ordini a fornitore", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item17.SetName( "aggordfor" )
    item16.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item18 = RadioBox( parent, ID_AGGORDCLI, "Ordini da cliente", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item18.SetName( "aggordcli" )
    item16.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item16.AddGrowableCol( 1 )

    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item19 = wx.StaticText( parent, ID_TEXT, "Conto Vendita", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetBackgroundColour( wx.LIGHT_GREY )
    item19.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item14.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item20 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item21 = RadioBox( parent, ID_AGGCVCCAR, "Car. C/V Clienti", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item21.SetName( "aggcvccar" )
    item20.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item22 = RadioBox( parent, ID_AGGCVCSCA, "Scar. C/V Clienti", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item22.SetName( "aggcvcsca" )
    item20.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item20.AddGrowableCol( 1 )

    item14.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item23 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item24 = RadioBox( parent, ID_AGGCVFCAR, "Car. C/V Fornit.", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item24.SetName( "aggcvfcar" )
    item23.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item25 = RadioBox( parent, ID_AGGCVFSCA, "Scar. C/V Fornit.", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item25.SetName( "aggcvfsca" )
    item23.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item23.AddGrowableCol( 1 )

    item14.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item14.AddGrowableCol( 0 )

    item14.AddGrowableRow( 1 )

    item14.AddGrowableRow( 3 )

    item14.AddGrowableRow( 4 )

    item1.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item27 = wx.StaticText( parent, ID_TEXT, "Valori statistici", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.SetBackgroundColour( wx.LIGHT_GREY )
    item27.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item26.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item28 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item29 = RadioBox( parent, ID_STATFTCLI, "Fatt.clienti: Vendita", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item29.SetName( "statftcli" )
    item28.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item30 = RadioBox( parent, ID_STATCSCLI, "Fatt.clienti: Costo", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item30.SetName( "statcscli" )
    item28.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item28.AddGrowableCol( 1 )

    item28.AddGrowableCol( 2 )

    item26.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item31 = RadioBox( parent, ID_MANCOSTO, "Valore costo riga", wx.DefaultPosition, wx.DefaultSize, 
        ["Nascondi","Visualizza","Modifica"] , 1, wx.RA_SPECIFY_ROWS )
    item31.SetName( "mancosto" )
    item26.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item32 = RadioBox( parent, ID_STATFTFOR, "Fatturato fornitori", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item32.SetName( "statftfor" )
    item26.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item26.AddGrowableCol( 0 )

    item1.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableCol( 1 )

    item1.AddGrowableCol( 2 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
