# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: caumagazz.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from anag.basetab import AnagCardPanel

from awc.controls.textctrl import TextCtrl, TextCtrl_LC
from awc.controls.numctrl import NumCtrl
from awc.controls.radiobox import RadioBox
from awc.controls.checkbox import CheckBox
from awc.controls.linktable import LinkTable
from awc.controls.dbgrid import DbGrid
from awc.controls.entries import PrintersComboBox
from awc.controls.notebook import Notebook

from anag.pdctip import PdcTipDialog
from anag.pdc import PdcDialog
from cfg.caucontab import CauContabDialog
from anag.trasp import TraCauDialog, TraCurDialog, TraVetDialog, TraAspDialog, TraPorDialog, TraConDialog
from anag.mag import MagazzDialog

from anag.lib import LinkTableCauContab, LinkTablePdc
import anag.lib as alib

from Env import Azienda
bt = Azienda.BaseTab

class RCheckBox(CheckBox):
    def __init__(self, parent, id, label, pos, size, style):
        style = wx.ALIGN_RIGHT
        CheckBox.__init__(self, parent, id, label, pos, size, style)

class DocNotebook(Notebook):
    def __init__(self, *args, **kwargs):
        Notebook.__init__(self, *args, **kwargs)
        self.SetName('docbook')

class MovNotebook(Notebook):
    def __init__(self, *args, **kwargs):
        Notebook.__init__(self, *args, **kwargs)
        self.SetName('movbook')

class LinkedCheckBox(CheckBox):
    
    values = None
    linkname = None
    
    def __init__(self, *args, **kwargs):
        CheckBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=self.values)
        self.Bind(wx.EVT_CHECKBOX, self.OnChanged)
    
    def OnChanged(self, event):
        self.CheckChecked()
        event.Skip()
    
    def SetValue(self, *args, **kwargs):
        CheckBox.SetValue(self, *args, **kwargs)
        self.CheckChecked()
    
    def CheckChecked(self):
        self.GetParent().FindWindowByName(self.linkname).Enable(self.IsChecked())
    
class ColCgCheckBox(LinkedCheckBox):
    
    values = values={True: "X", False: " "}
    linkname = 'id_caucg'
    
class RitAccCheckBox(LinkedCheckBox):
    
    values = values={True: 1, False: 0}
    linkname = 'id_pdc_ra'


class AccorpaIvaCheckBox(RCheckBox):
    
    def __init__(self, *args, **kwargs):
        RCheckBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values={True:1, False: 0})


from cfg.caucontab_wdr import TipoDocumentoRadioBox as FTEL_TipoDocumentoRadioBox

# Window functions

ID_ANAGMAIN = 16000
ID_DOCBOOK = 16001

def CauMagazzCardFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = AnagCardPanel(parent, -1)
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = DocNotebook( parent, ID_DOCBOOK, wx.DefaultPosition, [200,160], 0 )
    item2 = item3
    
    item4 = wx.Panel( item3, -1 )
    Doc1Func(item4, False)
    item3.AddPage( item4, "Setup documento #1" )

    item5 = wx.Panel( item3, -1 )
    Doc2Func(item5, False)
    item3.AddPage( item5, "Setup documento #2" )

    item6 = wx.Panel( item3, -1 )
    MovFunc(item6, False)
    item3.AddPage( item6, "Setup movimenti" )

    item7 = wx.Panel( item3, -1 )
    Doc3Func(item7, False)
    item3.AddPage( item7, "Testo email" )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 16002
ID_DESCANAG = 16003
ID_CTRPDCTIP = 16004
ID_NUMDOC = 16005
ID_DATDOC = 16006
ID_RADIOBOX = 16007
ID_FTEL_NODDT = 16008
ID_TEXTCTRL = 16009
ID_CTRNUM = 16010
ID_AGGNUM = 16011
ID_PIENUM = 16012
ID_NONUMXMAG = 16013
ID_ASKMAGAZZ = 16014
ID_PDCDAMAG = 16015
ID_ASKMODPAG = 16016
ID_ASKBANCA = 16017
ID_ASKMPNOEFF = 16018
ID_ASKDESTIN = 16019
ID_ASKAGENTE = 16020
ID_ASKZONA = 16021
ID_ASKLISTINO = 16022
ID_ROWLISTINO = 16023
ID_TOTALI = 16024
ID_TOTZERO = 16025
ID_TOTNEG = 16026
ID_CLASDOC = 16027
ID_ASKRIFDESC = 16028
ID_ASKRIFNUM = 16029
ID_ASKRIFDATA = 16030
ID_NUMSCONTI = 16031
ID_PANGRIDPERM = 16032
ID_MAGAZZ = 16033
ID_MODPAG = 16034
ID_TDOCTRA = 16035
ID_PROVVIG = 16036
ID_STETIC = 16037
ID_TOOLPRINT = 16038
ID_FTEL_LAYOUT = 16039
ID_TOOLBARRA = 16040
ID_COMBO = 16041
ID_COPIES = 16042
ID_STAINTEST = 16043
ID_ASKSTAINT = 16044
ID_STAOBB = 16045
ID_STALOGO = 16046
ID_ASKSTAPRE = 16047
ID_STANOC = 16048
ID_DOCEMAIL = 16049
ID_AANOTEDOC = 16050

def Doc1Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item4 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item6 = wx.StaticBox( parent, -1, "" )
    item5 = wx.StaticBoxSizer( item6, wx.VERTICAL )
    
    item7 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item8 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item9 = wx.StaticText( parent, ID_TEXT, "Descrizione dell'anagrafica:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item10 = TextCtrl_LC( parent, ID_DESCANAG, "", wx.DefaultPosition, [140,-1], 0 )
    item10.SetName( "descanag" )
    item8.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item8.AddGrowableCol( 0 )

    item7.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item12 = wx.StaticText( parent, ID_TEXT, "Tipologia:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item11.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item13 = LinkTable(parent, ID_CTRPDCTIP ); item13.SetDataLink( bt.TABNAME_PDCTIP, "id_pdctip", PdcTipDialog )
    item11.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item11.AddGrowableCol( 0 )

    item7.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7.AddGrowableCol( 1 )

    item5.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item15 = RadioBox( parent, ID_NUMDOC, "Proposizione Numero documento", wx.DefaultPosition, wx.DefaultSize, 
        ["Zero","Da setup documento/famiglia","Da protocollo IVA","Da documenti/famiglia a piede"] , 1, wx.RA_SPECIFY_COLS )
    item15.SetName( "numdoc" )
    item14.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item16 = RadioBox( parent, ID_DATDOC, "Gestione Data documento", wx.DefaultPosition, wx.DefaultSize, 
        ["Nessuna gestione (data vuota)","Proposta data nulla","Proposta data registrazione","Proposta ultima data documento/famiglia","Non richiesta (=data registrazione)"] , 1, wx.RA_SPECIFY_COLS )
    item16.SetName( "datdoc" )
    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item14.AddGrowableCol( 0 )

    item14.AddGrowableCol( 1 )

    item4.Add( item14, 0, wx.GROW, 5 )

    item3.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item18 = FTEL_TipoDocumentoRadioBox( parent, ID_RADIOBOX, "Tipo documento attura elettronica, da causale contabile", wx.DefaultPosition, wx.DefaultSize, 
        ["Non gestito","TD01 - Fattura","TD02 - Acconto ft.","TD03 - Acconto parcella","TD04 - Nota credito","TD05 - Nota debito","TD06 - Parcella","TD07 - Fattura semplif.","TD08 - Nota cr. semplif.","TD09 - Non utilizzato","TD10 - Ft. Intra beni","TD11 - Ft. Intra servizi"] , 2, wx.RA_SPECIFY_COLS )
    item18.SetName( "ftel_tipdoc" )
    item17.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item20 = wx.StaticBox( parent, -1, "Riferimento ai DDT" )
    item19 = wx.StaticBoxSizer( item20, wx.HORIZONTAL )
    
    item21 = CheckBox( parent, ID_FTEL_NODDT, "Non mettere i riferimenti ai DDT se doc. differito", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.SetName( "ftel_noddt" )
    item19.Add( item21, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item17.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item17.AddGrowableRow( 1 )

    item3.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item22 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item23 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item25 = wx.StaticBox( parent, -1, "Gestione Numero documento" )
    item24 = wx.StaticBoxSizer( item25, wx.VERTICAL )
    
    item26 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item27 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item28 = wx.StaticText( parent, ID_TEXT, "Famiglia:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item28, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item29 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [50,-1], 0 )
    item29.SetName( "docfam" )
    item27.Add( item29, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item30 = wx.StaticText( parent, ID_TEXT, "Numeraz.esterna:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item30, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item31 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [50,-1], 0 )
    item31.SetName( "numest" )
    item27.Add( item31, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item32 = wx.StaticText( parent, ID_TEXT, "Personalizzazione:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.Add( item32, 0, wx.ALIGN_CENTER, 5 )

    item33 = TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item33.SetName( "custde" )
    item27.Add( item33, 0, wx.GROW|wx.LEFT|wx.RIGHT, 5 )

    item26.Add( item27, 0, wx.ALIGN_CENTER, 5 )

    item34 = wx.BoxSizer( wx.VERTICAL )
    
    item35 = CheckBox( parent, ID_CTRNUM, "Controlla", wx.DefaultPosition, wx.DefaultSize, 0 )
    item35.SetName( "ctrnum" )
    item34.Add( item35, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item36 = CheckBox( parent, ID_AGGNUM, "Aggiorna", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.SetName( "aggnum" )
    item34.Add( item36, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item37 = CheckBox( parent, ID_PIENUM, "Richiesta a piede", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.SetName( "pienum" )
    item34.Add( item37, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item38 = CheckBox( parent, ID_NONUMXMAG, "Non numerare x mag.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item38.SetName( "nonumxmag" )
    item34.Add( item38, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item26.Add( item34, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item24.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item23.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item40 = wx.StaticBox( parent, -1, "Dati da richiedere in testata" )
    item39 = wx.StaticBoxSizer( item40, wx.VERTICAL )
    
    item41 = wx.BoxSizer( wx.HORIZONTAL )
    
    item42 = CheckBox( parent, ID_ASKMAGAZZ, "Magazzino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.SetName( "askmagazz" )
    item41.Add( item42, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item43 = CheckBox( parent, ID_PDCDAMAG, "Usa sua anagrafica", wx.DefaultPosition, wx.DefaultSize, 0 )
    item43.SetName( "pdcdamag" )
    item41.Add( item43, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item39.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item44 = wx.BoxSizer( wx.HORIZONTAL )
    
    item45 = CheckBox( parent, ID_ASKMODPAG, "Mod.pag.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.SetName( "askmodpag" )
    item44.Add( item45, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item46 = CheckBox( parent, ID_ASKBANCA, "Banca", wx.DefaultPosition, wx.DefaultSize, 0 )
    item46.SetName( "askbanca" )
    item44.Add( item46, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item47 = CheckBox( parent, ID_ASKMPNOEFF, "No effetti", wx.DefaultPosition, wx.DefaultSize, 0 )
    item47.SetName( "askmpnoeff" )
    item44.Add( item47, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item39.Add( item44, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item48 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item49 = CheckBox( parent, ID_ASKDESTIN, "Destinaz.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item49.SetName( "askdestin" )
    item48.Add( item49, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item50 = CheckBox( parent, ID_ASKAGENTE, "Agente", wx.DefaultPosition, wx.DefaultSize, 0 )
    item50.SetName( "askagente" )
    item48.Add( item50, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item51 = CheckBox( parent, ID_ASKZONA, "Zona", wx.DefaultPosition, wx.DefaultSize, 0 )
    item51.SetName( "askzona" )
    item48.Add( item51, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item39.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52 = wx.BoxSizer( wx.HORIZONTAL )
    
    item53 = CheckBox( parent, ID_ASKLISTINO, "Listino", wx.DefaultPosition, wx.DefaultSize, 0 )
    item53.SetName( "asklist" )
    item52.Add( item53, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item54 = CheckBox( parent, ID_ROWLISTINO, "Listino su ogni riga", wx.DefaultPosition, wx.DefaultSize, 0 )
    item54.SetName( "rowlist" )
    item52.Add( item54, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item39.Add( item52, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item23.Add( item39, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item56 = wx.StaticBox( parent, -1, "Totali" )
    item55 = wx.StaticBoxSizer( item56, wx.VERTICAL )
    
    item57 = CheckBox( parent, ID_TOTALI, "Mostra totali", wx.DefaultPosition, wx.DefaultSize, 0 )
    item57.SetName( "totali" )
    item55.Add( item57, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item58 = CheckBox( parent, ID_TOTZERO, "Accetta zero", wx.DefaultPosition, wx.DefaultSize, 0 )
    item58.SetName( "totzero" )
    item55.Add( item58, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item59 = CheckBox( parent, ID_TOTNEG, "Accetta negativo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item59.SetName( "totneg" )
    item55.Add( item59, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item23.Add( item55, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item22.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item22.AddGrowableCol( 0 )

    item22.AddGrowableRow( 1 )

    item2.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.AddGrowableRow( 1 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item60 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item61 = RadioBox( parent, ID_CLASDOC, "Classif. documento", wx.DefaultPosition, wx.DefaultSize, 
        ["Generico","Ordine a Fornitore","Carico da Fornitore","Reso a Fornitore","Ordine da Cliente","Vendita a Cliente","Reso da Cliente"] , 1, wx.RA_SPECIFY_COLS )
    item61.SetName( "clasdoc" )
    item60.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item63 = wx.StaticBox( parent, -1, "Dati di riferimento" )
    item62 = wx.StaticBoxSizer( item63, wx.VERTICAL )
    
    item64 = CheckBox( parent, ID_ASKRIFDESC, "Descrizione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item64.SetName( "askrifdesc" )
    item62.Add( item64, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item65 = CheckBox( parent, ID_ASKRIFNUM, "Numero", wx.DefaultPosition, wx.DefaultSize, 0 )
    item65.SetName( "askrifnum" )
    item62.Add( item65, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item66 = CheckBox( parent, ID_ASKRIFDATA, "Data", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.SetName( "askrifdata" )
    item62.Add( item66, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item60.Add( item62, 0, wx.GROW|wx.BOTTOM, 5 )

    item68 = wx.StaticBox( parent, -1, "Scontistiche" )
    item67 = wx.StaticBoxSizer( item68, wx.HORIZONTAL )
    
    item69 = wx.StaticText( parent, ID_TEXT, "Num.sconti:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item67.Add( item69, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item70 = NumCtrl(parent, ID_NUMSCONTI, integerWidth=1, allowNegative=False, groupDigits=False); item70.SetName("numsconti")
    item67.Add( item70, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item60.Add( item67, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item60.AddGrowableRow( 2 )

    item1.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item71 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item72 = wx.StaticText( parent, ID_TEXT, "Utenti che possono accedere:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item72.SetForegroundColour( wx.BLUE )
    item71.Add( item72, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item73 = wx.Panel( parent, ID_PANGRIDPERM, wx.DefaultPosition, [200,160], wx.SUNKEN_BORDER )
    item73.SetName( "pangridperm" )
    item71.Add( item73, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item71.AddGrowableCol( 0 )

    item71.AddGrowableRow( 1 )

    item1.Add( item71, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 2 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item74 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item75 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item77 = wx.StaticBox( parent, -1, "Dati da proporre in testata" )
    item76 = wx.StaticBoxSizer( item77, wx.VERTICAL )
    
    item78 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item79 = wx.StaticText( parent, ID_TEXT, "Magazzino:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item78.Add( item79, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item80 = wx.StaticText( parent, ID_TEXT, "Mod.Pagamento:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item78.Add( item80, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item81 = LinkTable(parent, ID_MAGAZZ ); item81.SetDataLink( bt.TABNAME_MAGAZZ, "id_magazz", MagazzDialog )
    item78.Add( item81, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item82 = alib.LinkTableModPag(parent, ID_MODPAG, 'id_modpag')
    item78.Add( item82, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item78.AddGrowableCol( 0 )

    item78.AddGrowableCol( 1 )

    item76.Add( item78, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item75.Add( item76, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item84 = wx.StaticBox( parent, -1, "Generazione documento di trasferimento" )
    item83 = wx.StaticBoxSizer( item84, wx.VERTICAL )
    
    item85 = LinkTable(parent, ID_TDOCTRA ); item85.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_tdoctra", None )
    item83.Add( item85, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item75.Add( item83, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item75.AddGrowableCol( 0 )

    item74.Add( item75, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item86 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item87 = RadioBox( parent, ID_PROVVIG, "Provvigioni", wx.DefaultPosition, wx.DefaultSize, 
        ["No","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item87.SetName( "provvig" )
    item86.Add( item87, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item89 = wx.StaticBox( parent, -1, "Etichette" )
    item88 = wx.StaticBoxSizer( item89, wx.VERTICAL )
    
    item90 = CheckBox( parent, ID_STETIC, "Stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item90.SetName( "printetic" )
    item88.Add( item90, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item86.Add( item88, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item86.AddGrowableRow( 1 )

    item74.Add( item86, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item92 = wx.StaticBox( parent, -1, "Stampa" )
    item91 = wx.StaticBoxSizer( item92, wx.VERTICAL )
    
    item93 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item94 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item95 = wx.StaticText( parent, ID_TEXT, "Report:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item94.Add( item95, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item96 = TextCtrl_LC( parent, ID_TOOLPRINT, "", wx.DefaultPosition, [80,-1], 0 )
    item96.SetName( "toolprint" )
    item94.Add( item96, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item97 = wx.StaticText( parent, ID_TEXT, "Ft.PA:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item94.Add( item97, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item98 = TextCtrl_LC( parent, ID_FTEL_LAYOUT, "", wx.DefaultPosition, [80,-1], 0 )
    item98.SetName( "ftel_layout" )
    item94.Add( item98, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item93.Add( item94, 0, wx.ALIGN_CENTER, 5 )

    item99 = wx.StaticText( parent, ID_TEXT, "Num./", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item93.Add( item99, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item100 = TextCtrl( parent, ID_TOOLBARRA, "", wx.DefaultPosition, [20,-1], 0 )
    item100.SetName( "toolbarra" )
    item93.Add( item100, 0, wx.LEFT|wx.BOTTOM, 5 )

    item101 = wx.StaticText( parent, ID_TEXT, "Stampante:", wx.DefaultPosition, [70,20], wx.ALIGN_RIGHT )
    item93.Add( item101, 0, wx.ALIGN_RIGHT|wx.TOP, 5 )

    item102 = PrintersComboBox( parent, ID_COMBO, "", wx.DefaultPosition, wx.DefaultSize, [], wx.CB_DROPDOWN|wx.CB_READONLY )
    item102.SetName( "printer" )
    item93.Add( item102, 0, wx.LEFT|wx.RIGHT, 5 )

    item103 = wx.StaticText( parent, ID_TEXT, "Copie:", wx.DefaultPosition, wx.DefaultSize, wx.ALIGN_RIGHT )
    item93.Add( item103, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item104 = NumCtrl(parent, ID_COPIES, integerWidth=3, allowNegative=False, groupDigits=False); item104.SetName("copies")
    item93.Add( item104, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.BOTTOM, 5 )

    item93.AddGrowableCol( 5 )

    item91.Add( item93, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item105 = wx.FlexGridSizer( 0, 4, 0, 0 )
    
    item106 = CheckBox( parent, ID_STAINTEST, "Stampa dati azienda", wx.DefaultPosition, wx.DefaultSize, 0 )
    item106.SetName( "staintest" )
    item105.Add( item106, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item107 = CheckBox( parent, ID_ASKSTAINT, "Chiedi stampa intestazioni", wx.DefaultPosition, wx.DefaultSize, 0 )
    item107.SetName( "askstaint" )
    item105.Add( item107, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item108 = CheckBox( parent, ID_STAOBB, "Obbligatoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item108.SetName( "staobb" )
    item105.Add( item108, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item105.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER, 5 )

    item109 = CheckBox( parent, ID_STALOGO, "Stampa logo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item109.SetName( "stalogo" )
    item105.Add( item109, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item110 = CheckBox( parent, ID_ASKSTAPRE, "Chiedi stampa prezzi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item110.SetName( "askstapre" )
    item105.Add( item110, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item111 = CheckBox( parent, ID_STANOC, "Non contabile", wx.DefaultPosition, wx.DefaultSize, 0 )
    item111.SetName( "stanoc" )
    item105.Add( item111, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item112 = CheckBox( parent, ID_DOCEMAIL, "Invia email", wx.DefaultPosition, wx.DefaultSize, 0 )
    item112.SetName( "docemail" )
    item105.Add( item112, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item113 = CheckBox( parent, ID_AANOTEDOC, "Non copiare note anag.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item113.SetName( "aanotedoc" )
    item105.Add( item113, 0, wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item91.Add( item105, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item74.Add( item91, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item74.AddGrowableCol( 0 )

    item0.Add( item74, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_COLCG = 16051
ID_NOIVAPROF = 16052
ID_CTRCAUCON = 16053
ID_SCORPIVA = 16054
ID_SOGRITACC = 16055
ID_CTRPDCRITACC = 16056
ID_ASKPROTIVA = 16057
ID_AUTOQTAONBC = 16058
ID_RPTCOLLI = 16059
ID_DESEVARIF = 16060
ID_CTRACQDOC1 = 16061
ID_TIPACQ1 = 16062
ID_COPYDOC1 = 16063
ID_EVADOC1 = 16064
ID_ACQDOC1 = 16065
ID_ANNACQ1 = 16066
ID_CHECKACQ1 = 16067
ID_CTRACQDOC2 = 16068
ID_TIPACQ2 = 16069
ID_COPYDOC2 = 16070
ID_EVADOC2 = 16071
ID_ACQDOC2 = 16072
ID_ANNACQ2 = 16073
ID_CHECKACQ2 = 16074
ID_CTRACQDOC3 = 16075
ID_TIPACQ3 = 16076
ID_COPYDOC3 = 16077
ID_EVADOC3 = 16078
ID_ACQDOC3 = 16079
ID_ANNACQ3 = 16080
ID_CHECKACQ3 = 16081
ID_CTRACQDOC4 = 16082
ID_TIPACQ4 = 16083
ID_COPYDOC4 = 16084
ID_EVADOC4 = 16085
ID_ACQDOC4 = 16086
ID_ANNACQ4 = 16087
ID_CHECKACQ4 = 16088
ID_CHECKFIDO = 16089
ID_VISLISTINI = 16090
ID_VISCOSTO = 16091
ID_VISGIAC = 16092
ID_VISULTMOV = 16093
ID_ULTMOVBEF = 16094
ID_VISMARGINE = 16095
ID_ASKDATIACC = 16096
ID_TRAKGC = 16097
ID_TRACAU = 16098
ID_TRAASP = 16099
ID_TRACUR = 16100
ID_TRAPOR = 16101
ID_TRAVET = 16102
ID_TRACON = 16103

def Doc2Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item5 = wx.StaticBox( parent, -1, "Collegamento contabile" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )
    
    item6 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item7 = ColCgCheckBox( parent, ID_COLCG, "Contabilizza su:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item7.SetName( "colcg" )
    item6.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item8 = AccorpaIvaCheckBox( parent, ID_NOIVAPROF, "Accorpa IVA se causale composta", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.SetName( "noivaprof" )
    item6.Add( item8, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.AddGrowableCol( 1 )

    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = LinkTableCauContab(parent, ID_CTRCAUCON, "id_caucg")
    item4.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item3.Add( item4, 0, wx.GROW|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item10 = RadioBox( parent, ID_SCORPIVA, "Gli importi sono:", wx.DefaultPosition, wx.DefaultSize, 
        ["Imponibili: l'IVA sarà aggiunta","Ivati: l'IVA sarà scorporata"] , 1, wx.RA_SPECIFY_COLS )
    item10.SetName( "scorpiva" )
    item3.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item3.AddGrowableCol( 0 )

    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item12 = wx.StaticBox( parent, -1, "Gestione Ritenuta d'Acconto" )
    item11 = wx.StaticBoxSizer( item12, wx.VERTICAL )
    
    item13 = RitAccCheckBox( parent, ID_SOGRITACC, "Attiva la gestione delle ritenute d'acconto e contabilizzale su:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.SetName( "sogritacc" )
    item11.Add( item13, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item14 = LinkTablePdc(parent, ID_CTRPDCRITACC, "id_pdc_ra")
    item11.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item11, 0, wx.GROW|wx.LEFT|wx.RIGHT, 5 )

    item2.AddGrowableCol( 0 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = RadioBox( parent, ID_ASKPROTIVA, "Protocollo IVA", wx.DefaultPosition, wx.DefaultSize, 
        ["Non richiesto","Proposto zero","Proposto numero documento","Proposto da registro IVA"] , 1, wx.RA_SPECIFY_COLS )
    item15.SetName( "askprotiva" )
    item1.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item16 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item18 = wx.StaticBox( parent, -1, "Barcode" )
    item17 = wx.StaticBoxSizer( item18, wx.VERTICAL )
    
    item19 = CheckBox( parent, ID_AUTOQTAONBC, "Auto qta = 1", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetName( "autoqtaonbc" )
    item17.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item16.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item21 = wx.StaticBox( parent, -1, "Segnacolli" )
    item20 = wx.StaticBoxSizer( item21, wx.VERTICAL )
    
    item22 = CheckBox( parent, ID_RPTCOLLI, "Attiva stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.SetName( "rptcolli" )
    item20.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item16.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item24 = wx.StaticBox( parent, -1, "Evasione doc." )
    item23 = wx.StaticBoxSizer( item24, wx.VERTICAL )
    
    item25 = CheckBox( parent, ID_DESEVARIF, "Usa dati rif.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.SetName( "desevarif" )
    item23.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item16.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item16.AddGrowableRow( 2 )

    item1.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item28 = wx.StaticBox( parent, -1, "Acquisizione ed evazione altri documenti" )
    item27 = wx.StaticBoxSizer( item28, wx.VERTICAL )
    
    item29 = wx.FlexGridSizer( 0, 6, 0, 0 )
    
    item30 = wx.StaticText( parent, ID_TEXT, "Documento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.TOP|wx.BOTTOM, 5 )

    item31 = wx.StaticText( parent, ID_TEXT, "Copia", wx.DefaultPosition, [30,-1], 0 )
    item29.Add( item31, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item32 = wx.StaticText( parent, ID_TEXT, "Evadi", wx.DefaultPosition, [30,-1], 0 )
    item29.Add( item32, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item33 = wx.StaticText( parent, ID_TEXT, "Acquis", wx.DefaultPosition, [30,-1], 0 )
    item29.Add( item33, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item34 = wx.StaticText( parent, ID_TEXT, "Annul", wx.DefaultPosition, [30,-1], 0 )
    item29.Add( item34, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item35 = wx.StaticText( parent, ID_TEXT, "Check", wx.DefaultPosition, [30,-1], 0 )
    item29.Add( item35, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item36 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item37 = LinkTable(parent, ID_CTRACQDOC1 ); item37.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_acqdoc1", None )
    item36.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item38 = TextCtrl(parent, ID_TIPACQ1); item38.SetName('tipacq1'); item38.Show(False)
    item36.Add( item38, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item36.AddGrowableCol( 0 )

    item29.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item39 = CheckBox( parent, ID_COPYDOC1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.SetName( "_copydoc1" )
    item29.Add( item39, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item40 = CheckBox( parent, ID_EVADOC1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.SetName( "_evadoc1" )
    item29.Add( item40, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item41 = CheckBox( parent, ID_ACQDOC1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.SetName( "_acqdoc1" )
    item29.Add( item41, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item42 = CheckBox( parent, ID_ANNACQ1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.SetName( "annacq1" )
    item29.Add( item42, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item43 = CheckBox( parent, ID_CHECKACQ1, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item43.SetName( "checkacq1" )
    item29.Add( item43, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item44 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item45 = LinkTable(parent, ID_CTRACQDOC2 ); item45.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_acqdoc2", None )
    item44.Add( item45, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item46 = TextCtrl(parent, ID_TIPACQ2); item46.SetName('tipacq2'); item46.Show(False)
    item44.Add( item46, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item44.AddGrowableCol( 0 )

    item29.Add( item44, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47 = CheckBox( parent, ID_COPYDOC2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item47.SetName( "_copydoc2" )
    item29.Add( item47, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item48 = CheckBox( parent, ID_EVADOC2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item48.SetName( "_evadoc2" )
    item29.Add( item48, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item49 = CheckBox( parent, ID_ACQDOC2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item49.SetName( "_acqdoc2" )
    item29.Add( item49, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item50 = CheckBox( parent, ID_ANNACQ2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item50.SetName( "annacq2" )
    item29.Add( item50, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item51 = CheckBox( parent, ID_CHECKACQ2, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item51.SetName( "checkacq2" )
    item29.Add( item51, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item52 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item53 = LinkTable(parent, ID_CTRACQDOC3 ); item53.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_acqdoc3", None )
    item52.Add( item53, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item54 = TextCtrl(parent, ID_TIPACQ3); item54.SetName('tipacq3'); item54.Show(False)
    item52.Add( item54, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item52.AddGrowableCol( 0 )

    item29.Add( item52, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item55 = CheckBox( parent, ID_COPYDOC3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.SetName( "_copydoc3" )
    item29.Add( item55, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item56 = CheckBox( parent, ID_EVADOC3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.SetName( "_evadoc3" )
    item29.Add( item56, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item57 = CheckBox( parent, ID_ACQDOC3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item57.SetName( "_acqdoc3" )
    item29.Add( item57, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item58 = CheckBox( parent, ID_ANNACQ3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item58.SetName( "annacq3" )
    item29.Add( item58, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item59 = CheckBox( parent, ID_CHECKACQ3, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item59.SetName( "checkacq3" )
    item29.Add( item59, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item60 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item61 = LinkTable(parent, ID_CTRACQDOC4 ); item61.SetDataLink( bt.TABNAME_CFGMAGDOC, "id_acqdoc4", None )
    item60.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item62 = TextCtrl(parent, ID_TIPACQ4); item62.SetName('tipacq4'); item62.Show(False)
    item60.Add( item62, 0, wx.ALIGN_CENTER|wx.BOTTOM, 5 )

    item60.AddGrowableCol( 0 )

    item29.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item63 = CheckBox( parent, ID_COPYDOC4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item63.SetName( "_copydoc4" )
    item29.Add( item63, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item64 = CheckBox( parent, ID_EVADOC4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item64.SetName( "_evadoc4" )
    item29.Add( item64, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item65 = CheckBox( parent, ID_ACQDOC4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item65.SetName( "_acqdoc4" )
    item29.Add( item65, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item66 = CheckBox( parent, ID_ANNACQ4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.SetName( "annacq4" )
    item29.Add( item66, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item67 = CheckBox( parent, ID_CHECKACQ4, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item67.SetName( "checkacq4" )
    item29.Add( item67, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item29.AddGrowableCol( 0 )

    item27.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item68 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item70 = wx.StaticBox( parent, -1, "Fido cliente" )
    item69 = wx.StaticBoxSizer( item70, wx.VERTICAL )
    
    item71 = CheckBox( parent, ID_CHECKFIDO, "Doc. sottoposto a controllo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.SetName( "checkfido" )
    item69.Add( item71, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item68.Add( item69, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item73 = wx.StaticBox( parent, -1, "Del prodotto, visualizza:" )
    item72 = wx.StaticBoxSizer( item73, wx.VERTICAL )
    
    item74 = CheckBox( parent, ID_VISLISTINI, "Dati e listini in vigore", wx.DefaultPosition, wx.DefaultSize, 0 )
    item74.SetName( "vislistini" )
    item72.Add( item74, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item75 = wx.BoxSizer( wx.HORIZONTAL )
    
    item76 = CheckBox( parent, ID_VISCOSTO, "Costo U.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item76.SetName( "viscosto" )
    item75.Add( item76, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item77 = CheckBox( parent, ID_VISGIAC, "Giacenza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item77.SetName( "visgiac" )
    item75.Add( item77, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item72.Add( item75, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item78 = wx.BoxSizer( wx.HORIZONTAL )
    
    item79 = CheckBox( parent, ID_VISULTMOV, "Movim. anag.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item79.SetName( "visultmov" )
    item78.Add( item79, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item80 = CheckBox( parent, ID_ULTMOVBEF, "Dai priorità", wx.DefaultPosition, wx.DefaultSize, 0 )
    item80.SetToolTip( wx.ToolTip("Se attivato, rende prioritaria la visualizzazione dei movimenti rispetto ai dati del prodotto") )
    item80.SetName( "ultmovbef" )
    item78.Add( item80, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item72.Add( item78, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item68.Add( item72, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item82 = wx.StaticBox( parent, -1, "Margine vendita" )
    item81 = wx.StaticBoxSizer( item82, wx.VERTICAL )
    
    item83 = CheckBox( parent, ID_VISMARGINE, "Visualizza", wx.DefaultPosition, wx.DefaultSize, 0 )
    item83.SetName( "vismargine" )
    item81.Add( item83, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item68.Add( item81, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item68.AddGrowableRow( 2 )

    item26.Add( item68, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item26.AddGrowableCol( 0 )

    item0.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item85 = wx.StaticBox( parent, -1, "Dati accompagnatori richiesti" )
    item84 = wx.StaticBoxSizer( item85, wx.VERTICAL )
    
    item86 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item87 = CheckBox( parent, ID_ASKDATIACC, "Attiva", wx.DefaultPosition, wx.DefaultSize, 0 )
    item87.SetName( "askdatiacc" )
    item86.Add( item87, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item88 = RCheckBox( parent, ID_TRAKGC, "Peso e colli", wx.DefaultPosition, wx.DefaultSize, 0 )
    item88.SetName( "asktrakgc" )
    item86.Add( item88, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item84.Add( item86, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item89 = wx.FlexGridSizer( 0, 4, 0, 0 )
    
    item90 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item89.Add( item90, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item91 = wx.StaticText( parent, ID_TEXT, "Valore di default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item89.Add( item91, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item92 = wx.StaticText( parent, ID_TEXT, "", wx.DefaultPosition, wx.DefaultSize, 0 )
    item89.Add( item92, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item93 = wx.StaticText( parent, ID_TEXT, "Valore di default", wx.DefaultPosition, wx.DefaultSize, 0 )
    item89.Add( item93, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item94 = RCheckBox( parent, ID_TRACAU, "Causale trasporto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item94.SetName( "asktracau" )
    item89.Add( item94, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item95 = LinkTable(parent, ID_TRACAU ); item95.SetDataLink( bt.TABNAME_TRACAU, "id_tracau", TraCauDialog )
    item89.Add( item95, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item96 = RCheckBox( parent, ID_TRAASP, "Aspetto esteriore beni", wx.DefaultPosition, wx.DefaultSize, 0 )
    item96.SetName( "asktraasp" )
    item89.Add( item96, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item97 = LinkTable(parent, ID_TRAASP ); item97.SetDataLink( bt.TABNAME_TRAASP, "id_traasp", TraAspDialog )
    item89.Add( item97, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item98 = RCheckBox( parent, ID_TRACUR, "Trasporto a cura", wx.DefaultPosition, wx.DefaultSize, 0 )
    item98.SetName( "asktracur" )
    item89.Add( item98, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item99 = LinkTable(parent, ID_TRACUR ); item99.SetDataLink( bt.TABNAME_TRACUR, "id_tracur", TraCurDialog )
    item89.Add( item99, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item100 = RCheckBox( parent, ID_TRAPOR, "Porto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item100.SetName( "asktrapor" )
    item89.Add( item100, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item101 = LinkTable(parent, ID_TRAPOR ); item101.SetDataLink( bt.TABNAME_TRAPOR, "id_trapor", TraPorDialog )
    item89.Add( item101, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item102 = RCheckBox( parent, ID_TRAVET, "Vettore", wx.DefaultPosition, wx.DefaultSize, 0 )
    item102.SetName( "asktravet" )
    item89.Add( item102, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item103 = LinkTable(parent, ID_TRAVET ); item103.SetDataLink( bt.TABNAME_TRAVET, "id_travet", TraVetDialog )
    item89.Add( item103, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item104 = RCheckBox( parent, ID_TRACON, "Contrassegno", wx.DefaultPosition, wx.DefaultSize, 0 )
    item104.SetName( "asktracon" )
    item89.Add( item104, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item105 = LinkTable(parent, ID_TRACON ); item105.SetDataLink( bt.TABNAME_TRACON, "id_tracon", TraConDialog )
    item89.Add( item105, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item89.AddGrowableCol( 1 )

    item89.AddGrowableCol( 3 )

    item84.Add( item89, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item84, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_PANGRIDMOV = 16104
ID_BUTNEWMOV = 16105
ID_BUTDELMOV = 16106
ID_MOVBOOK = 16107

def MovFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item2 = wx.Panel( parent, ID_PANGRIDMOV, wx.DefaultPosition, wx.DefaultSize, wx.SUNKEN_BORDER )
    item1.Add( item2, 0, wx.GROW|wx.ALL, 5 )

    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = wx.Button( parent, ID_BUTNEWMOV, "Nuovo movimento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.LEFT|wx.BOTTOM, 5 )

    item5 = wx.Button( parent, ID_BUTDELMOV, "Elimina movimento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableRow( 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7 = MovNotebook( parent, ID_MOVBOOK, wx.DefaultPosition, [200,160], 0 )
    item6 = item7
    
    item8 = wx.Panel( item7, -1 )
    Mov1Func(item8, False)
    item7.AddPage( item8, "Definizione movimento" )

    item9 = wx.Panel( item7, -1 )
    Mov2Func(item9, False)
    item7.AddPage( item9, "Progressivi" )

    item0.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TIPOLOGIA = 16108
ID_LENDESCRIZ = 16109
ID_ASKVALORI = 16110
ID_CANPREZZO0 = 16111
ID_TIPVALUNI = 16112
ID_TIPSCONTI = 16113
ID_AGGCOSTO = 16114
ID_AGGPREZZO = 16115
ID_MODIMPRICALC = 16116
ID_AGGGRP = 16117
ID_RICCOSTO = 16118
ID_CHECKBOX = 16119
ID_AGGFORNIT = 16120
ID_ACQPDT = 16121
ID_NOMASTROPROD = 16122
ID_PROOBB = 16123
ID_NOPROVVIG = 16124
ID_LABELPDC = 16125
ID_CTRPDC = 16126
ID_PDCRESET = 16127
ID_ISACCONTO = 16128
ID_ISACCSTOR = 16129
ID_ACC_SEPIVA = 16130
ID_PRTDESTOT = 16131

def Mov1Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = RadioBox( parent, ID_TIPOLOGIA, "Tipologia", wx.DefaultPosition, wx.DefaultSize, 
        ["Descrizione","Merce","Servizi","Spese","Trasporto","Sc. ripart.","Sc. merce","Omaggio","Aum.Prezzi"] , 1, wx.RA_SPECIFY_COLS )
    item3.SetName( "tipologia" )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item5 = wx.StaticBox( parent, -1, "Descrizione" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )
    
    item6 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "#Caratteri", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item8 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item9 = wx.StaticText( parent, ID_TEXT, "max:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item10 = NumCtrl(parent, ID_LENDESCRIZ, integerWidth=4, allowNegative=False, groupDigits=False); item10.SetName("lendescriz")
    item8.Add( item10, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6.AddGrowableCol( 0 )

    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item2.AddGrowableRow( 1 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item12 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item13 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item14 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item15 = RadioBox( parent, ID_ASKVALORI, "Valori richiesti", wx.DefaultPosition, wx.DefaultSize, 
        ["Solo qtà","Qtà, prezzo","Solo importo","Nulla"] , 1, wx.RA_SPECIFY_COLS )
    item15.SetName( "askvalori" )
    item14.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.StaticBox( parent, -1, "Richiesta prezzo" )
    item16 = wx.StaticBoxSizer( item17, wx.VERTICAL )
    
    item18 = CheckBox( parent, ID_CANPREZZO0, "Permetti 0", wx.DefaultPosition, wx.DefaultSize, 0 )
    item18.SetName( "canprezzo0" )
    item16.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item13.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item19 = RadioBox( parent, ID_TIPVALUNI, "Prop.Prezzo", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Costo","Prezzo","Listino"] , 1, wx.RA_SPECIFY_COLS )
    item19.SetName( "tipvaluni" )
    item13.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item20 = RadioBox( parent, ID_TIPSCONTI, "Prop.Sconti", wx.DefaultPosition, wx.DefaultSize, 
        ["Nulla","Da prodotto","Da cliente","Da griglia","Da gruppo prezzi"] , 1, wx.RA_SPECIFY_COLS )
    item20.SetName( "tipsconti" )
    item13.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item21 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item22 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item23 = RadioBox( parent, ID_AGGCOSTO, "Aggiorna costo", wx.DefaultPosition, wx.DefaultSize, 
        ["No","Da val. unitario","Da tot. riga"] , 1, wx.RA_SPECIFY_COLS )
    item23.SetName( "aggcosto" )
    item22.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item24 = RadioBox( parent, ID_AGGPREZZO, "Aggiorna prezzo", wx.DefaultPosition, wx.DefaultSize, 
        ["No","Da val. unitario","Da tot. riga"] , 1, wx.RA_SPECIFY_COLS )
    item24.SetName( "aggprezzo" )
    item22.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item21.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item25 = RadioBox( parent, ID_MODIMPRICALC, "La modifica dell'importo ricalcola:", wx.DefaultPosition, wx.DefaultSize, 
        ["Gli sconti (standard)","La quantità","Il prezzo"] , 1, wx.RA_SPECIFY_COLS )
    item25.SetName( "modimpricalc" )
    item21.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item13.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = RadioBox( parent, ID_AGGGRP, "Aggiorna griglie", wx.DefaultPosition, wx.DefaultSize, 
        ["No","Aggiorna più recente","Crea nuova griglia"] , 1, wx.RA_SPECIFY_COLS )
    item26.SetName( "agggrip" )
    item13.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item13.AddGrowableCol( 0 )

    item13.AddGrowableCol( 1 )

    item13.AddGrowableCol( 2 )

    item12.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item27 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item29 = wx.StaticBox( parent, -1, "Ricalcoli" )
    item28 = wx.StaticBoxSizer( item29, wx.VERTICAL )
    
    item30 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item31 = CheckBox( parent, ID_RICCOSTO, "Ricalcola il costo di acquisto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.SetName( "riccosto" )
    item30.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item32 = RCheckBox( parent, ID_CHECKBOX, "Usa sconti riga", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetName( "riccostosr" )
    item30.Add( item32, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item30.AddGrowableCol( 1 )

    item28.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item33 = CheckBox( parent, ID_RICCOSTO, "Ricalcola il prezzo al pubblico", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.SetName( "ricprezzo" )
    item28.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item34 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item35 = CheckBox( parent, ID_RICCOSTO, "Ricalcola i listini di vendita", wx.DefaultPosition, wx.DefaultSize, 0 )
    item35.SetName( "riclist" )
    item34.Add( item35, 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item36 = wx.StaticText( parent, ID_TEXT, "-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item34.Add( item36, 0, wx.ALIGN_CENTER|wx.TOP|wx.BOTTOM, 5 )

    item37 = RCheckBox( parent, ID_CHECKBOX, "Sempre nuovi", wx.DefaultPosition, wx.DefaultSize, 0 )
    item37.SetName( "newlist" )
    item34.Add( item37, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item34.AddGrowableCol( 0 )

    item34.AddGrowableCol( 2 )

    item28.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item27.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item39 = wx.StaticBox( parent, -1, "Varie" )
    item38 = wx.StaticBoxSizer( item39, wx.VERTICAL )
    
    item40 = CheckBox( parent, ID_AGGFORNIT, "Aggiorna fornitore prodotto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item40.SetName( "aggfornit" )
    item38.Add( item40, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item41 = CheckBox( parent, ID_ACQPDT, "Attiva collegamento a PDT", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.SetName( "f_acqpdt" )
    item38.Add( item41, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item42 = CheckBox( parent, ID_NOMASTROPROD, "Escludi in mastro prodotto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item42.SetName( "nomastroprod" )
    item38.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item27.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item44 = wx.StaticBox( parent, -1, "Provvigioni agenti" )
    item43 = wx.StaticBoxSizer( item44, wx.VERTICAL )
    
    item45 = CheckBox( parent, ID_PROOBB, "Provvigione obbligatoria", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.SetName( "proobb" )
    item43.Add( item45, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item46 = CheckBox( parent, ID_NOPROVVIG, "Escludi dal calcolo", wx.DefaultPosition, wx.DefaultSize, 0 )
    item46.SetName( "noprovvig" )
    item43.Add( item46, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item27.Add( item43, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item27.AddGrowableCol( 1 )

    item27.AddGrowableCol( 2 )

    item12.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item49 = wx.StaticBox( parent, -1, "Collegamento contabile" )
    item48 = wx.StaticBoxSizer( item49, wx.VERTICAL )
    
    item50 = wx.StaticText( parent, ID_LABELPDC, "Sottoconto su cui contabilizzare le righe:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item48.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item51 = LinkTable(parent, ID_CTRPDC ); item51.SetDataLink( bt.TABNAME_PDC, "id_pdc", PdcDialog )
    item48.Add( item51, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52 = CheckBox( parent, ID_PDCRESET, "Resetta in inserimento righe evase da altro documento", wx.DefaultPosition, wx.DefaultSize, 0 )
    item52.SetName( "pdcreset" )
    item48.Add( item52, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item47.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item54 = wx.StaticBox( parent, -1, "Acconti" )
    item53 = wx.StaticBoxSizer( item54, wx.VERTICAL )
    
    item55 = CheckBox( parent, ID_ISACCONTO, "E' un acconto", wx.DefaultPosition, wx.DefaultSize, 0 )
    item55.SetName( "is_acconto" )
    item53.Add( item55, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item56 = CheckBox( parent, ID_ISACCSTOR, "E' uno storno", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.SetName( "is_accstor" )
    item53.Add( item56, 0, wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item57 = CheckBox( parent, ID_ACC_SEPIVA, "Separa Tot.IVA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item57.SetName( "acc_sepiva" )
    item53.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47.Add( item53, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item59 = wx.StaticBox( parent, -1, "Tot.IVA (semplif.)" )
    item58 = wx.StaticBoxSizer( item59, wx.VERTICAL )
    
    item60 = wx.StaticText( parent, ID_LABELPDC, "Descrizione del totale:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item58.Add( item60, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item61 = TextCtrl( parent, ID_PRTDESTOT, "", wx.DefaultPosition, [80,-1], 0 )
    item61.SetName( "prtdestot" )
    item58.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47.Add( item58, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item63 = wx.StaticBox( parent, -1, "Totalizza Qta per:" )
    item62 = wx.StaticBoxSizer( item63, wx.VERTICAL )
    
    item64 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item65 = CheckBox( parent, ID_CHECKBOX, "Tot. Peso KG", wx.DefaultPosition, wx.DefaultSize, 0 )
    item65.SetName( "tqtaxpeso" )
    item64.Add( item65, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item66 = CheckBox( parent, ID_CHECKBOX, "Tot. Colli", wx.DefaultPosition, wx.DefaultSize, 0 )
    item66.SetName( "tqtaxcolli" )
    item64.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item64.AddGrowableCol( 0 )

    item62.Add( item64, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item47.Add( item62, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item47.AddGrowableCol( 0 )

    item12.Add( item47, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item12.AddGrowableCol( 0 )

    item12.AddGrowableRow( 1 )

    item11.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11.AddGrowableCol( 0 )

    item11.AddGrowableCol( 1 )

    item1.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.AddGrowableCol( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TXTEMAIL = 16132

def Doc3Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.StaticText( parent, ID_TEXT, "Testo da includere nella email, quando spedita, come corpo del messaggio.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.SetForegroundColour( wx.BLUE )
    item0.Add( item1, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item2 = wx.TextCtrl( parent, ID_TXTEMAIL, "", wx.DefaultPosition, wx.DefaultSize, wx.TE_MULTILINE )
    item2.SetName( "txtemail" )
    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_AGGINI = 16133
ID_AGGINIV = 16134
ID_AGGCAR = 16135
ID_AGGCARV = 16136
ID_AGGSCA = 16137
ID_AGGSCAV = 16138
ID_AGGORDFOR = 16139
ID_AGGORDCLI = 16140
ID_AGGCVCCAR = 16141
ID_AGGCVCSCA = 16142
ID_AGGCVFCAR = 16143
ID_AGGCVFSCA = 16144
ID_STATFTCLI = 16145
ID_STATCSCLI = 16146
ID_MANCOSTO = 16147
ID_STATFTFOR = 16148

def Mov2Func( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Inventario", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.SetBackgroundColour( wx.LIGHT_GREY )
    item3.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item4 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item5 = RadioBox( parent, ID_AGGINI, "Giacenza iniziale", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item5.SetName( "aggini" )
    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item6 = RadioBox( parent, ID_AGGINIV, "Valore giac.iniziale", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item6.SetName( "agginiv" )
    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item4.AddGrowableCol( 1 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item7 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item8 = RadioBox( parent, ID_AGGCAR, "Carichi", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item8.SetName( "aggcar" )
    item7.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = RadioBox( parent, ID_AGGCARV, "Valore carichi", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item9.SetName( "aggcarv" )
    item7.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item7.AddGrowableCol( 1 )

    item2.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item10 = CheckBox( parent, ID_CHECKBOX, "Aggiorna data/num. ultimo carico", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetName( "aggultcar" )
    item2.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item11 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item12 = RadioBox( parent, ID_AGGSCA, "Scarichi", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item12.SetName( "aggsca" )
    item11.Add( item12, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item13 = RadioBox( parent, ID_AGGSCAV, "Valore scarichi", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item13.SetName( "aggscav" )
    item11.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item11.AddGrowableCol( 1 )

    item2.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item2.AddGrowableCol( 0 )

    item2.AddGrowableRow( 1 )

    item2.AddGrowableRow( 2 )

    item2.AddGrowableRow( 3 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item14 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item15 = wx.StaticText( parent, ID_TEXT, "Ordini", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetBackgroundColour( wx.LIGHT_GREY )
    item15.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item14.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item16 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item17 = RadioBox( parent, ID_AGGORDFOR, "Ordini a fornitore", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item17.SetName( "aggordfor" )
    item16.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item18 = RadioBox( parent, ID_AGGORDCLI, "Ordini da cliente", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item18.SetName( "aggordcli" )
    item16.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item16.AddGrowableCol( 1 )

    item14.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item19 = wx.StaticText( parent, ID_TEXT, "Conto Vendita", wx.DefaultPosition, wx.DefaultSize, 0 )
    item19.SetBackgroundColour( wx.LIGHT_GREY )
    item19.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item14.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item20 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item21 = RadioBox( parent, ID_AGGCVCCAR, "Car. C/V Clienti", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item21.SetName( "aggcvccar" )
    item20.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item22 = RadioBox( parent, ID_AGGCVCSCA, "Scar. C/V Clienti", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item22.SetName( "aggcvcsca" )
    item20.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item20.AddGrowableCol( 1 )

    item14.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item23 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item24 = RadioBox( parent, ID_AGGCVFCAR, "Car. C/V Fornit.", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item24.SetName( "aggcvfcar" )
    item23.Add( item24, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item25 = RadioBox( parent, ID_AGGCVFSCA, "Scar. C/V Fornit.", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item25.SetName( "aggcvfsca" )
    item23.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT, 5 )

    item23.AddGrowableCol( 1 )

    item14.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.BOTTOM, 5 )

    item14.AddGrowableCol( 0 )

    item14.AddGrowableRow( 1 )

    item14.AddGrowableRow( 3 )

    item14.AddGrowableRow( 4 )

    item1.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item27 = wx.StaticText( parent, ID_TEXT, "Valori statistici", wx.DefaultPosition, wx.DefaultSize, 0 )
    item27.SetBackgroundColour( wx.LIGHT_GREY )
    item27.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item26.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP, 5 )

    item28 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item29 = RadioBox( parent, ID_STATFTCLI, "Fatt.clienti: Vendita", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item29.SetName( "statftcli" )
    item28.Add( item29, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item30 = RadioBox( parent, ID_STATCSCLI, "Fatt.clienti: Costo", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item30.SetName( "statcscli" )
    item28.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item28.AddGrowableCol( 1 )

    item28.AddGrowableCol( 2 )

    item26.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item31 = RadioBox( parent, ID_MANCOSTO, "Valore costo riga", wx.DefaultPosition, wx.DefaultSize, 
        ["Nascondi","Visualizza","Modifica"] , 1, wx.RA_SPECIFY_ROWS )
    item31.SetName( "mancosto" )
    item26.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item32 = RadioBox( parent, ID_STATFTFOR, "Fatturato fornitori", wx.DefaultPosition, wx.DefaultSize, 
        ["x","+","-"] , 1, wx.RA_SPECIFY_ROWS )
    item32.SetName( "statftfor" )
    item26.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item26.AddGrowableCol( 0 )

    item1.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.BOTTOM, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableCol( 1 )

    item1.AddGrowableCol( 2 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
