# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: tipsolpag.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from anag.basetab import AnagCardPanel, WorkZoneNotebook

from awc.controls.linktable import LinkTable
from awc.controls.attachbutton import AttachmentButton

import awc.controls.windows as aw

from Env import Azienda
bt = Azienda.BaseTab

from awc.controls.numctrl import NumCtrl
from awc.controls.textctrl import TextCtrl, TextCtrl_LC


# Window functions

ID_ANAGMAIN = 16000
ID_WORKZONE = 16001

def TipSolPagCardFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = AnagCardPanel(parent)
    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item3 = WorkZoneNotebook( parent, ID_WORKZONE, wx.DefaultPosition, [200,160], 0 )
    item2 = item3
    
    item4 = aw.Panel(item3, -1); item4.SetName('CatArtAnagPage')
    TipSolPagCardAnagFunc(item4, False)
    item3.AddPage( item4, "Dati anagrafici" )

    item0.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 16002
ID_LIVELLO = 16003
ID_TEXTCTRL = 16004

def TipSolPagCardAnagFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item2 = wx.StaticText( parent, ID_TEXT, "Livello (1/2/3):", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item2, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item3 = NumCtrl(parent, ID_LIVELLO, integerWidth=1, fractionWidth=0, name='livello')
    item1.Add( item3, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item1, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item4 = wx.StaticText( parent, ID_TEXT, "Testo accompagnatorio:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetForegroundColour( wx.BLUE )
    item0.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item5 = TextCtrl_LC( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [600,250], wx.TE_MULTILINE )
    item5.SetFont( wx.Font( 10, wx.MODERN, wx.NORMAL, wx.NORMAL ) )
    item5.SetName( "template" )
    item0.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 2 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
