# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: incpagdet.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from awc.controls.datectrl import DateCtrl

import anag.lib as alib



# Window functions

ID_IS_ENTRATE = 32000
ID_IS_USCITE = 32001
ID_TEXT = 32002
ID_DATMIN = 32003
ID_DATMAX = 32004
ID_BUTUPD = 32005
ID_PANGRIDCAS = 32006
ID_PANGRIDREG = 32007
ID_PANGRIDDET = 32008
ID_BUTPRT = 32009

def DettaglioIncassiPagamentiFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = wx.StaticBox( parent, -1, "Tipo" )
    item2 = wx.StaticBoxSizer( item3, wx.VERTICAL )
    
    item4 = wx.CheckBox( parent, ID_IS_ENTRATE, "Entrate", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetName( "is_entrate" )
    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item5 = wx.CheckBox( parent, ID_IS_USCITE, "Uscite", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.SetName( "is_uscite" )
    item2.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item7 = wx.StaticBox( parent, -1, "Selezioni" )
    item6 = wx.StaticBoxSizer( item7, wx.VERTICAL )
    
    item8 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item9 = wx.StaticText( parent, ID_TEXT, "Registrazioni dal:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item9, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item10 = DateCtrl( parent, ID_DATMIN, "", wx.DefaultPosition, [80,-1], 0 )
    item10.SetName( "datmin" )
    item8.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.StaticText( parent, ID_TEXT, "al:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item8.Add( item11, 0, wx.ALIGN_CENTER|wx.LEFT|wx.TOP|wx.BOTTOM, 5 )

    item12 = DateCtrl( parent, ID_DATMAX, "", wx.DefaultPosition, [80,-1], 0 )
    item12.SetName( "datmax" )
    item8.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.Button( parent, ID_BUTUPD, "Aggiorna", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.SetName( "butupd" )
    item8.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6.Add( item8, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item14 = wx.Panel( parent, ID_PANGRIDCAS, wx.DefaultPosition, [322,80], wx.SUNKEN_BORDER )
    item14.SetName( "pangridcas" )
    item1.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item1.AddGrowableCol( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item16 = wx.StaticText( parent, ID_TEXT, "Elenco registrazioni", wx.DefaultPosition, wx.DefaultSize, 0 )
    item16.SetForegroundColour( wx.BLUE )
    item15.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.TOP, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Dettaglio operazione", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.SetForegroundColour( wx.BLUE )
    item15.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item18 = wx.Panel( parent, ID_PANGRIDREG, wx.DefaultPosition, [700,350], wx.SUNKEN_BORDER )
    item18.SetName( "pangridreg" )
    item15.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item19 = wx.Panel( parent, ID_PANGRIDDET, wx.DefaultPosition, [322,160], wx.SUNKEN_BORDER )
    item19.SetName( "pangriddet" )
    item15.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item15.AddGrowableCol( 0 )

    item15.AddGrowableRow( 1 )

    item0.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item20 = wx.Button( parent, ID_BUTPRT, "Stampa", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.SetName( "butprt" )
    item0.Add( item20, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 1 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
