# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: spesometro_2017.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid
import wx.animate

# Custom source
from awc.controls.linktable import LinkTable
from awc.controls.textctrl import TextCtrl
from awc.controls.datectrl import DateCtrl
from awc.controls.numctrl import NumCtrl
from awc.controls.checkbox import CheckBox, RCheckBox
from awc.controls.radiobox import RadioBox

import anag.lib as alib

from Env import Azienda
bt = Azienda.BaseTab

class AcquistiVenditeRadioBox(RadioBox):
    def __init__(self, *args, **kwargs):
        RadioBox.__init__(self, *args, **kwargs)
        self.SetDataLink(values=["A", "V"])




# Window functions

ID_ACQVEN = 10000
ID_TEXT = 10001
ID_DATA1 = 10002
ID_DATA2 = 10003
ID_SOLO_ANAG_ALL = 10004
ID_SOLO_CAUS_ALL = 10005
ID_BUTUPD = 10006
ID_PANGRIDSPE = 10007
ID_TOTNUMOPE = 10008
ID_TOTNUMPDC = 10009
ID_TOTIMPONIB = 10010
ID_TOTIMPOSTA = 10011
ID_TOTINDEDUC = 10012
ID_TOTIMPORTO = 10013
ID_NUMPROGR = 10014
ID_BUTGEN = 10015
ID_WARNING = 10016

def SpesometroPanelFunc( parent, call_fit = True, set_sizer = True ):
    item0 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item1 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item2 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item3 = AcquistiVenditeRadioBox( parent, ID_ACQVEN, "Tipo", wx.DefaultPosition, wx.DefaultSize, 
        ["Acquisti","Vendite"] , 2, wx.RA_SPECIFY_ROWS )
    item3.SetName( "acqven" )
    item2.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.ALL, 5 )

    item5 = wx.StaticBox( parent, -1, "Periodo" )
    item4 = wx.StaticBoxSizer( item5, wx.VERTICAL )
    
    item6 = wx.FlexGridSizer( 0, 4, 0, 0 )
    
    item7 = wx.StaticText( parent, ID_TEXT, "Registrazioni dal:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item8 = DateCtrl( parent, ID_DATA1, "", wx.DefaultPosition, [80,-1], 0 )
    item8.SetName( "data1" )
    item6.Add( item8, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item9 = wx.StaticText( parent, ID_TEXT, "al:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item9, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item10 = DateCtrl( parent, ID_DATA2, "", wx.DefaultPosition, [80,-1], 0 )
    item10.SetName( "data2" )
    item6.Add( item10, 0, wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.BOTTOM, 5 )

    item4.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item4, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item12 = wx.StaticBox( parent, -1, "Considera" )
    item11 = wx.StaticBoxSizer( item12, wx.VERTICAL )
    
    item13 = wx.CheckBox( parent, ID_SOLO_ANAG_ALL, "Solo anagrafiche in allegato", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.SetValue( True )
    item13.SetName( "solo_anag_all" )
    item11.Add( item13, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item14 = wx.CheckBox( parent, ID_SOLO_CAUS_ALL, "Solo causali in allegato", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.SetValue( True )
    item14.SetName( "solo_caus_all" )
    item11.Add( item14, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item2.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item2.AddGrowableCol( 2 )

    item1.Add( item2, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.Button( parent, ID_BUTUPD, "Aggiorna", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.SetDefault()
    item15.SetName( "butupd" )
    item1.Add( item15, 0, wx.ALIGN_RIGHT|wx.ALIGN_BOTTOM|wx.RIGHT|wx.TOP|wx.BOTTOM, 5 )

    item16 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item17 = wx.StaticText( parent, ID_TEXT, "Righe IVA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item17.SetForegroundColour( wx.BLUE )
    item16.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item18 = wx.Panel( parent, ID_PANGRIDSPE, wx.DefaultPosition, [800,160], wx.SUNKEN_BORDER )
    item18.SetName( "pangridspe" )
    item16.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item16.AddGrowableCol( 0 )

    item16.AddGrowableRow( 1 )

    item1.Add( item16, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item19 = wx.FlexGridSizer( 0, 2, 0, 0 )
    
    item1.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item21 = wx.StaticBox( parent, -1, "Totali" )
    item20 = wx.StaticBoxSizer( item21, wx.VERTICAL )
    
    item22 = wx.FlexGridSizer( 0, 6, 0, 0 )
    
    item23 = wx.StaticText( parent, ID_TEXT, "Registrazioni", wx.DefaultPosition, [60,-1], 0 )
    item22.Add( item23, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Anagrafiche", wx.DefaultPosition, [60,-1], 0 )
    item22.Add( item24, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item25 = wx.StaticText( parent, ID_TEXT, "Tot.Imponibile", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item25, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item26 = wx.StaticText( parent, ID_TEXT, "Tot.Imposta", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item26, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item27 = wx.StaticText( parent, ID_TEXT, "Tot.Indeduc.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item27, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item28 = wx.StaticText( parent, ID_TEXT, "Tot.Imp.+IVA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item22.Add( item28, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT, 5 )

    item29 = wx.StaticText( parent, ID_TOTNUMOPE, "0", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item29.SetName( "totnumope" )
    item22.Add( item29, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.RIGHT, 5 )

    item30 = wx.StaticText( parent, ID_TOTNUMPDC, "0", wx.DefaultPosition, [-1,30], wx.ST_NO_AUTORESIZE )
    item30.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item30.SetName( "totnumpdc" )
    item22.Add( item30, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.RIGHT, 5 )

    item31 = wx.StaticText( parent, ID_TOTIMPONIB, "0", wx.DefaultPosition, wx.DefaultSize, 0 )
    item31.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item31.SetName( "totimponib" )
    item22.Add( item31, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.RIGHT, 5 )

    item32 = wx.StaticText( parent, ID_TOTIMPOSTA, "0", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item32.SetName( "totimposta" )
    item22.Add( item32, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.RIGHT, 5 )

    item33 = wx.StaticText( parent, ID_TOTINDEDUC, "0", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item33.SetName( "totindeduc" )
    item22.Add( item33, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.RIGHT, 5 )

    item34 = wx.StaticText( parent, ID_TOTIMPORTO, "0", wx.DefaultPosition, wx.DefaultSize, 0 )
    item34.SetFont( wx.Font( 10, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item34.SetName( "totimporto" )
    item22.Add( item34, 0, wx.ALIGN_RIGHT|wx.LEFT|wx.RIGHT, 5 )

    item22.Add( [ 1, 1 ] , 0, wx.ALIGN_CENTER, 5 )

    item22.Add( [ 120, 1 ] , 0, wx.ALIGN_CENTER, 5 )

    item22.Add( [ 120, 1 ] , 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item22.Add( [ 120, 1 ] , 0, wx.ALIGN_CENTER|wx.ALL, 0 )

    item20.Add( item22, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item35 = wx.BoxSizer( wx.VERTICAL )
    
    item36 = wx.FlexGridSizer( 0, 1, 0, 0 )
    
    item37 = wx.StaticText( parent, ID_TEXT, "Num.Progr.", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.Add( item37, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.TOP, 5 )

    item38 = NumCtrl(parent, ID_NUMPROGR, integerWidth=3, fractionWidth=0, name='numprogr')
    item36.Add( item38, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.LEFT|wx.RIGHT|wx.BOTTOM, 5 )

    item39 = wx.Button( parent, ID_BUTGEN, "Genera file", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.SetName( "butgen" )
    item36.Add( item39, 0, wx.ALIGN_RIGHT|wx.BOTTOM, 5 )

    item35.Add( item36, 0, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item1.Add( item35, 0, wx.ALIGN_BOTTOM|wx.RIGHT, 5 )

    item1.AddGrowableCol( 0 )

    item1.AddGrowableRow( 1 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item40 = wx.FlexGridSizer( 1, 0, 0, 0 )
    
    item40.AddGrowableCol( 0 )

    item0.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item41 = wx.StaticText( parent, ID_WARNING, "-", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.SetForegroundColour( wx.RED )
    item41.SetFont( wx.Font( 12, wx.SWISS, wx.NORMAL, wx.BOLD ) )
    item41.SetName( "warning" )
    item0.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.AddGrowableCol( 0 )

    item0.AddGrowableRow( 0 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
